In [1]:
#!/usr/bin/env python3
import csv
import io
import requests
from slugify import slugify


DAWUM_API_URL = 'https://api.dawum.de/'
SLUGIFY_GERMAN_UMLAUTS = [
    ['ä', 'ae'],
    ['Ä', 'Ae'],
    ['ö', 'oe'],
    ['Ö', 'Oe'],
    ['ü', 'ue'],
    ['Ü', 'Ue'],
]

rsp = requests.get(DAWUM_API_URL)
data = rsp.json()

# Parse Parliaments
parliaments = {}
for key, value in data['Parliaments'].items():
    parliaments[key] = {
        'parliament_id': slugify(value['Shortcut']),
        'parliament_name': value['Name']
    }

# Parse Institutes
institutes = {}
for key, value in data['Institutes'].items():
    institutes[key] = {
        'institute_id': slugify(value['Name']),
        'institute_name': value['Name'],
    }

# Parse Taskers
taskers = {}
for key, value in data['Taskers'].items():
    taskers[key] = {
        'tasker_id': slugify(value['Name'], replacements=SLUGIFY_GERMAN_UMLAUTS),
        'tasker_name': value['Name'],
    }

# Parse Parties
parties = {}
for key, value in data['Parties'].items():
    parties[key] = {
        'party_id': slugify(value['Shortcut'], replacements=SLUGIFY_GERMAN_UMLAUTS),
        'party_name': value['Name'],
    }

# Parse Surveys
surveys = {}
result_fieldnames = set()
for key, value in data['Surveys'].items():
    surveys[key] = {
        'survey_id': key,
        'survey_date': value['Date'],
        'survey_persons': value['Surveyed_Persons'],
        'survey_start': value['Survey_Period']['Date_Start'],
        'survey_end': value['Survey_Period']['Date_End'],
    }
    surveys[key].update(
        parliaments[value['Parliament_ID']]
    )
    surveys[key].update(
        taskers[value['Tasker_ID']]
    )
    surveys[key].update(
        institutes[value['Institute_ID']]
    )
    for party_id, result in value['Results'].items():
        col = 'result_' + parties[party_id]['party_id']
        result_fieldnames.add(col)
        surveys[key][col] = float(result)


f = io.StringIO()
fieldnames = [
    'survey_id', 'survey_date', 'survey_persons', 'survey_start', 'survey_end',
    'parliament_id', 'parliament_name',
    'institute_id', 'institute_name',
    'tasker_id', 'tasker_name',
]
fieldnames += result_fieldnames
writer = csv.DictWriter(f, fieldnames=fieldnames)
writer.writeheader()
for survey in surveys.values():
    writer.writerow(survey)
print(f.getvalue())

survey_id,survey_date,survey_persons,survey_start,survey_end,parliament_id,parliament_name,institute_id,institute_name,tasker_id,tasker_name,result_volt,result_familie,result_die-partei,result_plus-brandenburg,result_bd,result_bsw,result_afd,result_gruene,result_tierschutzpartei,result_spd,result_npd,result_linke,result_bfth,result_cdu,result_bayernpartei,result_werteunion,result_piraten,result_fdp,result_csu,result_oedp,result_cdu-csu,result_freie-waehler,result_ssw,result_bunt-saar,result_bvb-fw,result_sonstige
4028,2025-12-09,2503,2025-12-02,2025-12-08,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,14.0,,11.0,,,,,,3.0,,,24.0,,,,,7.0
4027,2025-12-09,2007,2025-12-05,2025-12-08,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.5,10.5,,15.0,,11.0,,,,,,4.0,,,24.5,,,,,4.5
4025,2025-12-06,1206,2025-12-01,2025-12-05,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,10.0,,15.0,,11.0,,,,,,4.0,,,25.0,,,,,5.0
4024,2025-12-04,1306,2025-12-01,2025-12-03,bundestag,Bundestag,infratest-dimap,Infratest dimap,ard-tagesthemen,ARD-Tagesthemen,,,,,,4.0,25.0,12.0,,14.0,,10.0,,,,,,3.0,,,27.0,,,,,5.0
4023,2025-12-04,1000,2025-11-28,2025-11-30,bundestag,Bundestag,ipsos,Ipsos,ipsos,Ipsos,,,,,,4.0,26.0,13.0,,15.0,,10.0,,,,,,4.0,,,23.0,,,,,5.0
4022,2025-12-03,1150,2025-11-20,2025-11-26,saarland,Saarländischer Landtag,infratest-dimap,Infratest dimap,saarlaendischer-rundfunk,Saarländischer Rundfunk,,,,,,3.0,23.0,7.0,,27.0,,7.0,,25.0,,,,,,,,,,,,8.0
4026,2025-12-03,3020,2025-11-26,2025-12-02,bundestag,Bundestag,pollytix,pollytix,pollytix,pollytix,,,,,,4.0,26.0,11.0,,15.0,,10.0,,,,,,4.0,,,26.0,,,,,4.0
4021,2025-12-02,2501,2025-11-25,2025-12-01,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,14.0,,11.0,,,,,,3.0,,,25.0,,,,,6.0
4020,2025-12-02,2969,2025-11-12,2025-11-26,berlin,Berliner Abgeordnetenhaus,civey,Civey,der-tagesspiegel,Der Tagesspiegel,,,,,,5.0,16.0,15.0,,13.0,,18.0,,23.0,,,,3.0,,,,,,,,7.0
4019,2025-12-02,2002,2025-11-28,2025-12-01,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,27.0,11.0,,14.5,,10.5,,,,,,3.5,,,24.5,,,,,5.0
4018,2025-11-28,1198,2025-11-24,2025-11-28,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,27.0,11.0,,15.0,,10.0,,,,,,3.0,,,25.0,,,,,5.0
4017,2025-11-25,2501,2025-11-18,2025-11-24,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,14.0,,11.0,,,,,,3.0,,,25.0,,,,,6.0
4016,2025-11-25,2008,2025-11-21,2025-11-24,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.0,11.0,,15.0,,10.5,,,,,,3.0,,,25.5,,,,,5.0
4015,2025-11-23,1000,2025-11-11,2025-11-18,nordrhein-westfalen-nrw,Landtag von Nordrhein-Westfalen,insa,INSA,bild,BILD,,,,,,,16.0,12.0,,19.0,,7.0,,36.0,,,,5.0,,,,,,,,5.0
4014,2025-11-22,1208,2025-11-17,2025-11-21,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,11.0,,15.0,,10.0,,,,,,3.0,,,25.0,,,,,6.0
4012,2025-11-21,1207,2025-11-18,2025-11-20,bundestag,Bundestag,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,zdf-politbarometer,ZDF-Politbarometer,,,,,,,27.0,12.0,,14.0,,9.0,,,,,,,,,27.0,,,,,11.0
4011,2025-11-19,2005,2025-11-14,2025-11-17,bundestag,Bundestag,yougov,YouGov,yougov,YouGov,,,,,,4.0,25.0,11.0,,14.0,,11.0,,,,,,4.0,,,27.0,,,,,5.0
4010,2025-11-19,1185,2025-11-13,2025-11-17,berlin,Berliner Abgeordnetenhaus,infratest-dimap,Infratest dimap,rbb-abendschau-rbb-88-8,RBB Abendschau / RBB 88.8,,,,,,4.0,16.0,16.0,,13.0,,19.0,,22.0,,,,,,,,,,,,10.0
4009,2025-11-19,1156,2025-11-12,2025-11-17,niedersachsen,Niedersächsischer Landtag,infratest-dimap,Infratest dimap,ndr,NDR,,,,,,3.0,20.0,12.0,,26.0,,6.0,,26.0,,,,3.0,,,,,,,,4.0
4008,2025-11-18,2502,2025-11-11,2025-11-17,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,,26.0,12.0,,14.0,,11.0,,,,,,3.0,,,25.0,,,,,9.0
4007,2025-11-18,2006,2025-11-14,2025-11-17,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.0,11.0,,15.0,,11.0,,,,,,3.5,,,24.5,,,,,5.0
4006,2025-11-17,1020,2025-11-11,2025-11-17,bundestag,Bundestag,gms,GMS,gms,GMS,,,,,,3.0,26.0,12.0,,14.0,,11.0,,,,,,3.0,,,25.0,,,,,6.0
4013,2025-11-15,5000,2025-10-30,2025-11-13,bayern,Bayerischer Landtag,civey,Civey,augsburger-allgemeine,Augsburger Allgemeine,,,,,,2.0,20.0,12.0,,8.0,,5.0,,,,,,1.0,40.0,,,9.0,,,,3.0
4005,2025-11-15,1203,2025-11-10,2025-11-14,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,11.0,,15.0,,11.0,,,,,,3.0,,,25.0,,,,,5.0
4004,2025-11-14,1011,2025-10-23,2025-11-06,bundestag,Bundestag,allensbach,Allensbach,frankfurter-allgemeine-zeitung,Frankfurter Allgemeine Zeitung,,,,,,4.0,24.0,11.0,,15.5,,10.0,,,,,,3.5,,,27.0,,,,,5.0
4003,2025-11-12,1000,2025-11-07,2025-11-09,bundestag,Bundestag,ipsos,Ipsos,ipsos,Ipsos,,,,,,4.0,26.0,12.0,,15.0,,11.0,,,,,,4.0,,,24.0,,,,,4.0
4002,2025-11-11,2503,2025-11-04,2025-11-10,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,14.0,,11.0,,,,,,3.0,,,24.0,,,,,7.0
4001,2025-11-11,2010,2025-11-07,2025-11-10,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.0,11.5,,15.5,,10.5,,,,,,3.0,,,25.0,,,,,4.5
4000,2025-11-08,1205,2025-11-03,2025-11-07,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,12.0,,15.0,,11.0,,,,,,3.0,,,25.0,,,,,4.0
3999,2025-11-07,1471,2025-10-28,2025-11-04,bundestag,Bundestag,verian-emnid,Verian (Emnid),focus,FOCUS,,,,,,3.0,25.0,12.0,,15.0,,10.0,,,,,,3.0,,,26.0,,,,,6.0
3998,2025-11-07,1322,2025-11-04,2025-11-06,bundestag,Bundestag,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,zdf-politbarometer,ZDF-Politbarometer,,,,,,,26.0,12.0,,14.0,,10.0,,,,,,,,,26.0,,,,,12.0
3997,2025-11-06,1300,2025-11-03,2025-11-05,bundestag,Bundestag,infratest-dimap,Infratest dimap,ard-tagesthemen,ARD-Tagesthemen,,,,,,3.0,26.0,12.0,,14.0,,10.0,,,,,,3.0,,,27.0,,,,,5.0
3996,2025-11-04,2500,2025-10-28,2025-11-03,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,14.0,,12.0,,,,,,3.0,,,24.0,,,,,6.0
3995,2025-11-03,2002,2025-10-30,2025-11-03,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,25.5,11.0,,15.0,,11.0,,,,,,3.0,,,25.5,,,,,5.0
3993,2025-11-01,1202,2025-10-27,2025-10-30,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,11.0,,15.0,,11.0,,,,,,3.0,,,25.0,,,,,5.0
3992,2025-10-28,1000,2025-10-21,2025-10-28,berlin,Berliner Abgeordnetenhaus,insa,INSA,nius,NIUS,,,,,,5.0,15.0,14.0,,16.0,,17.0,,23.0,,,,4.0,,,,,,,,6.0
3991,2025-10-28,2502,2025-10-21,2025-10-27,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,13.0,,12.0,,,,,,3.0,,,25.0,,,,,6.0
3990,2025-10-27,2004,2025-10-24,2025-10-27,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.0,11.0,,15.0,,11.5,,,,,,3.5,,,24.5,,,,,4.5
3989,2025-10-25,1205,2025-10-20,2025-10-24,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,11.0,,15.0,,11.0,,,,,,4.0,,,24.0,,,,,5.0
3988,2025-10-24,1272,2025-10-21,2025-10-23,bundestag,Bundestag,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,zdf-politbarometer,ZDF-Politbarometer,,,,,,,25.0,11.0,,15.0,,10.0,,,,,,,,,27.0,,,,,12.0
3987,2025-10-21,2505,2025-10-14,2025-10-20,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,26.0,12.0,,14.0,,11.0,,,,,,3.0,,,24.0,,,,,6.0
3986,2025-10-21,2006,2025-10-17,2025-10-20,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.5,27.0,11.0,,14.0,,11.0,,,,,,4.0,,,24.5,,,,,4.0
3985,2025-10-18,1200,2025-10-13,2025-10-17,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,27.0,11.0,,14.0,,11.0,,,,,,4.0,,,25.0,,,,,4.0
3984,2025-10-17,1044,2025-09-26,2025-10-10,bundestag,Bundestag,allensbach,Allensbach,frankfurter-allgemeine-zeitung,Frankfurter Allgemeine Zeitung,,,,,,4.0,25.0,11.0,,15.0,,11.0,,,,,,3.0,,,26.0,,,,,5.0
3983,2025-10-16,1000,2025-10-07,2025-10-14,baden-wurttemberg,Landtag von Baden-Württemberg,insa,INSA,schwaebische-zeitung,Schwäbische Zeitung,,,,,,3.0,20.0,17.0,,11.0,,7.0,,31.0,,,,7.0,,,,,,,,4.0
3982,2025-10-16,1158,2025-10-08,2025-10-14,baden-wurttemberg,Landtag von Baden-Württemberg,infratest-dimap,Infratest dimap,swr-stuttgarter-zeitung,SWR / Stuttgarter Zeitung,,,,,,3.0,21.0,20.0,,10.0,,7.0,,29.0,,,,5.0,,,,,,,,5.0
3981,2025-10-15,1880,2025-10-10,2025-10-13,bundestag,Bundestag,yougov,YouGov,yougov,YouGov,,,,,,4.0,26.0,11.0,,14.0,,10.0,,,,,,3.0,,,27.0,,,,,5.0
3980,2025-10-15,1000,2025-10-07,2025-10-14,sachsen-anhalt,Landtag von Sachsen-Anhalt,insa,INSA,nius,NIUS,,,,,,6.0,40.0,3.0,,6.0,,11.0,,26.0,,,,3.0,,,,,,,,5.0
3979,2025-10-14,2500,2025-10-07,2025-10-13,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,26.0,12.0,,13.0,,12.0,,,,,,3.0,,,24.0,,,,,6.0
3978,2025-10-14,2008,2025-10-10,2025-10-13,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.5,11.5,,14.0,,10.5,,,,,,4.0,,,25.0,,,,,4.5
3977,2025-10-12,1224,2025-10-06,2025-10-10,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,12.0,,14.0,,11.0,,,,,,4.0,,,24.0,,,,,5.0
3994,2025-10-11,5000,2025-09-24,2025-10-09,bayern,Bayerischer Landtag,civey,Civey,augsburger-allgemeine,Augsburger Allgemeine,,,,,,2.0,20.0,11.0,,8.0,,4.0,,,,,,2.0,38.0,,,10.0,,,,5.0
3976,2025-10-10,1478,2025-09-30,2025-10-07,bundestag,Bundestag,verian-emnid,Verian (Emnid),focus,FOCUS,,,,,,4.0,25.0,12.0,,15.0,,10.0,,,,,,3.0,,,25.0,,,,,6.0
3975,2025-10-09,976,2025-09-30,2025-10-07,hessen,Hessischer Landtag,insa,INSA,bild,BILD,,,,,,3.0,20.0,12.0,,15.0,,7.0,,32.0,,,,4.0,,,,3.0,,,,4.0
3974,2025-10-09,1000,2025-10-02,2025-10-03,bundestag,Bundestag,ipsos,Ipsos,ipsos,Ipsos,,,,,,5.0,25.0,11.0,,15.0,,12.0,,,,,,4.0,,,23.0,,,,,5.0
3973,2025-10-09,1158,2025-10-01,2025-10-07,rheinland-pfalz,Landtag von Rheinland-Pfalz,infratest-dimap,Infratest dimap,swr-zur-sache-rheinland-pfalz,SWR Zur Sache Rheinland-Pfalz,,,,,,,19.0,10.0,,23.0,,6.0,,29.0,,,,,,,,4.0,,,,9.0
3972,2025-10-07,2001,2025-09-30,2025-10-06,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,26.0,12.0,,13.0,,12.0,,,,,,3.0,,,24.0,,,,,6.0
3971,2025-10-06,2010,2025-10-02,2025-10-06,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.5,11.0,,14.5,,11.5,,,,,,3.5,,,24.5,,,,,4.5
3970,2025-10-04,1186,2025-09-29,2025-10-02,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,11.0,,14.0,,12.0,,,,,,4.0,,,24.0,,,,,5.0
3969,2025-10-04,1000,2025-09-16,2025-09-23,rheinland-pfalz,Landtag von Rheinland-Pfalz,insa,INSA,bild,BILD,,,,,,4.0,23.0,9.0,,22.0,,6.0,,27.0,,,,4.0,,,,3.0,,,,2.0
3968,2025-10-02,1306,2025-09-29,2025-10-01,bundestag,Bundestag,infratest-dimap,Infratest dimap,ard-tagesthemen,ARD-Tagesthemen,,,,,,3.0,26.0,12.0,,14.0,,10.0,,,,,,3.0,,,26.0,,,,,6.0
3967,2025-10-02,1300,2025-09-29,2025-10-01,bundestag,Bundestag,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,zdf-politbarometer,ZDF-Politbarometer,,,,,,,25.0,11.0,,15.0,,11.0,,,,,,3.0,,,27.0,,,,,8.0
3966,2025-09-30,1012,2025-09-24,2025-09-29,bundestag,Bundestag,gms,GMS,gms,GMS,,,,,,3.0,25.0,11.0,,15.0,,10.0,,,,,,3.0,,,26.0,1.0,,,,6.0
3965,2025-09-30,1017,2025-09-24,2025-09-29,bayern,Bayerischer Landtag,gms,GMS,sat-1-bayern,SAT.1 Bayern,,,,,,2.0,19.0,11.0,,7.0,,4.0,,,1.0,,,2.0,39.0,,,11.0,,,,4.0
3964,2025-09-30,2502,2025-09-23,2025-09-29,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,27.0,12.0,,13.0,,11.0,,,,,,3.0,,,24.0,,,,,6.0
3963,2025-09-29,2006,2025-09-26,2025-09-29,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.0,11.5,,15.5,,11.0,,,,,,3.0,,,25.0,,,,,4.0
3962,2025-09-27,1200,2025-09-22,2025-09-26,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,12.0,,15.0,,11.0,,,,,,3.0,,,25.0,,,,,4.0
3960,2025-09-25,1151,2025-09-18,2025-09-23,mecklenburg-vorpommern,Landtag von Mecklenburg-Vorpommern,infratest-dimap,Infratest dimap,ndr,NDR,,,,,,7.0,38.0,5.0,,19.0,,12.0,,13.0,,,,,,,,,,,,6.0
3961,2025-09-24,1013,2025-09-05,2025-09-17,bundestag,Bundestag,allensbach,Allensbach,frankfurter-allgemeine-zeitung,Frankfurter Allgemeine Zeitung,,,,,,3.0,24.0,11.0,,15.0,,11.0,,,,,,4.0,,,27.0,,,,,5.0
3959,2025-09-23,2504,2025-09-16,2025-09-22,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,27.0,11.0,,13.0,,11.0,,,,,,3.0,,,25.0,,,,,6.0
3958,2025-09-23,2002,2025-09-19,2025-09-22,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,26.0,11.0,,14.5,,11.5,,,,,,3.5,,,24.5,,,,,5.0
3957,2025-09-20,1200,2025-09-15,2025-09-19,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,26.0,11.0,,15.0,,11.0,,,,,,3.0,,,25.0,,,,,5.0
3955,2025-09-19,1419,2025-09-16,2025-09-18,bundestag,Bundestag,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,zdf-politbarometer,ZDF-Politbarometer,,,,,,3.0,26.0,10.0,,15.0,,11.0,,,,,,3.0,,,26.0,,,,,6.0
3956,2025-09-18,1000,2025-09-09,2025-09-16,brandenburg,Brandenburgischer Landtag,insa,INSA,maerkische-allgemeine-zeitung-maz-maerkische-oderzeitung-moz-lausitzer-rundschau-lr,Märkische Allgemeine Zeitung (MAZ) / Märkische Oderzeitung (MOZ) / Lausitzer Rundschau (LR),,,,,,9.0,34.0,4.0,,24.0,,9.0,,13.0,,,,2.0,,,,,,,2.0,3.0
3954,2025-09-17,3000,2025-09-02,2025-09-16,berlin,Berliner Abgeordnetenhaus,civey,Civey,der-tagesspiegel,Der Tagesspiegel,,,,,,7.0,16.0,15.0,,13.0,,16.0,,25.0,,,,2.0,,,,,,,,6.0
3952,2025-09-17,1649,2025-09-12,2025-09-15,bundestag,Bundestag,yougov,YouGov,yougov,YouGov,,,,,,5.0,27.0,11.0,,15.0,,9.0,,,,,,4.0,,,26.0,,,,,4.0
3951,2025-09-16,2502,2025-09-09,2025-09-15,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,25.0,12.0,,14.0,,11.0,,,,,,3.0,,,25.0,,,,,6.0
3950,2025-09-16,2004,2025-09-12,2025-09-15,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,25.5,11.5,,14.5,,11.0,,,,,,3.0,,,25.5,,,,,5.0
3948,2025-09-13,1204,2025-09-08,2025-09-12,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,25.0,12.0,,14.0,,11.0,,,,,,3.0,,,25.0,,,,,6.0
3953,2025-09-13,5000,2025-08-29,2025-09-12,bayern,Bayerischer Landtag,civey,Civey,augsburger-allgemeine,Augsburger Allgemeine,,,,,,2.0,20.0,13.0,,8.0,,1.0,,,,,,1.0,40.0,,,10.0,,,,5.0
3949,2025-09-12,1012,2025-09-01,2025-09-10,bayern,Bayerischer Landtag,forsa,Forsa,sueddeutsche-zeitung,Süddeutsche Zeitung,,,,,,1.0,19.0,15.0,,8.0,,5.0,,,,,,2.0,37.0,,,10.0,,,,3.0
3946,2025-09-11,1000,2025-09-02,2025-09-09,thuringen,Thüringischer Landtag,insa,INSA,funke-medien-thueringen,FUNKE Medien Thüringen,,,,,,9.0,37.0,3.0,,7.0,,14.0,,25.0,,,,,,,,,,,,5.0
3947,2025-09-10,1460,2025-09-03,2025-09-09,bundestag,Bundestag,verian-emnid,Verian (Emnid),focus,FOCUS,,,,,,4.0,25.0,11.0,,15.0,,11.0,,,,,,3.0,,,26.0,,,,,5.0
3945,2025-09-10,1000,2025-09-05,2025-09-07,bundestag,Bundestag,ipsos,Ipsos,ipsos,Ipsos,,,,,,4.0,25.0,12.0,,15.0,,12.0,,,,,,3.0,,,24.0,,,,,5.0
3944,2025-09-09,2500,2025-09-02,2025-09-08,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,11.0,,14.0,,12.0,,,,,,3.0,,,25.0,,,,,6.0
3943,2025-09-08,2006,2025-09-05,2025-09-08,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.5,25.5,11.0,,14.5,,10.0,,,,,,3.5,,,25.5,,,,,5.5
3942,2025-09-07,1287,2025-09-01,2025-09-05,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,25.0,12.0,,15.0,,11.0,,,,,,3.0,,,26.0,,,,,4.0
3940,2025-09-05,1269,2025-09-02,2025-09-04,bundestag,Bundestag,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,zdf-politbarometer,ZDF-Politbarometer,,,,,,3.0,25.0,11.0,,15.0,,10.0,,,,,,3.0,,,27.0,,,,,6.0
3939,2025-09-04,1167,2025-08-28,2025-09-02,sachsen-anhalt,Landtag von Sachsen-Anhalt,infratest-dimap,Infratest dimap,mdr-mitteldeutsche-zeitung-volksstimme,MDR / Mitteldeutsche Zeitung / Volksstimme,,,,,,6.0,39.0,3.0,,7.0,,13.0,,27.0,,,,,,,,,,,,5.0
3938,2025-09-03,1342,2025-09-01,2025-09-02,bundestag,Bundestag,infratest-dimap,Infratest dimap,ard-tagesthemen,ARD-Tagesthemen,,,,,,4.0,25.0,11.0,,14.0,,10.0,,,,,,3.0,,,27.0,,,,,6.0
3941,2025-09-03,1533,2025-08-26,2025-09-02,bundestag,Bundestag,pollytix,pollytix,pollytix,pollytix,,,,,,5.0,25.0,11.0,,16.0,,9.0,,,,,,4.0,,,27.0,,,,,3.0
3937,2025-09-02,2502,2025-08-26,2025-09-01,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,11.0,,14.0,,12.0,,,,,,3.0,,,25.0,,,,,6.0
3936,2025-09-02,2004,2025-08-29,2025-09-01,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.0,25.0,11.0,,14.5,,11.0,,,,,,3.5,,,25.5,,,,,5.5
3935,2025-08-29,1202,2025-08-25,2025-08-29,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,25.0,11.0,,15.0,,11.0,,,,,,3.0,,,26.0,,,,,5.0
3934,2025-08-26,2501,2025-08-19,2025-08-25,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,13.0,,11.0,,,,,,3.0,,,25.0,,,,,7.0
3933,2025-08-25,2002,2025-08-22,2025-08-25,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.5,25.0,10.5,,15.0,,11.0,,,,,,3.5,,,25.0,,,,,5.5
3932,2025-08-23,1201,2025-08-18,2025-08-22,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,25.0,11.0,,15.0,,11.0,,,,,,3.0,,,25.0,,,,,6.0
3931,2025-08-22,1000,2025-08-13,2025-08-19,nordrhein-westfalen-nrw,Landtag von Nordrhein-Westfalen,insa,INSA,nius,NIUS,,,,,,3.0,16.0,13.0,,18.0,,8.0,,35.0,,,,4.0,,,,,,,,3.0
3930,2025-08-21,1051,2025-08-01,2025-08-14,bundestag,Bundestag,allensbach,Allensbach,frankfurter-allgemeine-zeitung,Frankfurter Allgemeine Zeitung,,,,,,4.0,22.5,11.0,,16.0,,10.0,,,,,,4.0,,,28.0,,,,,4.5
3928,2025-08-20,1831,2025-08-15,2025-08-18,bundestag,Bundestag,yougov,YouGov,yougov,YouGov,,,,,,5.0,25.0,12.0,,14.0,,10.0,,,,,,3.0,,,27.0,,,,,4.0
3927,2025-08-19,2502,2025-08-12,2025-08-18,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,26.0,12.0,,13.0,,12.0,,,,,,3.0,,,25.0,,,,,6.0
3926,2025-08-19,2010,2025-08-15,2025-08-18,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,5.0,25.0,11.0,,14.5,,10.0,,,,,,4.0,,,26.0,,,,,4.5
3929,2025-08-18,5000,2025-07-30,2025-08-14,bayern,Bayerischer Landtag,civey,Civey,augsburger-allgemeine,Augsburger Allgemeine,,,,,,2.0,20.0,13.0,,8.0,,1.0,,,,,,1.0,41.0,,,9.0,,,,5.0
3925,2025-08-16,1206,2025-08-11,2025-08-15,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,25.0,11.0,,15.0,,9.0,,,,,,4.0,,,26.0,,,,,6.0
3924,2025-08-15,1464,2025-08-06,2025-08-12,bundestag,Bundestag,verian-emnid,Verian (Emnid),focus,FOCUS,,,,,,3.0,25.0,12.0,,14.0,,10.0,,,,,,4.0,,,26.0,,,,,6.0
3923,2025-08-14,1370,2025-08-11,2025-08-13,bundestag,Bundestag,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,zdf-politbarometer,ZDF-Politbarometer,,,,,,3.0,23.0,12.0,,15.0,,11.0,,,,,,3.0,,,27.0,,,,,6.0
3922,2025-08-12,2505,2025-08-05,2025-08-11,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,26.0,13.0,,13.0,,11.0,,,,,,3.0,,,24.0,,,,,6.0
3921,2025-08-11,2008,2025-08-08,2025-08-11,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.5,25.0,10.5,,14.5,,9.5,,,,,,3.5,,,27.0,,,,,5.5
3920,2025-08-09,1204,2025-08-03,2025-08-08,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,25.0,11.0,,15.0,,9.0,,,,,,4.0,,,27.0,,,,,5.0
3919,2025-08-07,1321,2025-08-04,2025-08-06,bundestag,Bundestag,infratest-dimap,Infratest dimap,ard-tagesthemen,ARD-Tagesthemen,,,,,,3.0,24.0,12.0,,13.0,,10.0,,,,,,4.0,,,27.0,,,,,7.0
3917,2025-08-07,1000,2025-08-01,2025-08-03,bundestag,Bundestag,ipsos,Ipsos,ipsos,Ipsos,,,,,,5.0,25.0,11.0,,15.0,,11.0,,,,,,3.0,,,25.0,,,,,5.0
3907,2025-08-05,2503,2025-07-29,2025-08-04,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,4.0,25.0,12.0,,13.0,,12.0,,,,,,3.0,,,25.0,,,,,6.0
3906,2025-08-05,2004,2025-08-01,2025-08-04,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.5,25.0,10.5,,14.5,,9.5,,,,,,3.0,,,27.5,,,,,5.5
3916,2025-08-04,2500,2025-07-20,2025-08-04,sachsen,Sächsischer Landtag,civey,Civey,saechsische-zeitung,Sächsische Zeitung,,,,,,9.0,35.0,6.0,,6.0,,10.0,,27.0,,,,1.0,,,,2.0,,,,4.0
3905,2025-08-02,1203,2025-07-28,2025-08-01,bundestag,Bundestag,insa,INSA,bild-am-sonntag,BILD am Sonntag,,,,,,4.0,25.0,11.0,,15.0,,10.0,,,,,,3.0,,,27.0,,,,,5.0
3904,2025-08-01,1473,2025-07-23,2025-07-29,bundestag,Bundestag,verian-emnid,Verian (Emnid),focus,FOCUS,,,,,,3.0,24.0,12.0,,14.0,,11.0,,,,,,4.0,,,27.0,,,,,5.0
3903,2025-07-29,2502,2025-07-22,2025-07-28,bundestag,Bundestag,forsa,Forsa,rtl-n-tv,RTL / n-tv,,,,,,3.0,25.0,12.0,,13.0,,12.0,,,,,,3.0,,,26.0,,,,,6.0
3902,2025-07-28,2006,2025-07-25,2025-07-28,bundestag,Bundestag,insa,INSA,bild,BILD,,,,,,4.5,24.0,10.5,,14.5,,10.0,,,,,,3.5,,,27.5,,,,,5.5

In [6]:
import pandas as pd

# Your existing StringIO object 'f'
surveys_df = pd.DataFrame(surveys.values())
surveys_df

,survey_id,survey_date,survey_persons,survey_start,survey_end,parliament_id,parliament_name,tasker_id,tasker_name,institute_id,...,result_die-partei,result_tierschutzpartei,result_werteunion,result_piraten,result_familie,result_plus-brandenburg,result_bfth,result_bunt-saar,result_oedp,result_npd
0,4028,2025-12-09,2503,2025-12-02,2025-12-08,bundestag,Bundestag,rtl-n-tv,RTL / n-tv,forsa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4027,2025-12-09,2007,2025-12-05,2025-12-08,bundestag,Bundestag,bild,BILD,insa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4025,2025-12-06,1206,2025-12-01,2025-12-05,bundestag,Bundestag,bild-am-sonntag,BILD am Sonntag,insa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4024,2025-12-04,1306,2025-12-01,2025-12-03,bundestag,Bundestag,ard-tagesthemen,ARD-Tagesthemen,infratest-dimap,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4023,2025-12-04,1000,2025-11-28,2025-11-30,bundestag,Bundestag,ipsos,Ipsos,ipsos,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3651,374,2017-01-25,2504,2017-01-16,2017-01-20,bundestag,Bundestag,stern-rtl,Stern / RTL,forsa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3652,373,2017-01-24,5028,2017-01-12,2017-01-23,bundestag,Bundestag,spiegel-online,Spiegel Online,civey,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3653,372,2017-01-24,1992,2017-01-20,2017-01-23,bundestag,Bundestag,bild,BILD,insa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3654,370,2017-01-22,2805,2017-01-12,2017-01-18,bundestag,Bundestag,bild-am-sonntag,BILD am Sonntag,verian-emnid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3655,365,2017-01-18,2503,2017-01-09,2017-01-13,bundestag,Bundestag,stern-rtl,Stern / RTL,forsa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
surveys_df.columns

Index(['survey_id', 'survey_date', 'survey_persons', 'survey_start',
       'survey_end', 'parliament_id', 'parliament_name', 'tasker_id',
       'tasker_name', 'institute_id', 'institute_name', 'result_afd',
       'result_cdu-csu', 'result_spd', 'result_gruene', 'result_linke',
       'result_sonstige', 'result_fdp', 'result_bsw', 'result_cdu',
       'result_csu', 'result_freie-waehler', 'result_bayernpartei',
       'result_bvb-fw', 'result_bd', 'result_volt', 'result_ssw',
       'result_die-partei', 'result_tierschutzpartei', 'result_werteunion',
       'result_piraten', 'result_familie', 'result_plus-brandenburg',
       'result_bfth', 'result_bunt-saar', 'result_oedp', 'result_npd'],
      dtype='object')

In [13]:
surveys_mainpartys=surveys_df[['survey_id', 'survey_date', 'survey_persons', 'survey_start',
       'survey_end', 'parliament_id', 'parliament_name', 'tasker_id',
       'tasker_name', 'institute_id', 'institute_name', 'result_afd',
       'result_cdu-csu', 'result_spd', 'result_gruene', 'result_linke']]

In [18]:
surveys_mainpartys["institute_name"].unique()

array(['Forsa', 'INSA', 'Infratest dimap', 'Ipsos', 'pollytix', 'Civey',
       'Forschungsgruppe Wahlen', 'YouGov', 'GMS', 'Allensbach',
       'Verian (Emnid)', 'Institut Wahlkreisprognose',
       'Trend Research Hamburg', 'IFM Berlin', 'Policy Matters',
       'Universität Hamburg', 'Mentefactum', 'IM Field', 'uniQma',
       'Conoscope', 'dimap', 'GESS Phone & Field'], dtype=object)

In [22]:
surveys_mainpartys[surveys_mainpartys["parliament_name"]=="Landtag von Baden-Württemberg"].iloc[40:60]

,survey_id,survey_date,survey_persons,survey_start,survey_end,parliament_id,parliament_name,tasker_id,tasker_name,institute_id,institute_name,result_afd,result_cdu-csu,result_spd,result_gruene,result_linke
2125,1902,2021-03-10,2069,2021-03-02,2021-03-09,baden-wurttemberg,Landtag von Baden-Württemberg,spiegel-online,Spiegel Online,civey,Civey,12.0,NaN,13.0,32.0,4.0
2126,1901,2021-03-10,1558,2021-03-01,2021-03-07,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,12.0,NaN,10.0,32.0,3.0
2133,1894,2021-03-05,1032,2021-03-01,2021-03-04,baden-wurttemberg,Landtag von Baden-Württemberg,zdf-politbarometer,ZDF-Politbarometer,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,11.0,NaN,10.0,35.0,3.0
2134,1896,2021-03-04,1054,2021-02-27,2021-03-04,baden-wurttemberg,Landtag von Baden-Württemberg,institut-wahlkreisprognose,Institut Wahlkreisprognose,institut-wahlkreisprognose,Institut Wahlkreisprognose,13.0,NaN,12.5,33.0,3.5
2137,1891,2021-03-04,1185,2021-03-01,2021-03-03,baden-wurttemberg,Landtag von Baden-Württemberg,ard,ARD,infratest-dimap,Infratest dimap,12.0,NaN,10.0,33.0,4.0
2159,1869,2021-02-13,1009,2021-02-08,2021-02-11,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,11.0,NaN,11.0,31.0,4.0
2164,1864,2021-02-05,1032,2021-02-01,2021-02-04,baden-wurttemberg,Landtag von Baden-Württemberg,zdf-politbarometer,ZDF-Politbarometer,forschungsgruppe-wahlen,Forschungsgruppe Wahlen,11.0,NaN,10.0,34.0,3.0
2167,1861,2021-02-04,1000,2021-01-29,2021-02-02,baden-wurttemberg,Landtag von Baden-Württemberg,swr-stuttgarter-zeitung,SWR / Stuttgarter Zeitung,infratest-dimap,Infratest dimap,10.0,NaN,11.0,34.0,3.0
2188,1840,2021-01-13,1010,2021-01-05,2021-01-11,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,12.0,NaN,12.0,30.0,4.0
2204,1824,2020-12-17,1001,2020-12-14,2020-12-16,baden-wurttemberg,Landtag von Baden-Württemberg,swr,SWR,infratest-dimap,Infratest dimap,11.0,NaN,10.0,35.0,3.0
2229,1799,2020-11-19,1001,2020-11-10,2020-11-16,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,12.0,NaN,11.0,29.0,5.0
2263,1765,2020-10-15,1001,2020-10-08,2020-10-13,baden-wurttemberg,Landtag von Baden-Württemberg,swr-stuttgarter-zeitung,SWR / Stuttgarter Zeitung,infratest-dimap,Infratest dimap,11.0,NaN,11.0,34.0,4.0
2292,1736,2020-09-10,1000,2020-09-02,2020-09-07,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,12.0,NaN,12.0,28.0,5.0
2403,1624,2020-04-30,1003,2020-04-27,2020-04-28,baden-wurttemberg,Landtag von Baden-Württemberg,swr,SWR,infratest-dimap,Infratest dimap,12.0,NaN,11.0,34.0,3.0
2413,1616,2020-04-22,1523,2020-04-15,2020-04-20,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,11.0,NaN,13.0,29.0,4.0
2449,1579,2020-03-12,1001,2020-03-05,2020-03-10,baden-wurttemberg,Landtag von Baden-Württemberg,swr-stuttgarter-zeitung,SWR / Stuttgarter Zeitung,infratest-dimap,Infratest dimap,14.0,NaN,11.0,36.0,5.0
2572,1456,2019-10-30,1036,2019-10-23,2019-10-28,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,13.0,NaN,11.0,30.0,4.0
2611,1415,2019-09-19,1004,2019-09-16,2019-09-17,baden-wurttemberg,Landtag von Baden-Württemberg,swr-stuttgarter-zeitung,SWR / Stuttgarter Zeitung,infratest-dimap,Infratest dimap,12.0,NaN,8.0,38.0,3.0
2751,1275,2019-05-10,1040,2019-05-06,2019-05-08,baden-wurttemberg,Landtag von Baden-Württemberg,bild,BILD,insa,INSA,12.0,NaN,11.0,28.0,6.0
2805,1223,2019-03-28,1002,2019-03-20,2019-03-26,baden-wurttemberg,Landtag von Baden-Württemberg,swr-stuttgarter-zeitung,SWR / Stuttgarter Zeitung,infratest-dimap,Infratest dimap,11.0,NaN,12.0,32.0,4.0

In [6]:
data_not_na=data[~data["einheit_mastr_nummer"].isna()]
data_not_na

,goal100_id,einheit_mastr_nummer,behoerden_einheit_id,name_windpark,name_stromerzeugungseinheit,einheit_betriebsstatus,ags_gemeinde,bundesland,landkreis,gemeinde,...,dauer_genehmigung,dauer_realisierung,id_version_download_datenset_behoerde,id_version_download_datenset_mastr,x_25832,y_25832,x_4326,y_4326,ags_bundesland,ags_landkreis
0,36019,SEE966958743041,NaN,NaN,HS-Flensburg_P00012_W+PV_202kW,In Betrieb,1001000.0,Schleswig-Holstein,Flensburg,Flensburg,...,NaN,NaN,NaN,2.0,529350.868073,6.069506e+06,9.456250,54.771910,1.0,01001
4,79220,SEE970653437198,SH-03000924205-0002,Windpark Lübeck Nord,WEA2 Pöppendorf,In Betrieb,1003000.0,Schleswig-Holstein,Lübeck,Lübeck,...,203.0,539.0,59.0,2.0,619814.179633,5.977998e+06,10.825159,53.936484,1.0,01003
5,77800,SEE930060808431,SH-03000924233-0001,Bültwind Nr.60,Bültwind,In Betrieb,1003000.0,Schleswig-Holstein,Lübeck,Lübeck,...,NaN,NaN,59.0,2.0,620844.345391,5.977568e+06,10.840673,53.932386,1.0,01003
6,78441,SEE948056013141,SH-51001900011-0004,Bürgerwindpark Albersdorf,WEA 4 / V 203772,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,192.0,59.0,7.0,516927.977265,5.998977e+06,9.259109,54.138631,1.0,01051
7,79178,SEE969313089747,SH-51001900011-0001,Bürgerwindpark Albersdorf,WEA 1 / V 203769,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,193.0,59.0,7.0,516647.993158,5.999295e+06,9.254841,54.141498,1.0,01051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42663,41655,SEE905015577458,NaN,meridian Windpark Thonhausen,WEA 4,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,355.0,NaN,48.0,735203.382956,5.636053e+06,12.340000,50.828333,16.0,16077
42664,41828,SEE929841659676,NaN,meridian Windpark Thonhausen,WEA 7,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,240.0,NaN,48.0,735567.702820,5.635576e+06,12.344858,50.823906,16.0,16077
42665,29924,SEE924115847834,NaN,meridian Windpark Thonhausen,WEA 6,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,349.0,NaN,48.0,735559.598844,5.635976e+06,12.345000,50.827500,16.0,16077
42666,24143,SEE924538245743,SN-09000000004-0002,Mark Sahnau / Thonhausen,Mark Sahnau WEA2,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,296.0,34.0,2.0,735756.754790,5.636739e+06,12.348285,50.834268,16.0,16077
42667,24769,SEE998013206017,TH-FAWIND-GOAL100-SEE998013206017,Mark Sahnau / Thonhausen,Thonhausen WEA6,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,77.0,307.0,23.0,2.0,735407.153276,5.636633e+06,12.343261,50.833461,16.0,16077

In [7]:
genehmigungsdauer=data_not_na[data_not_na["dauer_genehmigung"]>0]
genehmigungsdauer

,goal100_id,einheit_mastr_nummer,behoerden_einheit_id,name_windpark,name_stromerzeugungseinheit,einheit_betriebsstatus,ags_gemeinde,bundesland,landkreis,gemeinde,...,dauer_genehmigung,dauer_realisierung,id_version_download_datenset_behoerde,id_version_download_datenset_mastr,x_25832,y_25832,x_4326,y_4326,ags_bundesland,ags_landkreis
4,79220,SEE970653437198,SH-03000924205-0002,Windpark Lübeck Nord,WEA2 Pöppendorf,In Betrieb,1003000.0,Schleswig-Holstein,Lübeck,Lübeck,...,203.0,539.0,59.0,2.0,619814.179633,5.977998e+06,10.825159,53.936484,1.0,01003
6,78441,SEE948056013141,SH-51001900011-0004,Bürgerwindpark Albersdorf,WEA 4 / V 203772,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,192.0,59.0,7.0,516927.977265,5.998977e+06,9.259109,54.138631,1.0,01051
7,79178,SEE969313089747,SH-51001900011-0001,Bürgerwindpark Albersdorf,WEA 1 / V 203769,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,193.0,59.0,7.0,516647.993158,5.999295e+06,9.254841,54.141498,1.0,01051
8,79324,SEE973804784493,SH-51001900011-0005,Bürgerwindpark Albersdorf,WEA 5 / V 203773,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,200.0,59.0,7.0,517034.002839,5.998625e+06,9.260712,54.135464,1.0,01051
9,78680,SEE954883336339,SH-51001900011-0003,Bürgerwindpark Albersdorf,WEA 3 / V 203771,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,192.0,59.0,7.0,516705.970862,5.998672e+06,9.255694,54.135897,1.0,01051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42651,24577,SEE947239808451,TH-FAWIND-GOAL100-SEE947239808451,Kraasa,Kraasa 9,In Betrieb,16077044.0,Thüringen,Altenburger Land,Starkenberg,...,311.0,412.0,23.0,48.0,729612.900483,5.653407e+06,12.271667,50.986389,16.0,16077
42653,24645,SEE965077486013,TH-FAWIND-GOAL100-SEE965077486013,Kraasa,Kraasa 8,In Betrieb,16077044.0,Thüringen,Altenburger Land,Starkenberg,...,311.0,378.0,23.0,48.0,729668.302083,5.653039e+06,12.272222,50.983056,16.0,16077
42654,24507,SEE926469864444,TH-FAWIND-GOAL100-SEE926469864444,Windpark Kraasa,VE-01-206089,In Betrieb,16077044.0,Thüringen,Altenburger Land,Starkenberg,...,279.0,57.0,23.0,48.0,730314.272403,5.653665e+06,12.281806,50.988417,16.0,16077
42661,24597,SEE953472606747,TH-FAWIND-GOAL100-SEE953472606747,WEA 05,WEA 5,In Betrieb,16077044.0,Thüringen,Altenburger Land,Starkenberg,...,608.0,300.0,23.0,48.0,729947.012664,5.653305e+06,12.276355,50.985338,16.0,16077
42667,24769,SEE998013206017,TH-FAWIND-GOAL100-SEE998013206017,Mark Sahnau / Thonhausen,Thonhausen WEA6,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,77.0,307.0,23.0,2.0,735407.153276,5.636633e+06,12.343261,50.833461,16.0,16077

In [23]:
median_dauer_bl=genehmigungsdauer.groupby("bundesland")["dauer_genehmigung"].median()
median_dauer_bl

bundesland
Baden-Württemberg         456.0
Brandenburg               579.0
Hessen                    481.0
Mecklenburg-Vorpommern    594.0
Nordrhein-Westfalen       434.0
Rheinland-Pfalz           427.0
Saarland                  366.0
Sachsen                   537.0
Schleswig-Holstein        301.0
Thüringen                 375.0
Name: dauer_genehmigung, dtype: float64

In [24]:
max_dauer_bl=genehmigungsdauer.groupby("bundesland")["dauer_genehmigung"].quantile(.90)
max_dauer_bl

bundesland
Baden-Württemberg         1400.0
Brandenburg               1401.0
Hessen                    1316.5
Mecklenburg-Vorpommern     594.0
Nordrhein-Westfalen       1060.0
Rheinland-Pfalz           1251.4
Saarland                  1115.0
Sachsen                    866.0
Schleswig-Holstein         914.0
Thüringen                 1056.0
Name: dauer_genehmigung, dtype: float64

In [25]:
min_dauer_bl=genehmigungsdauer.groupby("bundesland")["dauer_genehmigung"].quantile(.10)
min_dauer_bl

bundesland
Baden-Württemberg         184.0
Brandenburg               254.0
Hessen                    220.0
Mecklenburg-Vorpommern    594.0
Nordrhein-Westfalen       204.2
Rheinland-Pfalz           138.0
Saarland                  144.0
Sachsen                   447.0
Schleswig-Holstein        163.0
Thüringen                 167.4
Name: dauer_genehmigung, dtype: float64

In [30]:
min_max_bl=pd.merge(min_dauer_bl,max_dauer_bl,on="bundesland",suffixes=("_min","_max"))
min_max_med_bl=pd.merge(median_dauer_bl,min_max_bl,on="bundesland")
min_max_med_bl=min_max_med_bl.reset_index(drop=False)
min_max_med_bl.to_csv("min_max_median_bl.csv",index=False)

In [8]:
genehmigungsdauer_count=genehmigungsdauer[["ags_landkreis","dauer_genehmigung"]].groupby("ags_landkreis").count().reset_index()
genehmigungsdauer_count

    ags_landkreis  dauer_genehmigung
0           01003                  1
1           01051                648
2           01053                 36
3           01054                709
4           01055                173
..            ...                ...
154         16073                 13
155         16074                 25
156         16075                  2
157         16076                 16
158         16077                  5

[159 rows x 2 columns]

In [9]:
kreise_mindest_list=genehmigungsdauer_count[genehmigungsdauer_count["dauer_genehmigung"]>=5]["ags_landkreis"].tolist()
kreise_mindest_list

['01051',
 '01053',
 '01054',
 '01055',
 '01056',
 '01057',
 '01058',
 '01059',
 '01060',
 '01061',
 '01062',
 '05154',
 '05162',
 '05166',
 '05170',
 '05358',
 '05362',
 '05366',
 '05370',
 '05374',
 '05382',
 '05554',
 '05558',
 '05562',
 '05566',
 '05570',
 '05762',
 '05766',
 '05770',
 '05774',
 '05914',
 '05958',
 '05962',
 '05966',
 '05970',
 '05974',
 '06431',
 '06432',
 '06434',
 '06435',
 '06437',
 '06439',
 '06440',
 '06531',
 '06532',
 '06533',
 '06534',
 '06535',
 '06631',
 '06632',
 '06633',
 '06634',
 '06635',
 '06636',
 '07132',
 '07133',
 '07134',
 '07135',
 '07137',
 '07140',
 '07141',
 '07143',
 '07231',
 '07232',
 '07233',
 '07235',
 '07319',
 '07331',
 '07332',
 '07334',
 '07335',
 '07336',
 '07337',
 '07338',
 '07339',
 '07340',
 '08117',
 '08119',
 '08126',
 '08127',
 '08128',
 '08136',
 '08225',
 '08237',
 '08317',
 '08325',
 '08415',
 '08425',
 '08436',
 '08437',
 '10041',
 '10042',
 '10043',
 '10044',
 '10045',
 '10046',
 '12052',
 '12053',
 '12060',
 '12061',
 '12062',
 '12063',
 '12064',
 '12065',
 '12066',
 '12067',
 '12068',
 '12069',
 '12070',
 '12071',
 '12072',
 '12073',
 '14521',
 '14522',
 '14524',
 '14729',
 '16051',
 '16061',
 '16062',
 '16063',
 '16064',
 '16065',
 '16067',
 '16068',
 '16070',
 '16071',
 '16073',
 '16074',
 '16076',
 '16077']

In [10]:
mindest_zahl_genehmigungen=genehmigungsdauer[genehmigungsdauer["ags_landkreis"].isin(kreise_mindest_list)]
median_time_to_genehmigung=mindest_zahl_genehmigungen[["ags_landkreis","landkreis","dauer_genehmigung"]].groupby(["landkreis","ags_landkreis"]).median().reset_index()
median_time_to_genehmigung

                     landkreis ags_landkreis  dauer_genehmigung
0              Alb-Donau-Kreis         08425              251.0
1             Altenburger Land         16077              311.0
2    Altenkirchen (Westerwald)         07132             1733.0
3                  Alzey-Worms         07331              244.5
4                 Bad Dürkheim         07332              329.0
..                         ...           ...                ...
125                      Wesel         05170              598.0
126            Westerwaldkreis         07143              372.0
127              Wetteraukreis         06440              644.0
128                      Worms         07319              210.0
129                    Zwickau         14524              537.0

[130 rows x 3 columns]

In [11]:
median_time_to_genehmigung=median_time_to_genehmigung.sort_values(by="dauer_genehmigung")
median_time_to_genehmigung.head(50)

                   landkreis ags_landkreis  dauer_genehmigung
18                 Eichsfeld         16061              102.0
72               Ostalbkreis         08136              184.0
25              Freudenstadt         08237              186.0
111      Südliche Weinstraße         07337              186.0
128                    Worms         07319              210.0
94      Saale-Holzland-Kreis         16074              211.0
61     Neckar-Odenwald-Kreis         08225              216.0
23                Euskirchen         05366              219.0
89          Rhein-Lahn-Kreis         07141              231.0
3                Alzey-Worms         07331              244.5
17                     Düren         05358              248.0
0            Alb-Donau-Kreis         08425              251.0
62               Neunkirchen         10043              254.0
53              Mainz-Bingen         07339              255.0
16              Dithmarschen         01051              257.0
10                    Borken         05554              259.0
100          Schwäbisch Hall         08127              261.0
19   Eifelkreis Bitburg-Prüm         07232              269.0
123            Weimarer Land         16071              269.0
71              Ortenaukreis         08317              273.0
98       Schleswig-Flensburg         01059              273.0
63             Nordfriesland         01054              284.0
92     Rheingau-Taunus-Kreis         06439              290.0
107                Steinburg         01061              299.0
110                 Sömmerda         16068              304.0
5              Bad Kreuznach         07133              309.0
1           Altenburger Land         16077              311.0
15         Darmstadt-Dieburg         06432              311.0
66                 Oberhavel         12065              316.0
29                     Gotha         16067              316.0
56             Merzig-Wadern         10042              328.5
81            Recklinghausen         05562              328.5
4               Bad Dürkheim         07332              329.0
75                 Paderborn         05774              332.0
27               Germersheim         07334              336.0
43                    Kassel         06633              345.0
108                Steinfurt         05566              355.0
96                 Saarlouis         10044              360.0
86          Rhein-Erft-Kreis         05362              361.0
116    Unstrut-Hainich-Kreis         16064              364.0
42            Kaiserslautern         07335              365.5
104                    Soest         05974              370.0
126          Westerwaldkreis         07143              372.0
7                 Bergstraße         06431              377.0
124      Werra-Meißner-Kreis         06636              377.0
49          Limburg-Weilburg         06533              387.0
34                 Heinsberg         05370              394.0
12                  Coesfeld         05558              397.0
44                     Kleve         05154              401.0
119              Vulkaneifel         07233              403.0

In [32]:
median_time_to_genehmigung.head(10).to_csv("shortest_time.csv",index=False)

In [12]:
median_time_to_genehmigung.tail(50)

                     landkreis ags_landkreis  dauer_genehmigung
33                   Havelland         12063              542.0
60            Märkischer Kreis         05962              543.0
47             Lahn-Dill-Kreis         06532              544.0
79                    Prignitz         12070              555.5
28                      Gießen         06531              556.0
67       Oberspreewald-Lausitz         12066              560.0
32                       Hagen         05914              562.0
91            Rhein-Sieg-Kreis         05382              570.5
65        Oberbergischer Kreis         05374              576.0
11                 Cochem-Zell         07135              592.0
30                       Greiz         16076              594.0
125                      Wesel         05170              598.0
70                        Olpe         05966              599.0
9                   Birkenfeld         07134              614.0
59           Märkisch-Oderland         12064              615.0
52           Main-Tauber-Kreis         08128              620.5
120        Waldeck-Frankenberg         06635              621.0
102        Siegen-Wittgenstein         05970              624.0
114             Trier-Saarburg         07235              627.0
101                   Segeberg         01060              638.0
127              Wetteraukreis         06440              644.0
13                     Cottbus         12052              653.0
83             Rems-Murr-Kreis         08119              667.0
37          Hochsauerlandkreis         05958              680.0
26                       Fulda         06631              681.0
78          Potsdam-Mittelmark         12069              694.0
113             Teltow-Fläming         12072              707.0
85                  Reutlingen         08415              711.0
14             Dahme-Spreewald         12061              730.0
57             Minden-Lübbecke         05770              755.5
31                   Göppingen         08117              762.0
35          Hersfeld-Rotenburg         06632              789.0
69                  Oder-Spree         12067              827.0
87        Rhein-Hunsrück-Kreis         07140              830.0
105                Spree-Neiße         12071              841.0
50                       Lippe         05766              858.0
93                    Rottweil         08325              880.0
76                   Pinneberg         01056              890.0
68               Odenwaldkreis         06437              921.0
55               Mayen-Koblenz         07137              949.0
24            Frankfurt (Oder)         12053              958.0
74          Ostprignitz-Ruppin         12068              972.0
117                    Viersen         05166             1043.0
97             Saarpfalz-Kreis         10045             1115.0
22             Erzgebirgskreis         14521             1177.0
95         Saalfeld-Rudolstadt         16073             1183.0
103                Sigmaringen         08437             1400.0
88           Rhein-Kreis Neuss         05162             1572.5
2    Altenkirchen (Westerwald)         07132             1733.0
21                      Erfurt         16051             2996.0

In [13]:
median_time_to_genehmigung.to_csv("median_time_to_genehmigung.csv",index=False)

In [21]:
dauer_realisierung=data[data["dauer_realisierung"]>0]
dauer_realisierung

,goal100_id,einheit_mastr_nummer,behoerden_einheit_id,name_windpark,name_stromerzeugungseinheit,einheit_betriebsstatus,ags_gemeinde,bundesland,landkreis,gemeinde,...,dauer_genehmigung,dauer_realisierung,id_version_download_datenset_behoerde,id_version_download_datenset_mastr,x_25832,y_25832,x_4326,y_4326,ags_bundesland,ags_landkreis
4,79220,SEE970653437198,SH-03000924205-0002,Windpark Lübeck Nord,WEA2 Pöppendorf,In Betrieb,1003000.0,Schleswig-Holstein,Lübeck,Lübeck,...,203.0,539.0,59.0,2.0,619814.179633,5.977998e+06,10.825159,53.936484,1.0,01003
6,78441,SEE948056013141,SH-51001900011-0004,Bürgerwindpark Albersdorf,WEA 4 / V 203772,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,192.0,59.0,7.0,516927.977265,5.998977e+06,9.259109,54.138631,1.0,01051
7,79178,SEE969313089747,SH-51001900011-0001,Bürgerwindpark Albersdorf,WEA 1 / V 203769,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,193.0,59.0,7.0,516647.993158,5.999295e+06,9.254841,54.141498,1.0,01051
8,79324,SEE973804784493,SH-51001900011-0005,Bürgerwindpark Albersdorf,WEA 5 / V 203773,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,200.0,59.0,7.0,517034.002839,5.998625e+06,9.260712,54.135464,1.0,01051
9,78680,SEE954883336339,SH-51001900011-0003,Bürgerwindpark Albersdorf,WEA 3 / V 203771,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,192.0,59.0,7.0,516705.970862,5.998672e+06,9.255694,54.135897,1.0,01051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42663,41655,SEE905015577458,NaN,meridian Windpark Thonhausen,WEA 4,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,355.0,NaN,48.0,735203.382956,5.636053e+06,12.340000,50.828333,16.0,16077
42664,41828,SEE929841659676,NaN,meridian Windpark Thonhausen,WEA 7,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,240.0,NaN,48.0,735567.702820,5.635576e+06,12.344858,50.823906,16.0,16077
42665,29924,SEE924115847834,NaN,meridian Windpark Thonhausen,WEA 6,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,349.0,NaN,48.0,735559.598844,5.635976e+06,12.345000,50.827500,16.0,16077
42666,24143,SEE924538245743,SN-09000000004-0002,Mark Sahnau / Thonhausen,Mark Sahnau WEA2,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,296.0,34.0,2.0,735756.754790,5.636739e+06,12.348285,50.834268,16.0,16077
42667,24769,SEE998013206017,TH-FAWIND-GOAL100-SEE998013206017,Mark Sahnau / Thonhausen,Thonhausen WEA6,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,77.0,307.0,23.0,2.0,735407.153276,5.636633e+06,12.343261,50.833461,16.0,16077

In [22]:
realisierungsdauer_count=dauer_realisierung[["ags_landkreis","dauer_realisierung"]].groupby("ags_landkreis").count().reset_index()
realisierungsdauer_count

    ags_landkreis  dauer_realisierung
0           01003                   1
1           01051                 830
2           01053                  60
3           01054                 793
4           01055                 261
..            ...                 ...
292         16073                   4
293         16074                  62
294         16075                  22
295         16076                  14
296         16077                  49

[297 rows x 2 columns]

In [23]:
kreise_mindest_real=realisierungsdauer_count[realisierungsdauer_count["dauer_realisierung"]>=5]["ags_landkreis"]
kreise_mindest_real_list=kreise_mindest_real.tolist()

In [24]:
dauer_realisierung_mindest=dauer_realisierung[dauer_realisierung["ags_landkreis"].isin(kreise_mindest_real_list)]
dauer_realisierung_mindest

,goal100_id,einheit_mastr_nummer,behoerden_einheit_id,name_windpark,name_stromerzeugungseinheit,einheit_betriebsstatus,ags_gemeinde,bundesland,landkreis,gemeinde,...,dauer_genehmigung,dauer_realisierung,id_version_download_datenset_behoerde,id_version_download_datenset_mastr,x_25832,y_25832,x_4326,y_4326,ags_bundesland,ags_landkreis
6,78441,SEE948056013141,SH-51001900011-0004,Bürgerwindpark Albersdorf,WEA 4 / V 203772,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,192.0,59.0,7.0,516927.977265,5.998977e+06,9.259109,54.138631,1.0,01051
7,79178,SEE969313089747,SH-51001900011-0001,Bürgerwindpark Albersdorf,WEA 1 / V 203769,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,193.0,59.0,7.0,516647.993158,5.999295e+06,9.254841,54.141498,1.0,01051
8,79324,SEE973804784493,SH-51001900011-0005,Bürgerwindpark Albersdorf,WEA 5 / V 203773,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,200.0,59.0,7.0,517034.002839,5.998625e+06,9.260712,54.135464,1.0,01051
9,78680,SEE954883336339,SH-51001900011-0003,Bürgerwindpark Albersdorf,WEA 3 / V 203771,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,192.0,59.0,7.0,516705.970862,5.998672e+06,9.255694,54.135897,1.0,01051
10,79070,SEE966072006992,SH-51001900011-0002,Bürgerwindpark Albersdorf,WEA 2 / V 203770,In Betrieb,1051001.0,Schleswig-Holstein,Dithmarschen,Albersdorf,...,258.0,199.0,59.0,7.0,516598.971357,5.998975e+06,9.254073,54.138624,1.0,01051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42663,41655,SEE905015577458,NaN,meridian Windpark Thonhausen,WEA 4,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,355.0,NaN,48.0,735203.382956,5.636053e+06,12.340000,50.828333,16.0,16077
42664,41828,SEE929841659676,NaN,meridian Windpark Thonhausen,WEA 7,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,240.0,NaN,48.0,735567.702820,5.635576e+06,12.344858,50.823906,16.0,16077
42665,29924,SEE924115847834,NaN,meridian Windpark Thonhausen,WEA 6,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,349.0,NaN,48.0,735559.598844,5.635976e+06,12.345000,50.827500,16.0,16077
42666,24143,SEE924538245743,SN-09000000004-0002,Mark Sahnau / Thonhausen,Mark Sahnau WEA2,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,NaN,296.0,34.0,2.0,735756.754790,5.636739e+06,12.348285,50.834268,16.0,16077
42667,24769,SEE998013206017,TH-FAWIND-GOAL100-SEE998013206017,Mark Sahnau / Thonhausen,Thonhausen WEA6,In Betrieb,16077047.0,Thüringen,Altenburger Land,Thonhausen,...,77.0,307.0,23.0,2.0,735407.153276,5.636633e+06,12.343261,50.833461,16.0,16077

In [26]:
dauer_realisierung_mindest[dauer_realisierung_mindest.landkreis.str.contains("Erfurt")].sort_values(by="dauer_realisierung")

,goal100_id,einheit_mastr_nummer,behoerden_einheit_id,name_windpark,name_stromerzeugungseinheit,einheit_betriebsstatus,ags_gemeinde,bundesland,landkreis,gemeinde,...,dauer_genehmigung,dauer_realisierung,id_version_download_datenset_behoerde,id_version_download_datenset_mastr,x_25832,y_25832,x_4326,y_4326,ags_bundesland,ags_landkreis
41607,24600,SEE954018466771,TH-FAWIND-GOAL100-SEE954018466771,Kerspleben 2,531507,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,176.0,227.0,23.0,2.0,646042.100771,5.654831e+06,11.082553,51.026456,16.0,16051
41608,38145,SEE959393004785,NaN,Kerspleben 1,53474,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,274.0,NaN,2.0,646311.133580,5.654547e+06,11.086272,51.023834,16.0,16051
41575,24529,SEE932471928456,TH-FAWIND-GOAL100-SEE932471928456,CEE Windpark Töttleben,CEE Windpark Töttleben WEA 1,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,407.0,445.0,23.0,48.0,647644.980222,5.655664e+06,11.105733,51.033535,16.0,16051
41578,34940,SEE902132723218,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 1 - Nr. 78418,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,857.0,NaN,2.0,639289.628072,5.641111e+06,10.981073,50.904830,16.0,16051
41580,34945,SEE915327261174,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 3 - Nr. 78420,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,875.0,NaN,2.0,639175.609546,5.641661e+06,10.979662,50.909798,16.0,16051
41579,34943,SEE922411163153,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 2 - Nr. 78419,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,896.0,NaN,2.0,639215.811345,5.641374e+06,10.980124,50.907209,16.0,16051
41587,34950,SEE991418465737,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 7 - Nr. 78424,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,905.0,NaN,2.0,640007.258760,5.641903e+06,10.991577,50.911777,16.0,16051
41583,34949,SEE994547937892,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 6 - Nr. 78423,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,906.0,NaN,2.0,640054.008793,5.641620e+06,10.992133,50.909223,16.0,16051
41596,34952,SEE913659595509,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 9 - Nr. 78426,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,918.0,NaN,2.0,640447.034518,5.642031e+06,10.997878,50.912822,16.0,16051
41593,34954,SEE934461145102,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 11 - Nr. 78428,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,919.0,NaN,2.0,641151.260188,5.641966e+06,11.007864,50.912066,16.0,16051
41595,34953,SEE990494922448,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 10 - Nr. 78427,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,920.0,NaN,2.0,641231.745209,5.641604e+06,11.008868,50.908792,16.0,16051
41594,34951,SEE902941736171,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 8 - Nr. 78425,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,920.0,NaN,2.0,640740.190385,5.641561e+06,11.001864,50.908522,16.0,16051
41582,34948,SEE973527707113,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 5 - Nr. 78422,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,955.0,NaN,2.0,639652.878190,5.641359e+06,10.986331,50.906972,16.0,16051
41581,34946,SEE970686952231,NaN,Windpark Möbisburg GmbH ＆ Co. KG,WEA 4 - Nr. 78421,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,NaN,961.0,NaN,2.0,639553.934417,5.641669e+06,10.985043,50.909779,16.0,16051
41584,24523,SEE930372015268,TH-FAWIND-GOAL100-SEE930372015268,WP Frienstedt,24 WEA Frienstedt I,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,1332.0,23.0,2.0,634714.512382,5.645271e+06,10.917579,50.943303,16.0,16051
41586,24610,SEE956823799938,TH-FAWIND-GOAL100-SEE956823799938,WP Frienstedt,24 WEA Frienstedt III,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,1335.0,23.0,2.0,635017.269487,5.645109e+06,10.921826,50.941778,16.0,16051
41585,24643,SEE964410737935,TH-FAWIND-GOAL100-SEE964410737935,WP Frienstedt,24 WEA Frienstedt II,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,1335.0,23.0,2.0,634649.298454,5.645570e+06,10.916762,50.946010,16.0,16051
41589,24498,SEE924182704337,TH-FAWIND-GOAL100-SEE924182704337,WP Frienstedt,24 WEA Frienstedt IV,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,1336.0,23.0,2.0,635099.703599,5.645566e+06,10.923168,50.945862,16.0,16051
41590,24463,SEE917172170892,TH-FAWIND-GOAL100-SEE917172170892,WP Frienstedt,24 WEA Frienstedt V,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,1337.0,23.0,2.0,635431.238759,5.645287e+06,10.927781,50.943280,16.0,16051
41591,24441,SEE909386131769,TH-FAWIND-GOAL100-SEE909386131769,WP Frienstedt,24 WEA Frienstedt VI,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,1339.0,23.0,2.0,635460.637077,5.645967e+06,10.928452,50.949381,16.0,16051
41592,24698,SEE977382434764,TH-FAWIND-GOAL100-SEE977382434764,WP Frienstedt,24 WEA Frienstedt VII,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,1350.0,23.0,2.0,635000.762818,5.645883e+06,10.921878,50.948736,16.0,16051
41577,24606,SEE955990368176,TH-FAWIND-GOAL100-SEE955990368176,WP Frienstedt,24 WEA Frienstedt VIII,In Betrieb,16051000.0,Thüringen,Erfurt,Erfurt,...,2996.0,2100.0,23.0,2.0,635522.895658,5.645618e+06,10.929208,50.946232,16.0,16051

In [90]:
median_time_to_realisierung=dauer_realisierung_mindest[["ags_landkreis","landkreis","dauer_realisierung"]].groupby(["landkreis","ags_landkreis"]).median().reset_index()

median_time_to_genehmigung

                     landkreis ags_landkreis  dauer_genehmigung
0              Alb-Donau-Kreis         08425              251.0
1             Altenburger Land         16077              311.0
2    Altenkirchen (Westerwald)         07132             1733.0
3                  Alzey-Worms         07331              244.5
4                 Bad Dürkheim         07332              329.0
..                         ...           ...                ...
125                      Wesel         05170              598.0
126            Westerwaldkreis         07143              372.0
127              Wetteraukreis         06440              644.0
128                      Worms         07319              210.0
129                    Zwickau         14524              537.0

[130 rows x 3 columns]

In [91]:
median_time_to_realisierung.sort_values(by="dauer_realisierung").head(50)

                             landkreis ags_landkreis  dauer_realisierung
107                            Krefeld         05114                62.0
183                   Rhein-Lahn-Kreis         07141                64.0
251                              Worms         07319                69.5
7                            Ammerland         03451                76.0
46                            Dortmund         05913               132.0
61                Freiburg im Breisgau         08311               159.0
216   Sächsische Schweiz-Osterzgebirge         14628               163.0
72                 Grafschaft Bentheim         03456               211.0
121                           Lüneburg         03355               211.0
3                     Altenburger Land         16077               216.0
156                          Oberhavel         12065               216.5
5                          Alzey-Worms         07331               217.0
110                    Kyffhäuserkreis         16065               219.0
229                             Vechta         03460               220.0
143                  Neumarkt i.d.OPf.         09373               223.0
60                    Frankfurt (Oder)         12053               227.0
84                           Havelland         12063               231.0
18                             Bautzen         14625               232.0
155               Oberbergischer Kreis         05374               237.0
0                            Ahrweiler         07131               240.0
191               Saale-Holzland-Kreis         16074               244.0
66                                Gera         16052               250.0
27                              Bremen         04011               251.0
247                      Wilhelmshaven         03405               253.5
88                           Heilbronn         08125               253.5
4               Altmarkkreis Salzwedel         15081               255.0
105                          Kitzingen         09675               258.0
139                    Mönchengladbach         05116               259.0
96                     Hochtaunuskreis         06434               262.0
146   Neustadt a.d.Aisch-Bad Windsheim         09575               264.0
134                         Miltenberg         09676               265.5
145  Neustadt a.d. Aisch-Bad Windsheim         09575               265.5
236                        Vulkaneifel         07233               266.0
148                      Nordfriesland         01054               266.0
249                           Wittmund         03462               267.0
248                         Wittenberg         15091               267.0
113                               Leer         03457               270.5
234              Vorpommern-Greifswald         13075               271.0
115                            Leipzig         14729               271.0
45                    Donnersbergkreis         07333               271.0
185              Rheingau-Taunus-Kreis         06439               271.5
202                        Schweinfurt         09678               278.0
217                           Sömmerda         16068               280.0
63                           Friesland         03455               280.0
93                 Herzogtum Lauenburg         01053               282.0
12                              Aurich         03452               282.0
144                        Neunkirchen         10043               283.0
42                            Diepholz         03251               284.5
195                    Saarpfalz-Kreis         10045               286.0
10                             Ansbach         09571               287.0

In [92]:
median_time_to_realisierung.sort_values(by="dauer_realisierung").tail(50)

                       landkreis ags_landkreis  dauer_realisierung
171        Pfaffenhofen a.d. Ilm         09186               483.0
83                          Harz         15085               485.0
213                      Stendal         15090               486.5
36                      Coesfeld         05558               489.0
178              Region Hannover         03241               489.5
117                        Lippe         05766               490.0
219                 Südwestpfalz         07340               493.0
238                    Warendorf         05570               494.5
153              Nürnberger Land         09574               497.0
52                         Emden         03402               503.0
116             Limburg-Weilburg         06533               509.0
231                      Viersen         05166               517.0
233                Vogtlandkreis         14523               521.0
64                         Fulda         06631               555.0
225                       Uelzen         03360               557.0
240                Weimarer Land         16071               563.0
91                       Herford         05758               568.5
29               Burgenlandkreis         15084               571.0
34                        Coburg         09473               573.0
149                   Nordhausen         16062               574.5
85                      Haßberge         09674               586.0
1              Aichach-Friedberg         09771               587.5
184            Rhein-Pfalz-Kreis         07338               590.0
43          Dillingen a.d. Donau         09773               592.0
200           Schwalm-Eder-Kreis         06634               607.0
11                      Augsburg         09772               608.0
194                    Saarlouis         10044               624.0
92            Hersfeld-Rotenburg         06632               636.5
87                    Heidenheim         08135               648.0
253   Wunsiedel i.Fichtelgebirge         09479               651.0
208                  Spree-Neiße         12071               658.0
221                Tirschenreuth         09377               661.0
201                   Schwandorf         09376               664.0
252  Wunsiedel i. Fichtelgebirge         09479               668.0
9                        Ansbach         09561               673.0
97                           Hof         09475               673.0
70                        Goslar         03153               680.0
108                     Kulmbach         09477               681.0
41                 Dessau-Roßlau         15001               702.0
37                       Cottbus         12052               782.0
120            Lüchow-Dannenberg         03354               798.5
78                         Hagen         05914               826.0
16                       Bamberg         09471               856.0
206                  Sigmaringen         08437               889.5
177                   Regensburg         09375               894.0
186                Rhön-Grabfeld         09673               902.5
56                        Erfurt         16051               920.0
138             Märkischer Kreis         05962               950.0
122                    Magdeburg         15003              1086.0
101                    Ilm-Kreis         16070              1378.0

In [100]:
genehmigung_realisierung_merged=pd.merge(median_time_to_genehmigung,median_time_to_realisierung,on=["ags_landkreis","landkreis"])
genehmigung_realisierung_merged

            landkreis ags_landkreis  dauer_genehmigung  dauer_realisierung
0     Alb-Donau-Kreis         08425              251.0               442.0
1    Altenburger Land         16077              311.0               216.0
2         Alzey-Worms         07331              244.5               217.0
3        Bad Dürkheim         07332              329.0               333.0
4       Bad Kreuznach         07133              309.0               472.0
..                ...           ...                ...                 ...
117             Wesel         05170              598.0               317.0
118   Westerwaldkreis         07143              372.0               350.0
119     Wetteraukreis         06440              644.0               387.0
120             Worms         07319              210.0                69.5
121           Zwickau         14524              537.0               472.0

[122 rows x 4 columns]

In [108]:
genehmigung_realisierung_merged_rank_1=genehmigung_realisierung_merged.sort_values(by="dauer_genehmigung").reset_index(drop=True).reset_index()
genehmigung_realisierung_merged_rank_1=genehmigung_realisierung_merged_rank_1.rename(columns={"index":"rank_genehmigung"})

In [109]:
genehmigung_realisierung_merged_rank_2=genehmigung_realisierung_merged_rank_1.sort_values(by="dauer_realisierung").reset_index(drop=True).reset_index()
genehmigung_realisierung_merged_rank_2=genehmigung_realisierung_merged_rank_2.rename(columns={"index":"rank_realisierung"})
genehmigung_realisierung_merged_rank_2

,rank_realisierung,rank_genehmigung,landkreis,ags_landkreis,dauer_genehmigung,dauer_realisierung
0,0,8,Rhein-Lahn-Kreis,07141,231.0,64.0
1,1,4,Worms,07319,210.0,69.5
2,2,27,Altenburger Land,16077,311.0,216.0
3,3,29,Oberhavel,12065,316.0,216.5
4,4,9,Alzey-Worms,07331,244.5,217.0
...,...,...,...,...,...,...
117,117,84,Hagen,05914,562.0,826.0
118,118,119,Sigmaringen,08437,1400.0,889.5
119,119,121,Erfurt,16051,2996.0,920.0
120,120,79,Märkischer Kreis,05962,543.0,950.0
121,121,51,Ilm-Kreis,16070,409.0,1378.0

In [110]:
genehmigung_realisierung_merged_rank_2["mean_rank"]=genehmigung_realisierung_merged_rank_2[["rank_genehmigung","rank_realisierung"]].mean(axis=1)
genehmigung_realisierung_merged_rank_2

,rank_realisierung,rank_genehmigung,landkreis,ags_landkreis,dauer_genehmigung,dauer_realisierung,mean_rank
0,0,8,Rhein-Lahn-Kreis,07141,231.0,64.0,4.0
1,1,4,Worms,07319,210.0,69.5,2.5
2,2,27,Altenburger Land,16077,311.0,216.0,14.5
3,3,29,Oberhavel,12065,316.0,216.5,16.0
4,4,9,Alzey-Worms,07331,244.5,217.0,6.5
...,...,...,...,...,...,...,...
117,117,84,Hagen,05914,562.0,826.0,100.5
118,118,119,Sigmaringen,08437,1400.0,889.5,118.5
119,119,121,Erfurt,16051,2996.0,920.0,120.0
120,120,79,Märkischer Kreis,05962,543.0,950.0,99.5
121,121,51,Ilm-Kreis,16070,409.0,1378.0,86.0

In [112]:
genehmigung_realisierung_merged_rank_2.sort_values(by="mean_rank").head(20)

,rank_realisierung,rank_genehmigung,landkreis,ags_landkreis,dauer_genehmigung,dauer_realisierung,mean_rank
1,1,4,Worms,07319,210.0,69.5,2.5
0,0,8,Rhein-Lahn-Kreis,07141,231.0,64.0,4.0
4,4,9,Alzey-Worms,07331,244.5,217.0,6.5
9,9,5,Saale-Holzland-Kreis,16074,211.0,244.0,7.0
20,20,1,Ostalbkreis,08136,184.0,297.0,10.5
17,17,12,Neunkirchen,10043,254.0,283.0,14.5
22,22,7,Euskirchen,05366,219.0,307.0,14.5
2,2,27,Altenburger Land,16077,311.0,216.0,14.5
3,3,29,Oberhavel,12065,316.0,216.5,16.0
12,12,21,Nordfriesland,01054,284.0,266.0,16.5
14,14,22,Rheingau-Taunus-Kreis,06439,290.0,271.5,18.0
35,35,2,Südliche Weinstraße,07337,186.0,325.0,18.5
15,15,24,Sömmerda,16068,304.0,280.0,19.5
34,34,6,Neckar-Odenwald-Kreis,08225,216.0,325.0,20.0
5,5,50,Kyffhäuserkreis,16065,406.0,219.0,27.5
46,46,13,Mainz-Bingen,07339,255.0,347.5,29.5
19,19,40,Kaiserslautern,07335,365.5,290.0,29.5
11,11,49,Vulkaneifel,07233,403.0,266.0,30.0
26,26,34,Germersheim,07334,336.0,312.0,30.0
47,47,16,Schwäbisch Hall,08127,261.0,349.0,31.5

In [113]:
genehmigung_realisierung_merged_rank_2.sort_values(by="mean_rank").tail(20)

,rank_realisierung,rank_genehmigung,landkreis,ags_landkreis,dauer_genehmigung,dauer_realisierung,mean_rank
92,92,87,Greiz,16076,594.0,453.0,89.5
79,79,101,Potsdam-Mittelmark,12069,694.0,419.0,90.0
78,78,102,Teltow-Fläming,12072,707.0,416.0,90.0
64,64,118,Erzgebirgskreis,14521,1177.0,379.0,91.0
63,63,120,Rhein-Kreis Neuss,05162,1572.5,377.5,91.5
88,88,95,Trier-Saarburg,07235,627.0,444.0,91.5
96,96,89,Olpe,05966,599.0,467.0,92.5
94,94,96,Segeberg,01060,638.0,464.0,95.0
120,120,79,Märkischer Kreis,05962,543.0,950.0,99.5
117,117,84,Hagen,05914,562.0,826.0,100.5
89,89,113,Mayen-Koblenz,07137,949.0,446.0,101.0
108,108,100,Fulda,06631,681.0,555.0,104.0
103,103,110,Lippe,05766,858.0,490.0,106.5
116,116,98,Cottbus,12052,653.0,782.0,107.0
99,99,115,Ostprignitz-Ruppin,12068,972.0,473.0,107.0
114,114,106,Hersfeld-Rotenburg,06632,789.0,636.5,110.0
107,107,116,Viersen,05166,1043.0,517.0,111.5
115,115,109,Spree-Neiße,12071,841.0,658.0,112.0
118,118,119,Sigmaringen,08437,1400.0,889.5,118.5
119,119,121,Erfurt,16051,2996.0,920.0,120.0

In [114]:
genehmigung_realisierung_merged_rank_2.to_csv("genehmigungen_realisierung.csv",index=False)

In [ ]:
# Viersen called NEW Mönchengladbach
# Erfurt called VSB
#