In [27]:
import pandas as pd
import glob

In [28]:
files=glob.glob('../data/*.csv')
files

['../data/all_pensionfund_red_positions_after_2.csv',
 '../data/all_pensionfund_red_positions_after.csv',
 '../data/all_pensionfund_red_positions_before.csv']

In [60]:
data=pd.read_csv("../data/all_pensionfund_red_positions_after.csv",encoding='latin-1', encoding_errors='replace')
data

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund
0,21),ABBVIE INC,52.79MLN,1000000,52.79,5.279000e+07,OTP
1,23),ABBVIE INC,233.94MLN,1000000,233.94,2.339400e+08,BCI
2,21),ABBVIE INC,610.6MLN,1000000,610.60,6.106000e+08,Calstrs
3,25),ABBVIE INC,228.44MLN,1000000,228.44,2.284400e+08,PSP
4,22),ABBVIE INC,2.57MLN,1000000,2.57,2.570000e+06,AP7
...,...,...,...,...,...,...,...
445,5),WOODSIDE ENERGY GROUP LTD,2.37BLN,1000000000,2.37,2.370000e+09,AusSuper
446,26),WORKSPACE GROUP PLC,2.47MLN,1000000,2.47,2.470000e+06,Zorg
447,10),WSP GLOBAL INC,2.30BLN,1000000000,2.30,2.300000e+09,CPP
448,1),WSP GLOBAL INC,3.60BLN,1000000000,3.60,3.600000e+09,CDPQ
449,9),YARA INTERNATIONAL ASA,893.37MLN,1000000,893.37,8.933700e+08,Gov Pens F domestic

In [61]:
summed_positions=data.groupby("Name").sum().reset_index()

summed_positions_bytotal=summed_positions.sort_values(by='Value_Final', ascending=False)
summed_positions_bytotal=summed_positions_bytotal[["Name","Value_Final"]]
summed_positions_bytotal

                                        Name   Value_Final
151                              NVIDIA CORP  1.014952e+11
135                           MICROSOFT CORP  7.969974e+10
10                                 APPLE INC  7.916417e+10
21                                  Alphabet  7.507120e+10
22                                    Amazon  4.937953e+10
..                                       ...           ...
99                     HOCHSCHILD MINING PLC  1.610000e+06
61        CUSTODIAN PROPERTY INCOME REIT PLC  1.560000e+06
202  SOCIAL HOUSING REIT PLC ORDINARY SHARES  1.440000e+06
144                        NEWRIVER REIT PLC  1.200000e+06
97                               HELICAL PLC  0.000000e+00

[251 rows x 2 columns]

In [62]:
frequency_positions=data.groupby("Name").count()
frequency_positions=frequency_positions.reset_index()
frequency_positions=frequency_positions[["Name","Fund"]]
frequency_positions.sort_values(by='Fund', ascending=False).head(50)
frequency_positions

                          Name  Fund
0                   ABBVIE INC     6
1                 ADECOAGRO SA     1
2       ADVANCED MICRO DEVICES     2
3                     AKER ASA     1
4                  AKER BP ASA     1
..                         ...   ...
246              WELLTOWER INC     1
247  WOODSIDE ENERGY GROUP LTD     1
248        WORKSPACE GROUP PLC     1
249             WSP GLOBAL INC     2
250     YARA INTERNATIONAL ASA     1

[251 rows x 2 columns]

In [63]:
frequency_positions=data.groupby("Name").count()
frequency_positions=frequency_positions.reset_index()
frequency_positions=frequency_positions[["Name","Fund"]]
frequency_positions.sort_values(by='Fund', ascending=False).head(50)

                                       Name  Fund
21                                 Alphabet    15
135                          MICROSOFT CORP    12
151                             NVIDIA CORP    12
40                             BROADCOM INC    11
22                                   Amazon    11
10                                APPLE INC    11
70                           ELI LILLY & CO    10
133                                    META     9
30                   BERKSHIRE HATHAWAY INC     8
241                          VISA INC-CLASS     8
113                     JPMORGAN CHASE & CO     8
130                          MASTERCARD INC     7
14                          ASTRAZENECA PLC     6
219                               TESLA INC     6
0                                ABBVIE INC     6
110                       JOHNSON & JOHNSON     6
134                   MICRON TECHNOLOGY INC     5
59                    COSTCO WHOLESALE CORP     4
119                       LAM RESEARCH CORP     4
244                             WALMART INC     4
103                       HSBC HOLDINGS PLC     4
25                     BANK OF AMERICA CORP     4
229                            UNILEVER PLC     4
54                        CISCO SYSTEMS INC     4
116                                KLA CORP     3
162                 PROCTER & GAMBLE CO/THE     3
79                         EXXON MOBIL CORP     3
224               TORONTO-DOMINION BANK/THE     3
178                    ROYAL BANK OF CANADA     3
85                         GENERAL ELECTRIC     3
182                          SALESFORCE INC     3
122                               LINDE PLC     3
31                            BHP GROUP LTD     2
48       CANADIAN IMPERIAL BANK OF COMMERCE     2
100                          HOME DEPOT INC     2
63   DIGITAL REALTY TRUST INC COMMON SHARES     2
9                        ANALOG DEVICES INC     2
156                    PARKER-HANNIFIN CORP     2
11                    APPLIED MATERIALS INC     2
77                        EVERSOURCE ENERGY     2
194                               SEGRO PLC     2
13                          ASML HOLDING NV     2
15                                  ASX LTD     2
214              TAIWAN SEMICONDUCTOR MAâ¦     2
143                             NETFLIX INC     2
81      FISHER & PAYKEL HEALTHCARE CORP LTD     2
149                         NOVARTIS AG-REG     2
120               LAND SECURITIES GROUP PLC     2
200                            SK HYNIX INC     2
239                            VICINITY LTD     2

In [64]:
frequency_positions.sort_values(by='Fund', ascending=False).tail(100)

                               Name  Fund
46                          CAE INC     1
47                       CAMURUS AB     1
49     CANADIAN NATIONAL RAILWAY CO     1
50   CANADIAN NATURAL RESOURCES LTD     1
51       CAPITAL ONE FINANCIAL CORP     1
..                              ...   ...
98        HENNES & MAURITZ AB-B SHS     1
99            HOCHSCHILD MINING PLC     1
101     HONEYWELL INTERNATIONAL INC     1
102                      HORIBA LTD     1
250          YARA INTERNATIONAL ASA     1

[100 rows x 2 columns]

In [65]:
merged_data=pd.merge(summed_positions_bytotal, frequency_positions, on="Name")
merged_data.head(50)

                                         Name   Value_Final  Fund
0                                 NVIDIA CORP  1.014952e+11    12
1                              MICROSOFT CORP  7.969974e+10    12
2                                   APPLE INC  7.916417e+10    11
3                                    Alphabet  7.507120e+10    15
4                                      Amazon  4.937953e+10    11
5                                BROADCOM INC  3.662171e+10    11
6                                        META  3.243298e+10     9
7                  TAIWAN SEMICONDUCTOR MAâ¦  2.755529e+10     2
8                                   TESLA INC  2.276376e+10     6
9                              ELI LILLY & CO  1.806661e+10    10
10                        JPMORGAN CHASE & CO  1.702528e+10     8
11                       VANGUARD S&P 500 ETF  1.660000e+10     1
12                     BERKSHIRE HATHAWAY INC  1.547416e+10     8
13                            ASML HOLDING NV  1.271000e+10     2
14                             MASTERCARD INC  1.127898e+10     7
15                          JOHNSON & JOHNSON  1.071953e+10     6
16                SAMSUNG ELECTRONICS CO Lâ¦  1.063063e+10     2
17                       TENCENT HOLDINGS LTD  9.980000e+09     1
18                             VISA INC-CLASS  9.864370e+09     8
19                           EXXON MOBIL CORP  9.574300e+09     3
20                ALIBABA GROUP HOLDING-SPâ¦  8.830000e+09     1
21                      MICRON TECHNOLOGY INC  8.678900e+09     5
22                          HSBC HOLDINGS PLC  8.525040e+09     4
23                                WALMART INC  8.491450e+09     4
24                ROCHE HOLDING AG-GENUSSCâ¦  8.210000e+09     1
25                            ASTRAZENECA PLC  7.650820e+09     6
26                               SK HYNIX INC  7.171230e+09     2
27                           UBS GROUP AG-REG  7.160000e+09     1
28                                     SAP SE  7.110000e+09     1
29                            NOVARTIS AG-REG  7.063240e+09     2
30                              BHP GROUP LTD  6.482540e+09     2
31                              WELLTOWER INC  5.940000e+09     1
32                             WSP GLOBAL INC  5.900000e+09     2
33                RIO TINTO PLC RIO LN SHARES  4.940000e+09     1
34                NATIONAL AUSTRALIA BANK LTD  4.590000e+09     1
35                       EVOLUTION MINING LTD  3.740000e+09     1
36                            BUNGE GLOBAL SA  3.050000e+09     1
37                      INTACT FINANCIAL CORP  2.830000e+09     1
38           EQUINOR ASA - DEPOSITARY RECEIPT  2.770000e+09     1
39                               DNB BANK ASA  2.740000e+09     1
40     DIGITAL REALTY TRUST INC COMMON SHARES  2.660000e+09     2
41                 PROLOGIS INC COMMON SHARES  2.620000e+09     1
42                           GENERAL ELECTRIC  2.589390e+09     3
43                           ALSTOM SA COMMON  2.530000e+09     1
44  TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD  2.470000e+09     1
45                  WOODSIDE ENERGY GROUP LTD  2.370000e+09     1
46                          ORIGIN ENERGY LTD  2.350000e+09     1
47                                 ABBVIE INC  2.228340e+09     6
48                          LAM RESEARCH CORP  2.206650e+09     4
49                      COSTCO WHOLESALE CORP  2.185320e+09     4

In [66]:
merged_data.head(10).to_csv("Mag7.csv")

In [67]:
merged_data.to_csv("merged_data_analysis.csv", index=False)

In [68]:
cleaned_data=pd.read_csv("merged_data_analysis_2.csv", encoding='ISO-8859-1')
cleaned_data.rename(columns={"Unnamed: 3":"Sector","Unnamed: 4":"Country"}, inplace=True)
cleaned_data

,Name,Value_Final,Fund,Sector,Country
0,NVIDIA CORP,1.014950e+11,12,Tech,USA
1,MICROSOFT CORP,7.969974e+10,12,Tech,USA
2,APPLE INC,7.916417e+10,11,Tech,USA
3,Alphabet,7.507120e+10,15,Tech,USA
4,AMAZON.COM INC,4.937953e+10,11,Tech,USA
...,...,...,...,...,...
252,WORKSPACE GROUP PLC,2.470000e+06,1,NaN,NaN
253,CUSTODIAN PROPERTY INCOME REIT PLC,1.560000e+06,1,NaN,NaN
254,SOCIAL HOUSING REIT PLC ORDINARY SHARES,1.440000e+06,1,NaN,NaN
255,NEWRIVER REIT PLC,1.200000e+06,1,NaN,NaN
256,HELICAL PLC,0.000000e+00,1,NaN,NaN

In [69]:
sectorwise=cleaned_data.groupby("Sector").sum().reset_index().sort_values(by='Value_Final', ascending=False)

In [70]:
sectorwise

,Sector,Name,Value_Final,Fund,Country
32,Tech,NVIDIA CORPMICROSOFT CORPAPPLE INCAlphabetAMAZ...,4.844789e+11,90,USAUSAUSAUSAUSAUSAUSAChinaChinaDeutschlandUSAU...
12,Finanzen,JPMORGAN CHASE & COBERKSHIRE HATHAWAY INC CLAS...,8.755251e+10,52,USAUSAUSAUSAUKSchweizAustralienNorwegenKanada ...
5,Chip,TAIWAN SEMICONDUCTOR MANUFACTURING CO LTDASML ...,7.388813e+10,22,TaiwanNiederlandeSdkoreaUSASdkoreaUSAUSA
23,Pharma,ELI LILLY & COJOHNSON & JOHNSONROCHE HOLDING A...,5.440421e+10,31,USAUSASchweizUKSchweizUSA
2,Auto,TESLA INC,2.276376e+10,6,USA
6,ETF,VANGUARD S&P 500 ETFJPMORGAN ACTIVE H YIELD ET...,2.016000e+10,3,USAUSAUSA
22,Oil,EXXON MOBIL CORPEQUINOR ASAWOODSIDE ENERGY GRO...,1.943430e+10,8,USANorwegenAustralienKanadaKanada
4,Bergbau,BHP GROUP LTDRIO TINTO PLC RIO LN SHARESEVOLUT...,1.688000e+10,5,AustralienUKAustralienAustralienAustralien
7,Einzelhandel,WALMART INCCOSTCO WHOLESALE CORPALIMENTATION C...,1.408677e+10,10,USAUSAKanada Kanada
24,Real Estate,WELLTOWER INCDIGITAL REALTY TRUST INC COMMON S...,1.319236e+10,6,USAUSAUSAFrankreichUSA
10,Energie,ORIGIN ENERGY LTDE.ON SENORSK HYDRO ASAEDP SA ...,6.450000e+09,4,AustralienDeutschlandNorwegenPortugal
3,Beratung,WSP GLOBAL INC,5.900000e+09,2,Kanada
34,Versicherung,INTACT FINANCIAL CORPQBE INSURANCE GROUP LTD,4.770000e+09,2,Kanada Australien
1,Anlagenbau,ATKINSREALIS GROUP INCLINDE PLC,3.958470e+09,4,Kanada Irland
8,Eisenbahn,ALSTOM SA COMMONCANADIAN NATIONAL RAILWAY CO,3.930000e+09,2,FrankreichKanada
33,Telekommunikation,CELLNEX TELECOM SA ORDINARY SHAREST-MOBILE US ...,3.730000e+09,3,SpanienUSANorwegen
13,Flugzeug,GENERAL ELECTRICCAE INC,3.639390e+09,4,USAKanada
0,Agrar,BUNGE GLOBAL SA,3.050000e+09,1,Schweiz
27,Ruestung,KONGSBERG GRUPPEN ASARTX CORP,2.695500e+09,2,NorwegenUSA
21,Nahrungsmittel,MOWI ASAORKLA ASA,2.122480e+09,2,NorwegenNorwegen
19,Medizintechnik,FISHER & PAYKEL HEALTHCARE CORP LTD,1.933380e+09,2,Neuseeland
28,Schifffahrt,VIKING HOLDINGS LTD ORDINARY SHARES,1.740000e+09,1,Schweiz
29,Spielehersteller,ARISTOCRAT LEISURE LTD ORDINARY,1.730000e+09,1,Australien
14,Infrastruktur,TRANSURBAN GROUP,1.520000e+09,1,Australien
16,Konsum,PROCTER & GAMBLE CO/THE,1.363010e+09,3,USA
11,Event,LIVE NATION ENTERTAINMENT INC,1.310000e+09,1,USA
31,Stahl,BLUESCOPE STEEL LTD,1.280000e+09,1,Australien
30,Sport,SPORTRADAR GROUP AG CLASS A COMMON SHARES,1.260000e+09,1,Schweiz
17,Lotterie,LOTTERY CORP LTD/THE,1.110000e+09,1,Australien
20,Minen,LYNAS RARE EARTHS LTD,1.070000e+09,1,Australien
26,Recycling,GFL ENVIRONMENTAL INC SUBORDINATE VOTING SHARES,1.060000e+09,1,Kanada
25,Rechenzentren,EQUINIX INC,1.030000e+09,1,USA
18,Medizin,NOVO NORDISK A/S CLASS B COMMON SHARES,9.364100e+08,2,Dnemark
9,Elektronik,JB HI-FI LTD,9.302800e+08,1,Australien
15,Investment,REAVES UTILITY INCOME FUND,9.173900e+08,1,USA

In [71]:
sectorwise.head(10).to_csv("sectorwise_analysis.csv", index=False)

In [72]:
countrywise=cleaned_data.groupby("Country").sum().reset_index().sort_values(by='Value_Final', ascending=False)
countrywise=countrywise.head(10).reset_index(drop=True)
countrywise

,Country,Name,Value_Final,Fund,Sector
0,USA,NVIDIA CORPMICROSOFT CORPAPPLE INCAlphabetAMAZ...,6.406085e+11,191,TechTechTechTechTechTechTechAutoPharmaFinanzen...
1,Australien,BHP GROUP LTDNATIONAL AUSTRALIA BANK LTDEVOLUT...,3.254028e+10,15,BergbauFinanzenBergbauOilEnergieVersicherungSp...
2,Taiwan,TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD,3.002529e+10,3,Chip
3,Schweiz,ROCHE HOLDING AGUBS GROUP AG-REGNOVARTIS AG-RE...,2.911966e+10,8,PharmaFinanzenPharmaAgrarSchifffahrtSport
4,UK,HSBC HOLDINGS PLCASTRAZENECA PLCRIO TINTO PLC ...,2.087210e+10,9,FinanzenPharmaBergbau
5,China,TENCENT HOLDINGS LTDALIBABA GROUP HOLDING-SPâ¦,1.881000e+10,2,TechTech
6,Sdkorea,SAMSUNG ELECTRONICS CO LTDSK HYNIX INC,1.867524e+10,5,ChipChip
7,Kanada,WSP GLOBAL INCINTACT FINANCIAL CORPATKINSREALI...,1.738978e+10,10,BeratungVersicherungAnlagenbauFinanzenFinanzen...
8,Norwegen,EQUINOR ASADNB BANK ASAKONGSBERG GRUPPEN ASANO...,1.367248e+10,8,OilFinanzenRuestungEnergieNahrungsmittelTeleko...
9,Niederlande,ASML HOLDING NV,1.271000e+10,2,Chip

In [73]:
cleaned_data

,Name,Value_Final,Fund,Sector,Country
0,NVIDIA CORP,1.014950e+11,12,Tech,USA
1,MICROSOFT CORP,7.969974e+10,12,Tech,USA
2,APPLE INC,7.916417e+10,11,Tech,USA
3,Alphabet,7.507120e+10,15,Tech,USA
4,AMAZON.COM INC,4.937953e+10,11,Tech,USA
...,...,...,...,...,...
252,WORKSPACE GROUP PLC,2.470000e+06,1,NaN,NaN
253,CUSTODIAN PROPERTY INCOME REIT PLC,1.560000e+06,1,NaN,NaN
254,SOCIAL HOUSING REIT PLC ORDINARY SHARES,1.440000e+06,1,NaN,NaN
255,NEWRIVER REIT PLC,1.200000e+06,1,NaN,NaN
256,HELICAL PLC,0.000000e+00,1,NaN,NaN

In [74]:
data

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund
0,21),ABBVIE INC,52.79MLN,1000000,52.79,5.279000e+07,OTP
1,23),ABBVIE INC,233.94MLN,1000000,233.94,2.339400e+08,BCI
2,21),ABBVIE INC,610.6MLN,1000000,610.60,6.106000e+08,Calstrs
3,25),ABBVIE INC,228.44MLN,1000000,228.44,2.284400e+08,PSP
4,22),ABBVIE INC,2.57MLN,1000000,2.57,2.570000e+06,AP7
...,...,...,...,...,...,...,...
445,5),WOODSIDE ENERGY GROUP LTD,2.37BLN,1000000000,2.37,2.370000e+09,AusSuper
446,26),WORKSPACE GROUP PLC,2.47MLN,1000000,2.47,2.470000e+06,Zorg
447,10),WSP GLOBAL INC,2.30BLN,1000000000,2.30,2.300000e+09,CPP
448,1),WSP GLOBAL INC,3.60BLN,1000000000,3.60,3.600000e+09,CDPQ
449,9),YARA INTERNATIONAL ASA,893.37MLN,1000000,893.37,8.933700e+08,Gov Pens F domestic

In [75]:
merged_on_firm_country=pd.merge(data, cleaned_data[["Name","Country"]], on="Name",how="outer",indicator=True)
merged_on_firm_country

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund,Country,_merge
0,21),ABBVIE INC,52.79MLN,1.000000e+06,52.79,5.279000e+07,OTP,USA,both
1,23),ABBVIE INC,233.94MLN,1.000000e+06,233.94,2.339400e+08,BCI,USA,both
2,21),ABBVIE INC,610.6MLN,1.000000e+06,610.60,6.106000e+08,Calstrs,USA,both
3,25),ABBVIE INC,228.44MLN,1.000000e+06,228.44,2.284400e+08,PSP,USA,both
4,22),ABBVIE INC,2.57MLN,1.000000e+06,2.57,2.570000e+06,AP7,USA,both
...,...,...,...,...,...,...,...,...,...
484,26),WORKSPACE GROUP PLC,2.47MLN,1.000000e+06,2.47,2.470000e+06,Zorg,NaN,both
485,10),WSP GLOBAL INC,2.30BLN,1.000000e+09,2.30,2.300000e+09,CPP,Kanada,both
486,1),WSP GLOBAL INC,3.60BLN,1.000000e+09,3.60,3.600000e+09,CDPQ,Kanada,both
487,9),YARA INTERNATIONAL ASA,893.37MLN,1.000000e+06,893.37,8.933700e+08,Gov Pens F domestic,NaN,both
488,NaN,ZEALAND PHARMA A/S,NaN,NaN,NaN,NaN,NaN,NaN,right_only

In [83]:
merged_on_firm_country[merged_on_firm_country['_merge']=="left_only"].to_csv("missing_country_coord.csv", index=False)

In [85]:
handfilled=pd.read_csv("missing_country_coord_hand.csv",encoding='latin-1', encoding_errors='replace')
handfilled

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund,Country,_merge
0,21),Amazon,371.8MLN,1000000,371.80,371800000,AP4,USA,left_only
1,6),Amazon,1.87BLN,1000000000,1.87,1870000000,Stichting,USA,left_only
2,5),Amazon,30.5BLN,1000000000,30.50,30500000000,Government Pension Fund Global,USA,left_only
3,4),Amazon,4.03BLN,1000000000,4.03,4030000000,CPP,USA,left_only
4,4),Amazon,784.49MLN,1000000,784.49,784490000,BCI,USA,left_only
...,...,...,...,...,...,...,...,...,...
69,17),VISA INC-CLASS,1.2BLN,1000000000,1.20,1200000000,Calpers,USA,left_only
70,38),VISA INC-CLASS,175.4MLN,1000000,175.40,175400000,AP4,USA,left_only
71,15),VISA INC-CLASS,2.44MLN,1000000,2.44,2440000,AP7,USA,left_only
72,25),VISA INC-CLASS,6.54BLN,1000000000,6.54,6540000000,Government Pension Fund Global,USA,left_only
73,14),VISA INC-CLASS,882.5MLN,1000000,882.50,882500000,Calstrs,USA,left_only

In [87]:
automaticmatch=merged_on_firm_country[merged_on_firm_country['_merge']=="both"]
automaticmatch

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund,Country,_merge
0,21),ABBVIE INC,52.79MLN,1.000000e+06,52.79,5.279000e+07,OTP,USA,both
1,23),ABBVIE INC,233.94MLN,1.000000e+06,233.94,2.339400e+08,BCI,USA,both
2,21),ABBVIE INC,610.6MLN,1.000000e+06,610.60,6.106000e+08,Calstrs,USA,both
3,25),ABBVIE INC,228.44MLN,1.000000e+06,228.44,2.284400e+08,PSP,USA,both
4,22),ABBVIE INC,2.57MLN,1.000000e+06,2.57,2.570000e+06,AP7,USA,both
...,...,...,...,...,...,...,...,...,...
483,5),WOODSIDE ENERGY GROUP LTD,2.37BLN,1.000000e+09,2.37,2.370000e+09,AusSuper,Australien,both
484,26),WORKSPACE GROUP PLC,2.47MLN,1.000000e+06,2.47,2.470000e+06,Zorg,NaN,both
485,10),WSP GLOBAL INC,2.30BLN,1.000000e+09,2.30,2.300000e+09,CPP,Kanada,both
486,1),WSP GLOBAL INC,3.60BLN,1.000000e+09,3.60,3.600000e+09,CDPQ,Kanada,both
487,9),YARA INTERNATIONAL ASA,893.37MLN,1.000000e+06,893.37,8.933700e+08,Gov Pens F domestic,NaN,both

In [110]:
automaticmatch["Country"]=automaticmatch["Country"].str.strip()

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_5132/825022254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  automaticmatch["Country"]=automaticmatch["Country"].str.strip()

In [111]:
allmatches=pd.concat([automaticmatch, handfilled], ignore_index=True)
allmatches

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund,Country,_merge
0,21),ABBVIE INC,52.79MLN,1.000000e+06,52.79,5.279000e+07,OTP,USA,both
1,23),ABBVIE INC,233.94MLN,1.000000e+06,233.94,2.339400e+08,BCI,USA,both
2,21),ABBVIE INC,610.6MLN,1.000000e+06,610.60,6.106000e+08,Calstrs,USA,both
3,25),ABBVIE INC,228.44MLN,1.000000e+06,228.44,2.284400e+08,PSP,USA,both
4,22),ABBVIE INC,2.57MLN,1.000000e+06,2.57,2.570000e+06,AP7,USA,both
...,...,...,...,...,...,...,...,...,...
445,17),VISA INC-CLASS,1.2BLN,1.000000e+09,1.20,1.200000e+09,Calpers,USA,left_only
446,38),VISA INC-CLASS,175.4MLN,1.000000e+06,175.40,1.754000e+08,AP4,USA,left_only
447,15),VISA INC-CLASS,2.44MLN,1.000000e+06,2.44,2.440000e+06,AP7,USA,left_only
448,25),VISA INC-CLASS,6.54BLN,1.000000e+09,6.54,6.540000e+09,Government Pension Fund Global,USA,left_only
449,14),VISA INC-CLASS,882.5MLN,1.000000e+06,882.50,8.825000e+08,Calstrs,USA,left_only

In [130]:
allmatches.groupby("Country").sum().reset_index().sort_values(by='Value_Final', ascending=False)[["Country","Value_Final"]].to_csv("countrywise_total_investments.csv", index=False)

In [112]:
homebias_byfund=allmatches[["Country","Fund","Value_Final"]].groupby(["Fund","Country"]).sum().reset_index().sort_values(by=["Fund","Value_Final"], ascending=[True,False])
homebias_byfund

                              Fund      Country   Value_Final
0                              AP4          USA  4.311500e+09
5                              AP7          USA  1.528900e+08
4                              AP7       Taiwan  5.529000e+07
3                              AP7     Sdkorea  1.186000e+07
2                              AP7      Schweiz  3.240000e+06
1                              AP7  Niederlande  0.000000e+00
6                         AusSuper   Australien  3.254028e+10
9                         AusSuper          USA  8.290550e+09
8                         AusSuper           UK  4.940000e+09
7                         AusSuper   Neuseeland  1.933380e+09
13                             BCI          USA  8.263700e+09
11                             BCI       Kanada  1.163930e+09
12                             BCI           UK  6.000900e+08
10                             BCI       Irland  2.296200e+08
15                            CDPQ       Kanada  1.871000e+10
19                            CDPQ          USA  1.599634e+10
14                            CDPQ   Frankreich  3.590000e+09
18                            CDPQ       Taiwan  2.470000e+09
17                            CDPQ     Sdkorea  8.733800e+08
16                            CDPQ      Schweiz  6.364200e+08
26                             CPP          USA  5.233000e+10
22                             CPP       Kanada  7.230000e+09
24                             CPP      Schweiz  6.050000e+09
20                             CPP  Deutschland  1.660000e+09
25                             CPP      Spanien  1.540000e+09
21                             CPP       Irland  1.520000e+09
23                             CPP     Portugal  1.180000e+09
27                         Calpers          USA  9.489210e+10
28                         Calstrs          USA  4.753890e+10
30             Gov Pens F domestic     Norwegen  1.367248e+10
29             Gov Pens F domestic     Dnemark  6.422300e+08
38  Government Pension Fund Global          USA  3.766500e+11
36  Government Pension Fund Global       Taiwan  2.750000e+10
34  Government Pension Fund Global      Schweiz  2.243000e+10
31  Government Pension Fund Global        China  1.881000e+10
35  Government Pension Fund Global     Sdkorea  1.779000e+10
37  Government Pension Fund Global           UK  1.367000e+10
33  Government Pension Fund Global  Niederlande  1.271000e+10
32  Government Pension Fund Global  Deutschland  7.110000e+09
39                             OTP       Kanada  1.060000e+09
41                             OTP          USA  7.668700e+08
40                             OTP           UK  7.819000e+07
45                             PSP          USA  8.476220e+09
43                             PSP       Kanada  1.151540e+09
44                             PSP           UK  3.960100e+08
42                             PSP       Irland  2.288500e+08
47                       Stichting          USA  2.350178e+10
46                       Stichting           UK  1.187810e+09
48                        UniSuper   Australien  4.849840e+09
49                        UniSuper           UK  9.375700e+08

In [117]:
fund_data=data[["Fund","Value_Final"]].groupby("Fund").sum().reset_index().sort_values(by="Value_Final", ascending=False)

In [118]:
aus_data=homebias_byfund[homebias_byfund["Fund"]=="AusSuper"]
aus_data

       Fund     Country   Value_Final
6  AusSuper  Australien  3.254028e+10
9  AusSuper         USA  8.290550e+09
8  AusSuper          UK  4.940000e+09
7  AusSuper  Neuseeland  1.933380e+09

2    5.242673e+10
Name: Value_Final, dtype: float64

In [125]:
aus_data[aus_data["Country"]=="Australien"]["Value_Final"].values[0]/fund_data[fund_data["Fund"]=="AusSuper"]["Value_Final"].values[0]

np.float64(0.6206810914966469)

In [126]:
can_data=homebias_byfund[homebias_byfund["Fund"]=="CDPQ"]
can_data

    Fund     Country   Value_Final
15  CDPQ      Kanada  1.871000e+10
19  CDPQ         USA  1.599634e+10
14  CDPQ  Frankreich  3.590000e+09
18  CDPQ      Taiwan  2.470000e+09
17  CDPQ    Sdkorea  8.733800e+08
16  CDPQ     Schweiz  6.364200e+08

In [127]:
can_data[can_data["Country"]=="Kanada"]["Value_Final"].values[0]/fund_data[fund_data["Fund"]=="CDPQ"]["Value_Final"].values[0]

np.float64(0.4203042679416121)