In [70]:
import pandas as pd
import glob
import numpy as np

In [71]:
files=glob.glob('../data/*.xlsx')
files

['../data/~$Pensionsfonds_extra.xlsx',
 '../data/~$Pensionsfonds_2.xlsx',
 '../data/Pensionsfonds_extra.xlsx',
 '../data/Pensionsfonds.xlsx',
 '../data/Pensionsfonds_2.xlsx']

In [72]:
excel_file = pd.ExcelFile("../data/Pensionsfonds_2.xlsx")
sheet_names = excel_file.sheet_names
print(sheet_names)

['Liste', 'Government Pension Fund Global', 'CPP', 'CDPQ', 'AusSuper', 'BCI', 'Calpers', 'Gov Pens F domestic', 'ART', 'Stichting', 'OTP', 'Zorg']

In [73]:
df_norway=pd.read_excel(excel_file, sheet_name=sheet_names[1])
df_norway

,Top Ind. Group Allocation,Unnamed: 1,Unnamed: 2,Security Results: Norges Bank Government Pension Fund Global (9086 Securities),Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Semiconductors,9.79%,NaN,,Security Name,Mkt Val,Position Ch…,Filing Date,Hold,NaN,NaN
1,Internet,9.44%,NaN,↓,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Banks,8.71%,NaN,1),NVIDIA CORP,61.1BLN,912.44MLN,324.08MLN,4.84MLN,06/30/25,
3,Software,7.47%,NaN,2),ALPHABET INC-CL A,49.79BLN,-1.81BLN,148.84MLN,-5.42MLN,06/30/25,
4,Pharmaceuticals,4.80%,NaN,3),APPLE INC,48.39BLN,844.58MLN,187.36MLN,3.27MLN,06/30/25,
...,...,...,...,...,...,...,...,...,...,...,...
57,NaN,NaN,NaN,56),AMPHENOL CORP-CL A,3.64BLN,317.81MLN,21.88MLN,1.91MLN,06/30/25,
58,NaN,NaN,NaN,57),LVMH MOET HENNESSY LOUIS…,3.6BLN,-300.41MLN,5.09MLN,"-424,384.81",06/30/25,
59,NaN,NaN,NaN,58),CATERPILLAR INC,3.56BLN,-211.54MLN,5.57MLN,"-331,088.83",06/30/25,
60,NaN,NaN,NaN,59),ORACLE CORP,3.52BLN,1.25BLN,20.1MLN,7.16MLN,06/30/25,
61,NaN,NaN,NaN,60),BANCO SANTANDER SA,3.51BLN,0,270.89MLN,0,01/23/26,NaN

In [74]:
df_columns_with_char = df_norway.columns[df_norway.columns.str.contains(")", na=False, regex=False)]
index_numbers = [df_norway.columns.get_loc(col) for col in df_columns_with_char]
print(index_numbers)

[3]

In [75]:
df_norway.columns[index_numbers[0]:(index_numbers[0]+3)]

Index([' Security Results: Norges Bank Government Pension Fund Global (9086 Securities)',
       'Unnamed: 4', 'Unnamed: 5'],
      dtype='object')

In [76]:
norway_red_df=df_norway[df_norway.columns[index_numbers[0]:(index_numbers[0]+3)]]
norway_red_df

,Security Results: Norges Bank Government Pension Fund Global (9086 Securities),Unnamed: 4,Unnamed: 5
0,,Security Name,Mkt Val
1,↓,NaN,NaN
2,1),NVIDIA CORP,61.1BLN
3,2),ALPHABET INC-CL A,49.79BLN
4,3),APPLE INC,48.39BLN
...,...,...,...
57,56),AMPHENOL CORP-CL A,3.64BLN
58,57),LVMH MOET HENNESSY LOUIS…,3.6BLN
59,58),CATERPILLAR INC,3.56BLN
60,59),ORACLE CORP,3.52BLN
61,60),BANCO SANTANDER SA,3.51BLN

In [77]:
# Find rows where any cell contains the character
search_string = ")"
mask = norway_red_df.apply(lambda col: col.astype(str).str.contains(search_string, na=False, regex=False), axis=1).any(axis=1)
norway_red_pos = norway_red_df[mask]
norway_red_pos.columns=["Rank","Name","Value"]
norway_red_pos

   Rank                        Name     Value
2    1)                 NVIDIA CORP   61.1BLN
3    2)           ALPHABET INC-CL A  49.79BLN
4    3)                   APPLE INC  48.39BLN
5    4)              MICROSOFT CORP  48.29BLN
6    5)              AMAZON.COM INC   30.5BLN
7    6)    TAIWAN SEMICONDUCTOR MA…   27.5BLN
8    7)                BROADCOM INC  22.21BLN
9    8)  META PLATFORMS INC-CLASS A  21.05BLN
10   9)                   TESLA INC   15.9BLN
11  10)             ASML HOLDING NV  12.71BLN
12  11)              ELI LILLY & CO  11.73BLN
13  12)   SAMSUNG ELECTRONICS CO L…  10.62BLN
14  13)         JPMORGAN CHASE & CO  10.52BLN
15  14)   BERKSHIRE HATHAWAY INC-C…   10.5BLN
16  15)        TENCENT HOLDINGS LTD   9.98BLN
17  16)   ALIBABA GROUP HOLDING-SP…   8.83BLN
18  17)   ROCHE HOLDING AG-GENUSSC…   8.21BLN
19  18)            EXXON MOBIL CORP   7.76BLN
20  19)           HSBC HOLDINGS PLC   7.47BLN
21  20)                SK HYNIX INC   7.17BLN
22  21)            UBS GROUP AG-REG   7.16BLN
23  22)           JOHNSON & JOHNSON   7.15BLN
24  23)                      SAP SE   7.11BLN
25  24)             NOVARTIS AG-REG   7.06BLN
26  25)     VISA INC-CLASS A SHARES   6.54BLN
27  26)       MICRON TECHNOLOGY INC   6.51BLN
28  27)          MASTERCARD INC - A   6.39BLN
29  28)                 WALMART INC   6.38BLN
30  29)             ASTRAZENECA PLC    6.2BLN
31  30)               WELLTOWER INC   5.94BLN
32  31)        BANK OF AMERICA CORP   5.59BLN
33  32)               NESTLE SA-REG   5.55BLN
34  33)       COSTCO WHOLESALE CORP   5.55BLN
35  34)      ADVANCED MICRO DEVICES   5.36BLN
36  35)                  ABBVIE INC   5.25BLN
37  36)                   SHELL PLC   5.24BLN
38  37)          NOVO NORDISK A/S-B   5.19BLN
39  38)                 NETFLIX INC   5.11BLN
40  39)              HOME DEPOT INC   5.01BLN
41  40)           LAM RESEARCH CORP   4.74BLN
42  41)     PROCTER & GAMBLE CO/THE   4.71BLN
43  42)   PALANTIR TECHNOLOGIES IN…   4.54BLN
44  43)            WELLS FARGO & CO   4.44BLN
45  44)              SIEMENS AG-REG   4.42BLN
46  45)           CISCO SYSTEMS INC   4.35BLN
47  46)   BANCO BILBAO VIZCAYA ARG…   4.21BLN
48  47)                IBERDROLA SA   4.04BLN
49  48)            COCA-COLA CO/THE   3.97BLN
50  49)            GENERAL ELECTRIC   3.94BLN
51  50)           TOYOTA MOTOR CORP   3.89BLN
52  51)            MERCK & CO. INC.   3.86BLN
53  52)                 BNP PARIBAS   3.84BLN
54  53)               UNICREDIT SPA   3.74BLN
55  54)       SCHNEIDER ELECTRIC SE   3.69BLN
56  55)    DIGITAL REALTY TRUST INC   3.64BLN
57  56)          AMPHENOL CORP-CL A   3.64BLN
58  57)   LVMH MOET HENNESSY LOUIS…    3.6BLN
59  58)             CATERPILLAR INC   3.56BLN
60  59)                 ORACLE CORP   3.52BLN
61  60)          BANCO SANTANDER SA   3.51BLN

In [78]:
norway_red_pos["Suffix"]=0
norway_red_pos["Suffix"] = np.where(norway_red_pos["Value"].str.contains("BLN"), 10**9,norway_red_pos["Suffix"] )
norway_red_pos["Suffix"] = np.where(norway_red_pos["Value"].str.contains("MLN"), 10**6,norway_red_pos["Suffix"] )
norway_red_pos

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2189678865.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  norway_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2189678865.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  norway_red_pos["Suffix"] = np.where(norway_red_pos["Value"].str.contains("BLN"), 10**9,norway_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2189678865.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  norway_red_pos["Suffix"] = np.where(norway_red_pos["Value"].str.contains("MLN"), 10**6,norway_red_pos["Suffix"] )

   Rank                        Name     Value      Suffix
2    1)                 NVIDIA CORP   61.1BLN  1000000000
3    2)           ALPHABET INC-CL A  49.79BLN  1000000000
4    3)                   APPLE INC  48.39BLN  1000000000
5    4)              MICROSOFT CORP  48.29BLN  1000000000
6    5)              AMAZON.COM INC   30.5BLN  1000000000
7    6)    TAIWAN SEMICONDUCTOR MA…   27.5BLN  1000000000
8    7)                BROADCOM INC  22.21BLN  1000000000
9    8)  META PLATFORMS INC-CLASS A  21.05BLN  1000000000
10   9)                   TESLA INC   15.9BLN  1000000000
11  10)             ASML HOLDING NV  12.71BLN  1000000000
12  11)              ELI LILLY & CO  11.73BLN  1000000000
13  12)   SAMSUNG ELECTRONICS CO L…  10.62BLN  1000000000
14  13)         JPMORGAN CHASE & CO  10.52BLN  1000000000
15  14)   BERKSHIRE HATHAWAY INC-C…   10.5BLN  1000000000
16  15)        TENCENT HOLDINGS LTD   9.98BLN  1000000000
17  16)   ALIBABA GROUP HOLDING-SP…   8.83BLN  1000000000
18  17)   ROCHE HOLDING AG-GENUSSC…   8.21BLN  1000000000
19  18)            EXXON MOBIL CORP   7.76BLN  1000000000
20  19)           HSBC HOLDINGS PLC   7.47BLN  1000000000
21  20)                SK HYNIX INC   7.17BLN  1000000000
22  21)            UBS GROUP AG-REG   7.16BLN  1000000000
23  22)           JOHNSON & JOHNSON   7.15BLN  1000000000
24  23)                      SAP SE   7.11BLN  1000000000
25  24)             NOVARTIS AG-REG   7.06BLN  1000000000
26  25)     VISA INC-CLASS A SHARES   6.54BLN  1000000000
27  26)       MICRON TECHNOLOGY INC   6.51BLN  1000000000
28  27)          MASTERCARD INC - A   6.39BLN  1000000000
29  28)                 WALMART INC   6.38BLN  1000000000
30  29)             ASTRAZENECA PLC    6.2BLN  1000000000
31  30)               WELLTOWER INC   5.94BLN  1000000000
32  31)        BANK OF AMERICA CORP   5.59BLN  1000000000
33  32)               NESTLE SA-REG   5.55BLN  1000000000
34  33)       COSTCO WHOLESALE CORP   5.55BLN  1000000000
35  34)      ADVANCED MICRO DEVICES   5.36BLN  1000000000
36  35)                  ABBVIE INC   5.25BLN  1000000000
37  36)                   SHELL PLC   5.24BLN  1000000000
38  37)          NOVO NORDISK A/S-B   5.19BLN  1000000000
39  38)                 NETFLIX INC   5.11BLN  1000000000
40  39)              HOME DEPOT INC   5.01BLN  1000000000
41  40)           LAM RESEARCH CORP   4.74BLN  1000000000
42  41)     PROCTER & GAMBLE CO/THE   4.71BLN  1000000000
43  42)   PALANTIR TECHNOLOGIES IN…   4.54BLN  1000000000
44  43)            WELLS FARGO & CO   4.44BLN  1000000000
45  44)              SIEMENS AG-REG   4.42BLN  1000000000
46  45)           CISCO SYSTEMS INC   4.35BLN  1000000000
47  46)   BANCO BILBAO VIZCAYA ARG…   4.21BLN  1000000000
48  47)                IBERDROLA SA   4.04BLN  1000000000
49  48)            COCA-COLA CO/THE   3.97BLN  1000000000
50  49)            GENERAL ELECTRIC   3.94BLN  1000000000
51  50)           TOYOTA MOTOR CORP   3.89BLN  1000000000
52  51)            MERCK & CO. INC.   3.86BLN  1000000000
53  52)                 BNP PARIBAS   3.84BLN  1000000000
54  53)               UNICREDIT SPA   3.74BLN  1000000000
55  54)       SCHNEIDER ELECTRIC SE   3.69BLN  1000000000
56  55)    DIGITAL REALTY TRUST INC   3.64BLN  1000000000
57  56)          AMPHENOL CORP-CL A   3.64BLN  1000000000
58  57)   LVMH MOET HENNESSY LOUIS…    3.6BLN  1000000000
59  58)             CATERPILLAR INC   3.56BLN  1000000000
60  59)                 ORACLE CORP   3.52BLN  1000000000
61  60)          BANCO SANTANDER SA   3.51BLN  1000000000

In [79]:
norway_red_pos["Value_Clean"]=norway_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
norway_red_pos["Value_Final"]=norway_red_pos["Value_Clean"]*norway_red_pos["Suffix"]
norway_red_pos=norway_red_pos.reset_index(drop=True)
norway_red_pos=norway_red_pos.iloc[:30]

norway_red_pos["Fund"]=sheet_names[1]

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/254385032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  norway_red_pos["Value_Clean"]=norway_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/254385032.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  norway_red_pos["Value_Final"]=norway_red_pos["Value_Clean"]*norway_red_pos["Suffix"]

In [80]:
base_df=pd.DataFrame()
for i in range(2,len(sheet_names)):
    print(i)
    print(sheet_names[i])
    if sheet_names[i]!="ART":
        df_other=pd.read_excel(excel_file, sheet_name=sheet_names[i])
        df_other
        # Find columns where any cell value contains ")"
        search_string = ")"
        columns_with_char = []

        for col in df_other.columns:
            if df_other[col].astype(str).str.contains(search_string, na=False, regex=False).any():
                columns_with_char.append(col)

        # Get index numbers of those columns
        index_numbers = [df_other.columns.get_loc(col) for col in columns_with_char]
        print(index_numbers)
        other_red_df=df_other[df_other.columns[[index_numbers[0],(index_numbers[0]+2),(index_numbers[0]+5)]]]
        # Find rows where any cell contains the character
        search_string = ")"
        mask = other_red_df.apply(lambda col: col.astype(str).str.contains(search_string, na=False, regex=False), axis=1).any(axis=1)
        other_red_pos = other_red_df[mask]
        other_red_pos.columns=["Rank","Name","Value"]
        other_red_pos["Suffix"]=0
        other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
        other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
        other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
        other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
        other_red_pos["Fund"]=sheet_names[i]
        other_red_pos=other_red_pos.reset_index(drop=True)
        other_red_pos=other_red_pos.iloc[:30]
        print(len(other_red_pos))
        base_df=pd.concat([base_df,other_red_pos],ignore_index=True)
    else:
        print("Skipping ART sheet")
    base_df

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]

2
CPP
[3]
30
3
CDPQ
[4]
30
4
AusSuper
[3]
30
5
BCI
[5]
30
6
Calpers
[4]
30
7
Gov Pens F domestic
[4]
30
8
ART
Skipping ART sheet
9
Stichting
[4]
30
10
OTP
[5]
30
11
Zorg
[5]
30

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/2400238953.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]

In [81]:
allpos_df=pd.concat([norway_red_pos,base_df],ignore_index=True)
allpos_df

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund
0,1),NVIDIA CORP,61.1BLN,1000000000,61.10,6.110000e+10,Government Pension Fund Global
1,2),ALPHABET INC-CL A,49.79BLN,1000000000,49.79,4.979000e+10,Government Pension Fund Global
2,3),APPLE INC,48.39BLN,1000000000,48.39,4.839000e+10,Government Pension Fund Global
3,4),MICROSOFT CORP,48.29BLN,1000000000,48.29,4.829000e+10,Government Pension Fund Global
4,5),AMAZON.COM INC,30.5BLN,1000000000,30.50,3.050000e+10,Government Pension Fund Global
...,...,...,...,...,...,...,...
295,26),Workspace Group PLC,2.47MLN,1000000,2.47,2.470000e+06,Zorg
296,27),Custodian Property Income Reit PLC,1.56MLN,1000000,1.56,1.560000e+06,Zorg
297,28),Social Housing Reit PLC Ordinary Shares,1.44MLN,1000000,1.44,1.440000e+06,Zorg
298,29),NewRiver REIT PLC,1.20MLN,1000000,1.20,1.200000e+06,Zorg
299,30),Helical PLC,967.296,1000000,NaN,NaN,Zorg

In [82]:
excel_file_2 = pd.ExcelFile("../data/Pensionsfonds_extra.xlsx")
sheet_names = excel_file_2.sheet_names
print(sheet_names)

['Liste', 'ATP', 'PSP', 'Calstrs', 'AP7', 'AP4', 'UniSuper', 'AP3']

In [83]:
base_df=pd.DataFrame()
for i in range(1,len(sheet_names)-2):
    print(i)
    print(sheet_names[i])
    if sheet_names[i]!="ART":
        df_other=pd.read_excel(excel_file_2, sheet_name=sheet_names[i])
        df_other
        # Find columns where any cell value contains ")"
        search_string = ")"
        columns_with_char = []

        for col in df_other.columns:
            if df_other[col].astype(str).str.contains(search_string, na=False, regex=False).any():
                columns_with_char.append(col)

        # Get index numbers of those columns
        index_numbers = [df_other.columns.get_loc(col) for col in columns_with_char]
        print(index_numbers)
        other_red_df=df_other[df_other.columns[[index_numbers[0],(index_numbers[0]+2),(index_numbers[0]+5)]]]
        # Find rows where any cell contains the character
        search_string = ")"
        mask = other_red_df.apply(lambda col: col.astype(str).str.contains(search_string, na=False, regex=False), axis=1).any(axis=1)
        other_red_pos = other_red_df[mask]
        other_red_pos.columns=["Rank","Name","Value"]
        other_red_pos["Suffix"]=0
        other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
        other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
        other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
        other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
        other_red_pos["Fund"]=sheet_names[i]
        other_red_pos=other_red_pos.reset_index(drop=True)
        other_red_pos=other_red_pos.iloc[:30]
        base_df=pd.concat([base_df,other_red_pos],ignore_index=True)
    base_df

1
ATP
[4]
2
PSP
[5]
3
Calstrs
[5, 7]
4
AP7
[5]
5
AP4
[5]

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"]=0
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("BLN"), 10**9,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Suffix"] = np.where(other_red_pos["Value"].str.contains("MLN"), 10**6,other_red_pos["Suffix"] )
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Clean"]=other_red_pos["Value"].str.replace(r'[^0-9.]', '', regex=True).astype(float)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Value_Final"]=other_red_pos["Value_Clean"]*other_red_pos["Suffix"]
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_72133/4288486828.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  other_red_pos["Fund"]=sheet_names[i]

In [84]:
base_df

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund
0,1),Danske Bank A/S,369.32MLN,1000000,369.32,369320000.0,ATP
1,2),ALK-Abello A/S Class B Common Shares,345.45MLN,1000000,345.45,345450000.0,ATP
2,3),DSV A/S,314.08MLN,1000000,314.08,314080000.0,ATP
3,4),Vestas Wind Systems A/S,308.12MLN,1000000,308.12,308120000.0,ATP
4,5),Per Aarsleff Holding A/S Class B Common Shares,299.69MLN,1000000,299.69,299690000.0,ATP
...,...,...,...,...,...,...,...
145,36),BIOARCTIC AB,193.6MLN,1000000,193.60,193600000.0,AP4
146,37),JOHNSON & JOHNSON,183.5MLN,1000000,183.50,183500000.0,AP4
147,38),VISA INC-CLASS A SHARES,175.4MLN,1000000,175.40,175400000.0,AP4
148,39),SAGAX AB-B,172.4MLN,1000000,172.40,172400000.0,AP4
149,40),BILLERUD AB,163.8MLN,1000000,163.80,163800000.0,AP4

In [90]:
allpos_df_extended=pd.concat([allpos_df,base_df],ignore_index=True)
allpos_df_extended

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund
0,1),NVIDIA CORP,61.1BLN,1000000000,61.10,6.110000e+10,Government Pension Fund Global
1,2),ALPHABET INC-CL A,49.79BLN,1000000000,49.79,4.979000e+10,Government Pension Fund Global
2,3),APPLE INC,48.39BLN,1000000000,48.39,4.839000e+10,Government Pension Fund Global
3,4),MICROSOFT CORP,48.29BLN,1000000000,48.29,4.829000e+10,Government Pension Fund Global
4,5),AMAZON.COM INC,30.5BLN,1000000000,30.50,3.050000e+10,Government Pension Fund Global
...,...,...,...,...,...,...,...
445,36),BIOARCTIC AB,193.6MLN,1000000,193.60,1.936000e+08,AP4
446,37),JOHNSON & JOHNSON,183.5MLN,1000000,183.50,1.835000e+08,AP4
447,38),VISA INC-CLASS A SHARES,175.4MLN,1000000,175.40,1.754000e+08,AP4
448,39),SAGAX AB-B,172.4MLN,1000000,172.40,1.724000e+08,AP4
449,40),BILLERUD AB,163.8MLN,1000000,163.80,1.638000e+08,AP4

In [93]:
allpos_df_extended["Fund"].drop_duplicates().to_csv("allFunds.csv", index=False)

In [94]:
allpos_df_extended["Name"]=allpos_df_extended["Name"].str.upper()
allpos_df_extended

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund
0,1),NVIDIA CORP,61.1BLN,1000000000,61.10,6.110000e+10,Government Pension Fund Global
1,2),ALPHABET INC-CL A,49.79BLN,1000000000,49.79,4.979000e+10,Government Pension Fund Global
2,3),APPLE INC,48.39BLN,1000000000,48.39,4.839000e+10,Government Pension Fund Global
3,4),MICROSOFT CORP,48.29BLN,1000000000,48.29,4.829000e+10,Government Pension Fund Global
4,5),AMAZON.COM INC,30.5BLN,1000000000,30.50,3.050000e+10,Government Pension Fund Global
...,...,...,...,...,...,...,...
445,36),BIOARCTIC AB,193.6MLN,1000000,193.60,1.936000e+08,AP4
446,37),JOHNSON & JOHNSON,183.5MLN,1000000,183.50,1.835000e+08,AP4
447,38),VISA INC-CLASS A SHARES,175.4MLN,1000000,175.40,1.754000e+08,AP4
448,39),SAGAX AB-B,172.4MLN,1000000,172.40,1.724000e+08,AP4
449,40),BILLERUD AB,163.8MLN,1000000,163.80,1.638000e+08,AP4

In [95]:
allpos_df_extended.sort_values(by="Name", ascending=True, inplace=True)
allpos_df_extended

,Rank,Name,Value,Suffix,Value_Clean,Value_Final,Fund
169,20),ABBVIE INC,1.1BLN,1000000000,1.10,1.100000e+09,Calpers
142,23),ABBVIE INC,233.94MLN,1000000,233.94,2.339400e+08,BCI
380,21),ABBVIE INC,610.6MLN,1000000,610.60,6.106000e+08,Calstrs
354,25),ABBVIE INC,228.44MLN,1000000,228.44,2.284400e+08,PSP
260,21),ABBVIE INC,52.79MLN,1000000,52.79,5.279000e+07,OTP
...,...,...,...,...,...,...,...
295,26),WORKSPACE GROUP PLC,2.47MLN,1000000,2.47,2.470000e+06,Zorg
60,1),WSP GLOBAL INC,3.60BLN,1000000000,3.60,3.600000e+09,CDPQ
39,10),WSP GLOBAL INC,2.30BLN,1000000000,2.30,2.300000e+09,CPP
188,9),YARA INTERNATIONAL ASA,893.37MLN,1000000,893.37,8.933700e+08,Gov Pens F domestic
329,30),ZEALAND PHARMA A/S,41.37MLN,1000000,41.37,4.137000e+07,ATP

In [96]:
allpos_df_extended.to_csv("../data/all_pensionfund_red_positions_before.csv", index=False)