In [64]:
import pandas as pd
import glob
import numpy as np

In [65]:
vars=[['Country Name','Country Code',"Land",
             'gdp_rel_ger','ppp_rel_ger', 'cost_to_gdp', 'popdensity', 'homicides',
      'FreedomScore', 'PISA Score','timediff_to_germany', 'Cuisine Rank', 
      'SunshineHours_per_year', 'sqm/sqkm', 'max_m', 'min_m', 'English Proficiency', 
       'Anzahl_der_Deutschen_numeric', 'Bureaucracy Score', 'MaxTemperature',
       'MinTemperature', 'LivingConditions', 'Healthcare', 'CostofLiving', 
       'Christian_%', 'Muslim_%', 'Irreligion_%', 'Hindu_%', 'Buddhist_%',
       'Folk religion_%', 'Other religion_%', 'Jewish_%', 'ban',
       'LGBTQ',"Sonnenstunde_pro_Tag"]]

In [66]:
data=pd.read_csv("../newdata/all_measures_v4.csv")
data

,Unnamed: 0,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,Country or Territory,FreedomScore,...,Muslim_%,Irreligion_%,Hindu_%,Buddhist_%,Folk religion_%,Other religion_%,Jewish_%,ban,Code,LGBTQ
0,0,Burundi,BDI,0.002759,0.209981,76.118642,533.078271,5.649742,Burundi,15,...,2.1,0.0,0.0,0.0,5.7,0.0,0.0,NaN,BDI,7.91
1,1,Central African Republic,CAF,0.009250,0.529283,57.217771,8.270604,20.120401,Central African Republic,5,...,15.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,CAF,27.03
2,2,"Yemen, Rep.",YEM,0.011360,0.564557,49.697205,74.608025,5.809719,Yemen,10,...,99.1,0.1,0.6,0.0,0.0,0.0,0.0,1.0,YEM,2.86
3,3,"Somalia, Fed. Rep.",SOM,0.011415,0.515590,45.166019,29.264219,NaN,Somalia,8,...,99.8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,SOM,1.00
4,4,South Sudan,SSD,0.019357,0.863409,44.603580,18.171908,13.982581,South Sudan,1,...,6.2,0.5,0.0,0.0,32.9,0.0,0.0,NaN,SSD,6.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,217,Northern Mariana Islands,MNP,0.426266,NaN,NaN,98.136957,NaN,NaN,NaN,...,0.7,1.0,0.0,10.6,5.3,1.1,0.0,NaN,NaN,NaN
218,218,New Caledonia,NCL,0.600649,NaN,NaN,15.857221,3.109821,NaN,NaN,...,2.8,10.4,0.0,0.6,0.2,0.8,0.0,NaN,NaN,NaN
219,219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,North Korea,3,...,0.0,71.3,0.0,1.5,12.3,12.9,0.0,NaN,PRK,32.11
220,220,French Polynesia,PYF,0.408137,NaN,NaN,80.990493,0.371083,NaN,NaN,...,0.1,4.8,0.0,0.0,0.5,0.4,0.0,NaN,NaN,NaN
221,221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,...,1.2,3.9,1.2,0.0,8.4,0.8,0.0,NaN,NaN,NaN

In [67]:
vars

[['Country Name',
  'Country Code',
  'Land',
  'gdp_rel_ger',
  'ppp_rel_ger',
  'cost_to_gdp',
  'popdensity',
  'homicides',
  'FreedomScore',
  'PISA Score',
  'timediff_to_germany',
  'Cuisine Rank',
  'SunshineHours_per_year',
  'sqm/sqkm',
  'max_m',
  'min_m',
  'English Proficiency',
  'Anzahl_der_Deutschen_numeric',
  'Bureaucracy Score',
  'MaxTemperature',
  'MinTemperature',
  'LivingConditions',
  'Healthcare',
  'CostofLiving',
  'Christian_%',
  'Muslim_%',
  'Irreligion_%',
  'Hindu_%',
  'Buddhist_%',
  'Folk religion_%',
  'Other religion_%',
  'Jewish_%',
  'ban',
  'LGBTQ',
  'Sonnenstunde_pro_Tag']]

In [68]:
data.columns

Index(['Unnamed: 0', 'Country Name', 'Country Code', 'gdp_rel_ger',
       'ppp_rel_ger', 'cost_to_gdp', 'popdensity', 'homicides',
       'Country or Territory', 'FreedomScore', 'PISA Score',
       'timediff_to_germany', 'Cuisine Rank', 'SunshineHours_per_year',
       'sqm/sqkm', 'max_m', 'min_m', 'English Proficiency', 'Land', 'ISO3',
       'Anzahl_der_Deutschen_numeric', 'Bureaucracy Score', 'MaxTemperature',
       'MinTemperature', 'LivingConditions', 'Healthcare', 'CostofLiving',
       'Country', 'Christian_%', 'Muslim_%', 'Irreligion_%', 'Hindu_%',
       'Buddhist_%', 'Folk religion_%', 'Other religion_%', 'Jewish_%', 'ban',
       'Code', 'LGBTQ'],
      dtype='object')

In [69]:
data.drop(columns=['Unnamed: 0',"Code",
      'Country or Territory',], inplace=True)

In [70]:
data.columns

Index(['Country Name', 'Country Code', 'gdp_rel_ger', 'ppp_rel_ger',
       'cost_to_gdp', 'popdensity', 'homicides', 'FreedomScore', 'PISA Score',
       'timediff_to_germany', 'Cuisine Rank', 'SunshineHours_per_year',
       'sqm/sqkm', 'max_m', 'min_m', 'English Proficiency', 'Land', 'ISO3',
       'Anzahl_der_Deutschen_numeric', 'Bureaucracy Score', 'MaxTemperature',
       'MinTemperature', 'LivingConditions', 'Healthcare', 'CostofLiving',
       'Country', 'Christian_%', 'Muslim_%', 'Irreligion_%', 'Hindu_%',
       'Buddhist_%', 'Folk religion_%', 'Other religion_%', 'Jewish_%', 'ban',
       'LGBTQ'],
      dtype='object')

In [71]:
data_dropped=data.copy()
df_to_check=data_dropped.copy()

In [72]:
df_to_check["gdp_rel_ger"]=df_to_check["gdp_rel_ger"]*100
df_to_check["ppp_rel_ger"]=df_to_check["ppp_rel_ger"]*100
df_to_check["Anzahl_der_Deutschen_numeric"]=np.where(df_to_check["Land"]=="Deutschland",np.nan,df_to_check["Anzahl_der_Deutschen_numeric"])
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Christian_%,Muslim_%,Irreligion_%,Hindu_%,Buddhist_%,Folk religion_%,Other religion_%,Jewish_%,ban,LGBTQ
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15,NaN,0.0,...,93.40,2.1,0.0,0.0,0.0,5.7,0.0,0.0,NaN,7.91
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5,NaN,1.0,...,89.50,15.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,27.03
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10,NaN,1.0,...,0.20,99.1,0.1,0.6,0.0,0.0,0.0,0.0,1.0,2.86
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8,NaN,1.0,...,0.01,99.8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.00
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1,NaN,0.0,...,60.50,6.2,0.5,0.0,0.0,32.9,0.0,0.0,NaN,6.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,81.30,0.7,1.0,0.0,10.6,5.3,1.1,0.0,NaN,NaN
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,85.20,2.8,10.4,0.0,0.6,0.2,0.8,0.0,NaN,NaN
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3,NaN,7.0,...,2.00,0.0,71.3,0.0,1.5,12.3,12.9,0.0,NaN,32.11
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,94.00,0.1,4.8,0.0,0.0,0.5,0.4,0.0,NaN,NaN
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,84.50,1.2,3.9,1.2,0.0,8.4,0.8,0.0,NaN,NaN

In [73]:
df_to_check["FreedomScore"]=pd.to_numeric(df_to_check["FreedomScore"], errors='coerce')
df_to_check["LGBTQ"]=pd.to_numeric(df_to_check["LGBTQ"], errors='coerce')
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Christian_%,Muslim_%,Irreligion_%,Hindu_%,Buddhist_%,Folk religion_%,Other religion_%,Jewish_%,ban,LGBTQ
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15.0,NaN,0.0,...,93.40,2.1,0.0,0.0,0.0,5.7,0.0,0.0,NaN,7.91
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5.0,NaN,1.0,...,89.50,15.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,27.03
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10.0,NaN,1.0,...,0.20,99.1,0.1,0.6,0.0,0.0,0.0,0.0,1.0,2.86
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8.0,NaN,1.0,...,0.01,99.8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.00
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1.0,NaN,0.0,...,60.50,6.2,0.5,0.0,0.0,32.9,0.0,0.0,NaN,6.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,81.30,0.7,1.0,0.0,10.6,5.3,1.1,0.0,NaN,NaN
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,85.20,2.8,10.4,0.0,0.6,0.2,0.8,0.0,NaN,NaN
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,2.00,0.0,71.3,0.0,1.5,12.3,12.9,0.0,NaN,32.11
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,94.00,0.1,4.8,0.0,0.0,0.5,0.4,0.0,NaN,NaN
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,84.50,1.2,3.9,1.2,0.0,8.4,0.8,0.0,NaN,NaN

In [74]:
df_to_check["SunshineHours_per_year"]=pd.to_numeric(df_to_check["SunshineHours_per_year"], errors='coerce')
df_to_check["Sonnenstunde_pro_Tag"]=df_to_check["SunshineHours_per_year"]/365
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Muslim_%,Irreligion_%,Hindu_%,Buddhist_%,Folk religion_%,Other religion_%,Jewish_%,ban,LGBTQ,Sonnenstunde_pro_Tag
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15.0,NaN,0.0,...,2.1,0.0,0.0,0.0,5.7,0.0,0.0,NaN,7.91,6.502466
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5.0,NaN,1.0,...,15.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,27.03,6.976712
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10.0,NaN,1.0,...,99.1,0.1,0.6,0.0,0.0,0.0,0.0,1.0,2.86,8.531507
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8.0,NaN,1.0,...,99.8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.00,8.501370
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1.0,NaN,0.0,...,6.2,0.5,0.0,0.0,32.9,0.0,0.0,NaN,6.83,7.784384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,0.7,1.0,0.0,10.6,5.3,1.1,0.0,NaN,NaN,6.164384
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,2.8,10.4,0.0,0.6,0.2,0.8,0.0,NaN,NaN,6.994521
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,0.0,71.3,0.0,1.5,12.3,12.9,0.0,NaN,32.11,6.827397
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,0.1,4.8,0.0,0.0,0.5,0.4,0.0,NaN,NaN,7.358904
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,1.2,3.9,1.2,0.0,8.4,0.8,0.0,NaN,NaN,8.950685

In [75]:
df_to_check["Mehrals5Morde_pro_100k_boolean"]=np.where(df_to_check["homicides"]>=5,True,False)
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Irreligion_%,Hindu_%,Buddhist_%,Folk religion_%,Other religion_%,Jewish_%,ban,LGBTQ,Sonnenstunde_pro_Tag,Mehrals5Morde_pro_100k_boolean
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15.0,NaN,0.0,...,0.0,0.0,0.0,5.7,0.0,0.0,NaN,7.91,6.502466,True
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5.0,NaN,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,NaN,27.03,6.976712,True
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10.0,NaN,1.0,...,0.1,0.6,0.0,0.0,0.0,0.0,1.0,2.86,8.531507,True
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8.0,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.00,8.501370,False
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1.0,NaN,0.0,...,0.5,0.0,0.0,32.9,0.0,0.0,NaN,6.83,7.784384,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,1.0,0.0,10.6,5.3,1.1,0.0,NaN,NaN,6.164384,False
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,10.4,0.0,0.6,0.2,0.8,0.0,NaN,NaN,6.994521,False
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,71.3,0.0,1.5,12.3,12.9,0.0,NaN,32.11,6.827397,False
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,4.8,0.0,0.0,0.5,0.4,0.0,NaN,NaN,7.358904,False
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,3.9,1.2,0.0,8.4,0.8,0.0,NaN,NaN,8.950685,True

In [76]:
df_to_check["Mehrals1000Deutsche_boolean"]=np.where(df_to_check["Anzahl_der_Deutschen_numeric"]>=1000,True,False)
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Hindu_%,Buddhist_%,Folk religion_%,Other religion_%,Jewish_%,ban,LGBTQ,Sonnenstunde_pro_Tag,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15.0,NaN,0.0,...,0.0,0.0,5.7,0.0,0.0,NaN,7.91,6.502466,True,False
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5.0,NaN,1.0,...,0.0,0.0,1.0,0.0,0.0,NaN,27.03,6.976712,True,False
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10.0,NaN,1.0,...,0.6,0.0,0.0,0.0,0.0,1.0,2.86,8.531507,True,False
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8.0,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.00,8.501370,False,False
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1.0,NaN,0.0,...,0.0,0.0,32.9,0.0,0.0,NaN,6.83,7.784384,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,0.0,10.6,5.3,1.1,0.0,NaN,NaN,6.164384,False,False
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,0.0,0.6,0.2,0.8,0.0,NaN,NaN,6.994521,False,False
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,0.0,1.5,12.3,12.9,0.0,NaN,32.11,6.827397,False,False
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,0.0,0.0,0.5,0.4,0.0,NaN,NaN,7.358904,False,False
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,1.2,0.0,8.4,0.8,0.0,NaN,NaN,8.950685,True,False

In [77]:
df_to_check["Alkoholverbot_boolean"]=np.where(df_to_check["ban"]>=1,True,False)
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Buddhist_%,Folk religion_%,Other religion_%,Jewish_%,ban,LGBTQ,Sonnenstunde_pro_Tag,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15.0,NaN,0.0,...,0.0,5.7,0.0,0.0,NaN,7.91,6.502466,True,False,False
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5.0,NaN,1.0,...,0.0,1.0,0.0,0.0,NaN,27.03,6.976712,True,False,False
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10.0,NaN,1.0,...,0.0,0.0,0.0,0.0,1.0,2.86,8.531507,True,False,True
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8.0,NaN,1.0,...,0.0,0.0,0.0,0.0,1.0,1.00,8.501370,False,False,True
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1.0,NaN,0.0,...,0.0,32.9,0.0,0.0,NaN,6.83,7.784384,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,10.6,5.3,1.1,0.0,NaN,NaN,6.164384,False,False,False
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,0.6,0.2,0.8,0.0,NaN,NaN,6.994521,False,False,False
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,1.5,12.3,12.9,0.0,NaN,32.11,6.827397,False,False,False
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,0.0,0.5,0.4,0.0,NaN,NaN,7.358904,False,False,False
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,0.0,8.4,0.8,0.0,NaN,NaN,8.950685,True,False,False

In [78]:
df_to_check["Kueste_boolean"]=np.where(df_to_check['sqm/sqkm']>0,True,False)
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Folk religion_%,Other religion_%,Jewish_%,ban,LGBTQ,Sonnenstunde_pro_Tag,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15.0,NaN,0.0,...,5.7,0.0,0.0,NaN,7.91,6.502466,True,False,False,False
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5.0,NaN,1.0,...,1.0,0.0,0.0,NaN,27.03,6.976712,True,False,False,False
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10.0,NaN,1.0,...,0.0,0.0,0.0,1.0,2.86,8.531507,True,False,True,True
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8.0,NaN,1.0,...,0.0,0.0,0.0,1.0,1.00,8.501370,False,False,True,True
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1.0,NaN,0.0,...,32.9,0.0,0.0,NaN,6.83,7.784384,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,5.3,1.1,0.0,NaN,NaN,6.164384,False,False,False,True
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,0.2,0.8,0.0,NaN,NaN,6.994521,False,False,False,True
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,12.3,12.9,0.0,NaN,32.11,6.827397,False,False,False,True
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,0.5,0.4,0.0,NaN,NaN,7.358904,False,False,False,True
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,8.4,0.8,0.0,NaN,NaN,8.950685,True,False,False,True

In [79]:
df_to_check["Christian_boolean"]=np.where(df_to_check["Christian_%"]>1,True,False)
df_to_check["Muslim_boolean"]=np.where(df_to_check["Muslim_%"]>1,True,False)
df_to_check["Jewish_boolean"]=np.where(df_to_check["Jewish_%"]>1,True,False)
df_to_check

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,ban,LGBTQ,Sonnenstunde_pro_Tag,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean
0,Burundi,BDI,0.275860,20.998052,76.118642,533.078271,5.649742,15.0,NaN,0.0,...,NaN,7.91,6.502466,True,False,False,False,True,True,False
1,Central African Republic,CAF,0.925033,52.928324,57.217771,8.270604,20.120401,5.0,NaN,1.0,...,NaN,27.03,6.976712,True,False,False,False,True,True,False
2,"Yemen, Rep.",YEM,1.135994,56.455732,49.697205,74.608025,5.809719,10.0,NaN,1.0,...,1.0,2.86,8.531507,True,False,True,True,False,True,False
3,"Somalia, Fed. Rep.",SOM,1.141543,51.558951,45.166019,29.264219,NaN,8.0,NaN,1.0,...,1.0,1.00,8.501370,False,False,True,True,False,True,False
4,South Sudan,SSD,1.935740,86.340936,44.603580,18.171908,13.982581,1.0,NaN,0.0,...,NaN,6.83,7.784384,True,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,NaN,NaN,6.164384,False,False,False,True,True,False,False
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,NaN,NaN,6.994521,False,False,False,True,True,True,False
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,NaN,32.11,6.827397,False,False,False,True,True,False,False
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,NaN,NaN,7.358904,False,False,False,True,True,False,False
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,NaN,NaN,8.950685,True,False,False,True,True,True,False

In [80]:
df_to_check["English_boolean"]=np.where(df_to_check["English Proficiency"]>500,True,False)
df_to_check["Cuisine_boolean"]=np.where(df_to_check["Cuisine Rank"]>0,True,False)
df_to_check.sort_values("English Proficiency",ascending=False)

,Country Name,Country Code,gdp_rel_ger,ppp_rel_ger,cost_to_gdp,popdensity,homicides,FreedomScore,PISA Score,timediff_to_germany,...,Sonnenstunde_pro_Tag,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
107,St. Vincent and the Grenadines,VCT,20.611436,70.054706,3.398827,259.802564,51.321276,90.0,NaN,6.0,...,7.923288,True,False,False,True,True,True,False,True,False
172,United Kingdom,GBR,94.330788,112.505518,1.192670,283.106684,1.118684,92.0,494.0,1.0,...,3.949772,False,True,False,True,True,True,False,True,True
87,Fiji,FJI,11.269487,50.821620,4.509666,50.582649,2.055953,69.0,NaN,10.0,...,5.265753,False,False,False,True,True,True,False,True,False
49,Nigeria,NGA,1.446134,16.235818,11.227053,250.209103,15.746681,44.0,NaN,1.0,...,7.312548,True,False,False,True,True,True,False,True,True
50,Kenya,KEN,3.953631,43.183644,10.922527,95.268137,4.871668,51.0,NaN,1.0,...,8.301712,False,False,False,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,42.626633,NaN,NaN,98.136957,NaN,NaN,NaN,8.0,...,6.164384,False,False,False,True,True,False,False,False,False
218,New Caledonia,NCL,60.064931,NaN,NaN,15.857221,3.109821,NaN,NaN,9.0,...,6.994521,False,False,False,True,True,True,False,False,False
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,219.402076,NaN,3.0,NaN,7.0,...,6.827397,False,False,False,True,True,False,False,False,False
220,French Polynesia,PYF,40.813714,NaN,NaN,80.990493,0.371083,NaN,NaN,12.0,...,7.358904,False,False,False,True,True,False,False,False,False
221,British Virgin Islands,VGB,NaN,NaN,NaN,259.900000,8.165598,NaN,NaN,6.0,...,8.950685,True,False,False,True,True,True,False,False,False

In [81]:
df_to_check.columns

Index(['Country Name', 'Country Code', 'gdp_rel_ger', 'ppp_rel_ger',
       'cost_to_gdp', 'popdensity', 'homicides', 'FreedomScore', 'PISA Score',
       'timediff_to_germany', 'Cuisine Rank', 'SunshineHours_per_year',
       'sqm/sqkm', 'max_m', 'min_m', 'English Proficiency', 'Land', 'ISO3',
       'Anzahl_der_Deutschen_numeric', 'Bureaucracy Score', 'MaxTemperature',
       'MinTemperature', 'LivingConditions', 'Healthcare', 'CostofLiving',
       'Country', 'Christian_%', 'Muslim_%', 'Irreligion_%', 'Hindu_%',
       'Buddhist_%', 'Folk religion_%', 'Other religion_%', 'Jewish_%', 'ban',
       'LGBTQ', 'Sonnenstunde_pro_Tag', 'Mehrals5Morde_pro_100k_boolean',
       'Mehrals1000Deutsche_boolean', 'Alkoholverbot_boolean',
       'Kueste_boolean', 'Christian_boolean', 'Muslim_boolean',
       'Jewish_boolean', 'English_boolean', 'Cuisine_boolean'],
      dtype='object')

In [82]:
df_to_check_renamed=df_to_check.rename(columns={
    'gdp_rel_ger':'BIP_rel_D',
    'ppp_rel_ger':'PurchasingPower_rel_D',
    'cost_to_gdp':'Cost_BIP_Ratio',
    "popdensity":'Bevoelkerungsdichte',
    'FreedomScore':'Freedom_Score',
    'PISA Score':'PISA_Score',
    'timediff_to_germany':'Zeitunterschied_D',
    'Cuisine Rank':'Rang_Kueche',
    'max_m':'HoechsterPunkt_m',
    'min_m':'NiedrigsterPunkt_m',
    'English Proficiency':'EnglishSkill',
    'Bureaucracy Score':'BuerokratieScore',
    'MaxTemperature':'MaxTemperatur',
    'MinTemperature':'MinTemperatur'
    })

In [83]:
df_to_check_renamed_reduced_cols=df_to_check_renamed[['Country Name', 'Country Code', 'Land', 'BIP_rel_D',
       'PurchasingPower_rel_D', 'Cost_BIP_Ratio', 'Bevoelkerungsdichte',
        'Freedom_Score', 'PISA_Score','Sonnenstunde_pro_Tag', 'Zeitunterschied_D',
      'HoechsterPunkt_m', 'NiedrigsterPunkt_m',
       'BuerokratieScore', 'MaxTemperatur','MinTemperatur', 'LivingConditions', 
       'Healthcare', 'CostofLiving', 'LGBTQ', 'Mehrals5Morde_pro_100k_boolean',
       'Mehrals1000Deutsche_boolean', 'Alkoholverbot_boolean',
        'Kueste_boolean', 'Christian_boolean',
       'Muslim_boolean', 'Jewish_boolean','English_boolean', 'Cuisine_boolean']]
df_to_check_renamed_reduced_cols

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Cost_BIP_Ratio,Bevoelkerungsdichte,Freedom_Score,PISA_Score,Sonnenstunde_pro_Tag,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,NaN,0.275860,20.998052,76.118642,533.078271,15.0,NaN,6.502466,...,7.91,True,False,False,False,True,True,False,False,False
1,Central African Republic,CAF,NaN,0.925033,52.928324,57.217771,8.270604,5.0,NaN,6.976712,...,27.03,True,False,False,False,True,True,False,False,False
2,"Yemen, Rep.",YEM,NaN,1.135994,56.455732,49.697205,74.608025,10.0,NaN,8.531507,...,2.86,True,False,True,True,False,True,False,False,False
3,"Somalia, Fed. Rep.",SOM,NaN,1.141543,51.558951,45.166019,29.264219,8.0,NaN,8.501370,...,1.00,False,False,True,True,False,True,False,False,False
4,South Sudan,SSD,NaN,1.935740,86.340936,44.603580,18.171908,1.0,NaN,7.784384,...,6.83,True,False,False,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,NaN,42.626633,NaN,NaN,98.136957,NaN,NaN,6.164384,...,NaN,False,False,False,True,True,False,False,False,False
218,New Caledonia,NCL,NaN,60.064931,NaN,NaN,15.857221,NaN,NaN,6.994521,...,NaN,False,False,False,True,True,True,False,False,False
219,"Korea, Dem. People's Rep.",PRK,NaN,NaN,NaN,NaN,219.402076,3.0,NaN,6.827397,...,32.11,False,False,False,True,True,False,False,False,False
220,French Polynesia,PYF,NaN,40.813714,NaN,NaN,80.990493,NaN,NaN,7.358904,...,NaN,False,False,False,True,True,False,False,False,False
221,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,259.900000,NaN,NaN,8.950685,...,NaN,True,False,False,True,True,True,False,False,False

In [84]:
df_to_check_renamed_reduced_cols[df_to_check_renamed_reduced_cols["Land"].isna()]["Country Name"].tolist()

['Burundi',
 'Central African Republic',
 'Yemen, Rep.',
 'Somalia, Fed. Rep.',
 'South Sudan',
 'Mozambique',
 'Congo, Dem. Rep.',
 'Malawi',
 'Madagascar',
 'Niger',
 'Eritrea',
 'Sudan',
 'Afghanistan',
 'Ethiopia',
 'Solomon Islands',
 'Burkina Faso',
 'Chad',
 'Lesotho',
 'Guinea-Bissau',
 'Mali',
 'Gambia, The',
 'Vanuatu',
 'Kiribati',
 'Rwanda',
 'Zimbabwe',
 'Comoros',
 'Tanzania',
 'Micronesia, Fed. Sts.',
 'West Bank and Gaza',
 'West Bank and Gaza',
 'Benin',
 'Syrian Arab Republic',
 'Timor-Leste',
 'Papua New Guinea',
 'Nepal',
 'Myanmar',
 'Tuvalu',
 'Sao Tome and Principe',
 'Pakistan',
 'Nigeria',
 'Kenya',
 'Mauritania',
 "Cote d'Ivoire",
 'Djibouti',
 'Samoa',
 'Tonga',
 'Ghana',
 'Marshall Islands',
 'Angola',
 'Bangladesh',
 'Lao PDR',
 'Jamaica',
 'Eswatini',
 'Nauru',
 'Iraq',
 'Fiji',
 'Viet Nam',
 'Indonesia',
 'Palau',
 'Equatorial Guinea',
 'Iran, Islamic Rep.',
 'Kosovo',
 'Kosovo',
 'Kosovo',
 'Grenada',
 'St. Vincent and the Grenadines',
 'Dominica',
 'Suriname',
 'Barbados',
 'Albania',
 'North Macedonia',
 'St. Lucia',
 'Costa Rica',
 'Curacao',
 'Antigua and Barbuda',
 'St. Kitts and Nevis',
 'Turks and Caicos Islands',
 'Malaysia',
 'Oman',
 'Aruba',
 'Virgin Islands (U.S.)',
 'Puerto Rico (US)',
 'Kuwait',
 'Sint Maarten (Dutch part)',
 'Bahrain',
 'Saudi Arabia',
 'San Marino',
 'United Arab Emirates',
 'Guyana',
 'Cayman Islands',
 'Brunei Darussalam',
 'Bermuda',
 'Qatar',
 'Macao SAR, China',
 'Singapore',
 'American Samoa',
 'Channel Islands',
 'Caribbean small states',
 'Gibraltar',
 'Guam',
 'Isle of Man',
 'St. Martin (French part)',
 'Monaco',
 'Northern Mariana Islands',
 'New Caledonia',
 "Korea, Dem. People's Rep.",
 'French Polynesia',
 'British Virgin Islands']

In [85]:
english_to_german_country_names={
 'Central African Republic':"Zentralafrikanische Republik",
 'Yemen, Rep.':"Jemen",
 'Somalia, Fed. Rep.':"Somalia",
 'South Sudan':"Südsudan",
 'Mozambique':"Mosambik",
 'Congo, Dem. Rep.':"Kongo, Demokratische Republik",
 'Madagascar':"Madagaskar",
 'Ethiopia':"Äthiopien",
 'Solomon Islands':"Salomonen",
 'Gambia, The':"Gambia",
 'Rwanda':'Ruanda',
 'Zimbabwe':"Simbabwe",
 'Comoros':'Komoren',
 'Tanzania':'Tansania',
 'Micronesia, Fed. Sts.':"Mikronesien",
 'West Bank and Gaza':"Palästinensische Gebiete",
 'Syrian Arab Republic':"Syrien",
 'Timor-Leste':'Osttimor',
 'Papua New Guinea':'Papua-Neuguinea',
 'Sao Tome and Principe':"São Tomé und Príncipe",
 'Kenya':'Kenia',
 'Mauritania':"Mauretanien",
 'Djibouti':'Dschibuti',
 'Marshall Islands':'Marshallinseln',
 'Bangladesh:':'Bangladesch',
 'Lao PDR':"Laos",
 'Jamaica':'Jamaika',
 'Iraq':'Irak',
 'Fiji':"Fidschi",
 'Viet Nam':'Vietnam',
 'Indonesia':'Indonesien',
 'Equatorial Guinea':"Äquatorialguinea",
 'Iran, Islamic Rep.':"Iran",
 'Kosovo':"Kosovo",
 'St. Vincent and the Grenadines':"St. Vincent und die Grenadinen",
 'Dominica':"Dominica",
 'Albania':"Albanien",
 'North Macedonia':"Nordmazedonien",
 'Antigua and Barbuda':"Antigua und Barbuda",
 'St. Kitts and Nevis':"St. Kitts und Nevis",
 'Turks and Caicos Islands':"Turks- und Caicosinseln",
 'Malaysia':'Malaysia',
 'Sint Maarten (Dutch part)':"Sint Maarten",
 'Saudi Arabia':"Saudi-Arabien",
 'United Arab Emirates':"Vereinigte Arabische Emirate",
 'Cayman Islands':"Caymaninseln",
 'Qatar':"Katar",
 'Singapore':'Singapur',
 'American Samoa':"Amerikanisch-Samoa",
 'St. Martin (French part)':"Saint-Martin",
 'Northern Mariana Islands':"Nördliche Marianen",
 'New Caledonia':'Neukaledonien',
 "Korea, Dem. People's Rep.":"Nordkorea",
 'French Polynesia': "Französisch-Polynesien",
 'British Virgin Islands':"Britische Jungferninseln"}

In [86]:
df_to_check_renamed_reduced_cols["Land"]=np.where(df_to_check_renamed_reduced_cols["Land"].isna(),df_to_check_renamed_reduced_cols["Country Name"],df_to_check_renamed_reduced_cols["Land"])
df_to_check_renamed_reduced_cols

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_33213/4293752334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_to_check_renamed_reduced_cols["Land"]=np.where(df_to_check_renamed_reduced_cols["Land"].isna(),df_to_check_renamed_reduced_cols["Country Name"],df_to_check_renamed_reduced_cols["Land"])

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Cost_BIP_Ratio,Bevoelkerungsdichte,Freedom_Score,PISA_Score,Sonnenstunde_pro_Tag,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,Burundi,0.275860,20.998052,76.118642,533.078271,15.0,NaN,6.502466,...,7.91,True,False,False,False,True,True,False,False,False
1,Central African Republic,CAF,Central African Republic,0.925033,52.928324,57.217771,8.270604,5.0,NaN,6.976712,...,27.03,True,False,False,False,True,True,False,False,False
2,"Yemen, Rep.",YEM,"Yemen, Rep.",1.135994,56.455732,49.697205,74.608025,10.0,NaN,8.531507,...,2.86,True,False,True,True,False,True,False,False,False
3,"Somalia, Fed. Rep.",SOM,"Somalia, Fed. Rep.",1.141543,51.558951,45.166019,29.264219,8.0,NaN,8.501370,...,1.00,False,False,True,True,False,True,False,False,False
4,South Sudan,SSD,South Sudan,1.935740,86.340936,44.603580,18.171908,1.0,NaN,7.784384,...,6.83,True,False,False,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,Northern Mariana Islands,42.626633,NaN,NaN,98.136957,NaN,NaN,6.164384,...,NaN,False,False,False,True,True,False,False,False,False
218,New Caledonia,NCL,New Caledonia,60.064931,NaN,NaN,15.857221,NaN,NaN,6.994521,...,NaN,False,False,False,True,True,True,False,False,False
219,"Korea, Dem. People's Rep.",PRK,"Korea, Dem. People's Rep.",NaN,NaN,NaN,219.402076,3.0,NaN,6.827397,...,32.11,False,False,False,True,True,False,False,False,False
220,French Polynesia,PYF,French Polynesia,40.813714,NaN,NaN,80.990493,NaN,NaN,7.358904,...,NaN,False,False,False,True,True,False,False,False,False
221,British Virgin Islands,VGB,British Virgin Islands,NaN,NaN,NaN,259.900000,NaN,NaN,8.950685,...,NaN,True,False,False,True,True,True,False,False,False

In [87]:
df_to_check_renamed_reduced_cols['Land']=df_to_check_renamed_reduced_cols['Land'].replace(english_to_german_country_names)
df_to_check_renamed_reduced_cols

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_33213/1982716575.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_to_check_renamed_reduced_cols['Land']=df_to_check_renamed_reduced_cols['Land'].replace(english_to_german_country_names)

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Cost_BIP_Ratio,Bevoelkerungsdichte,Freedom_Score,PISA_Score,Sonnenstunde_pro_Tag,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,Burundi,0.275860,20.998052,76.118642,533.078271,15.0,NaN,6.502466,...,7.91,True,False,False,False,True,True,False,False,False
1,Central African Republic,CAF,Zentralafrikanische Republik,0.925033,52.928324,57.217771,8.270604,5.0,NaN,6.976712,...,27.03,True,False,False,False,True,True,False,False,False
2,"Yemen, Rep.",YEM,Jemen,1.135994,56.455732,49.697205,74.608025,10.0,NaN,8.531507,...,2.86,True,False,True,True,False,True,False,False,False
3,"Somalia, Fed. Rep.",SOM,Somalia,1.141543,51.558951,45.166019,29.264219,8.0,NaN,8.501370,...,1.00,False,False,True,True,False,True,False,False,False
4,South Sudan,SSD,Südsudan,1.935740,86.340936,44.603580,18.171908,1.0,NaN,7.784384,...,6.83,True,False,False,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,Nördliche Marianen,42.626633,NaN,NaN,98.136957,NaN,NaN,6.164384,...,NaN,False,False,False,True,True,False,False,False,False
218,New Caledonia,NCL,Neukaledonien,60.064931,NaN,NaN,15.857221,NaN,NaN,6.994521,...,NaN,False,False,False,True,True,True,False,False,False
219,"Korea, Dem. People's Rep.",PRK,Nordkorea,NaN,NaN,NaN,219.402076,3.0,NaN,6.827397,...,32.11,False,False,False,True,True,False,False,False,False
220,French Polynesia,PYF,Französisch-Polynesien,40.813714,NaN,NaN,80.990493,NaN,NaN,7.358904,...,NaN,False,False,False,True,True,False,False,False,False
221,British Virgin Islands,VGB,Britische Jungferninseln,NaN,NaN,NaN,259.900000,NaN,NaN,8.950685,...,NaN,True,False,False,True,True,True,False,False,False

In [88]:
reisewarnungen_full=pd.read_csv("../newdata/reisewarnungen_full.csv")
reisewarnungen_full_list=reisewarnungen_full["0"].tolist()
reisewarnungen_full_list

['Afghanistan',
 'Belarus',
 'Haiti',
 'Iran',
 'Jemen',
 'Libyen',
 'Mali',
 'Myanmar',
 'Niger',
 'Palästinensische Gebiete',
 'Somalia',
 'Sudan',
 'Südsudan',
 'Syrien',
 'Ukraine',
 'Zentralafrikanische Republik']

In [89]:
safe_countries=df_to_check_renamed_reduced_cols[~df_to_check_renamed_reduced_cols["Land"].isin(reisewarnungen_full_list)]
safe_countries

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Cost_BIP_Ratio,Bevoelkerungsdichte,Freedom_Score,PISA_Score,Sonnenstunde_pro_Tag,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,Burundi,0.275860,20.998052,76.118642,533.078271,15.0,NaN,6.502466,...,7.91,True,False,False,False,True,True,False,False,False
5,Mozambique,MOZ,Mosambik,1.160006,49.343009,42.536863,42.772146,41.0,NaN,7.775342,...,48.21,False,False,False,True,True,True,False,False,False
6,"Congo, Dem. Rep.",COD,"Kongo, Demokratische Republik",1.160274,49.064988,42.287398,46.664048,18.0,NaN,6.095890,...,32.09,False,False,False,True,True,True,False,False,False
7,Malawi,MWI,Malawi,0.911056,35.424203,38.882573,223.848982,65.0,NaN,7.659909,...,12.09,False,False,False,False,True,True,False,True,False
8,Madagascar,MDG,Madagaskar,0.976694,37.490671,38.385285,53.619684,55.0,NaN,7.847763,...,40.00,False,False,False,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Northern Mariana Islands,MNP,Nördliche Marianen,42.626633,NaN,NaN,98.136957,NaN,NaN,6.164384,...,NaN,False,False,False,True,True,False,False,False,False
218,New Caledonia,NCL,Neukaledonien,60.064931,NaN,NaN,15.857221,NaN,NaN,6.994521,...,NaN,False,False,False,True,True,True,False,False,False
219,"Korea, Dem. People's Rep.",PRK,Nordkorea,NaN,NaN,NaN,219.402076,3.0,NaN,6.827397,...,32.11,False,False,False,True,True,False,False,False,False
220,French Polynesia,PYF,Französisch-Polynesien,40.813714,NaN,NaN,80.990493,NaN,NaN,7.358904,...,NaN,False,False,False,True,True,False,False,False,False
221,British Virgin Islands,VGB,Britische Jungferninseln,NaN,NaN,NaN,259.900000,NaN,NaN,8.950685,...,NaN,True,False,False,True,True,True,False,False,False

In [90]:
safe_countries.Land.isna().sum()

np.int64(0)

In [91]:
safe_countries.columns

Index(['Country Name', 'Country Code', 'Land', 'BIP_rel_D',
       'PurchasingPower_rel_D', 'Cost_BIP_Ratio', 'Bevoelkerungsdichte',
       'Freedom_Score', 'PISA_Score', 'Sonnenstunde_pro_Tag',
       'Zeitunterschied_D', 'HoechsterPunkt_m', 'NiedrigsterPunkt_m',
       'BuerokratieScore', 'MaxTemperatur', 'MinTemperatur',
       'LivingConditions', 'Healthcare', 'CostofLiving', 'LGBTQ',
       'Mehrals5Morde_pro_100k_boolean', 'Mehrals1000Deutsche_boolean',
       'Alkoholverbot_boolean', 'Kueste_boolean', 'Christian_boolean',
       'Muslim_boolean', 'Jewish_boolean', 'English_boolean',
       'Cuisine_boolean'],
      dtype='object')

In [98]:
safe_countries_enough_data_thresh28=safe_countries.dropna(thresh=28).copy()
safe_countries_enough_data_thresh29=safe_countries.dropna(thresh=29).copy()

In [100]:
list1=safe_countries_enough_data_thresh28["Country Name"].tolist()
list2=safe_countries_enough_data_thresh29["Country Name"].tolist()
difference = list(set(list1) - set(list2))
difference

['Namibia',
 'Trinidad and Tobago',
 'Nepal',
 'Honduras',
 'Lebanon',
 'Bahrain',
 'Pakistan',
 'Belize',
 'Congo, Dem. Rep.',
 'Guinea-Bissau',
 'Sierra Leone',
 'Guyana',
 'Venezuela, RB',
 'Algeria',
 'Mauritania',
 'Botswana',
 'Senegal',
 'Burkina Faso',
 'Lesotho',
 'India',
 'Lao PDR',
 "Cote d'Ivoire",
 'Tajikistan',
 'Cabo Verde',
 'Papua New Guinea',
 'Iraq',
 'Gabon',
 'Mozambique',
 'Mauritius',
 'Bosnia and Herzegovina',
 'Malawi',
 'Kuwait',
 'Armenia',
 'Bangladesh',
 'Ghana',
 'Oman',
 'Sao Tome and Principe',
 'Tunisia',
 'Ethiopia',
 'China',
 'Zimbabwe',
 'Kyrgyz Republic',
 'Djibouti',
 'Eswatini',
 'Seychelles',
 'Uganda',
 'South Africa',
 'Nicaragua',
 'Togo',
 'Madagascar',
 'Nigeria',
 'Luxembourg',
 'Sri Lanka',
 'Angola',
 'Tanzania',
 'Egypt, Arab Rep.',
 'Rwanda',
 'Equatorial Guinea',
 'Kenya',
 'Zambia',
 'Turkmenistan',
 'Burundi',
 'Cameroon',
 'Gambia, The',
 'Russian Federation',
 'Bolivia',
 'Guinea',
 'Suriname',
 'Comoros',
 'Eritrea',
 'Benin',
 'Congo, Rep.',
 'Ecuador',
 'Liberia',
 'Chad']

In [101]:
safe_countries_enough_data[safe_countries_enough_data["Country Name"].isin(difference)]

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Cost_BIP_Ratio,Bevoelkerungsdichte,Freedom_Score,PISA_Score,Sonnenstunde_pro_Tag,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,Burundi,0.275860,20.998052,76.118642,533.078271,15.0,NaN,6.502466,...,7.91,True,False,False,False,True,True,False,False,False
5,Mozambique,MOZ,Mosambik,1.160006,49.343009,42.536863,42.772146,41.0,NaN,7.775342,...,48.21,False,False,False,True,True,True,False,False,False
6,"Congo, Dem. Rep.",COD,"Kongo, Demokratische Republik",1.160274,49.064988,42.287398,46.664048,18.0,NaN,6.095890,...,32.09,False,False,False,True,True,True,False,False,False
7,Malawi,MWI,Malawi,0.911056,35.424203,38.882573,223.848982,65.0,NaN,7.659909,...,12.09,False,False,False,False,True,True,False,True,False
8,Madagascar,MDG,Madagaskar,0.976694,37.490671,38.385285,53.619684,55.0,NaN,7.847763,...,40.00,False,False,False,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Russian Federation,RUS,Russland,26.682724,40.695404,1.525159,8.782272,12.0,NaN,5.404897,...,31.55,True,True,False,True,True,True,False,True,True
161,Kuwait,KWT,Kuwait,57.730709,80.833923,1.400189,272.358025,31.0,NaN,8.227397,...,5.64,False,False,True,True,True,True,False,False,False
178,Bahrain,BHR,Bahrain,53.849641,57.927068,1.075719,1971.323750,12.0,NaN,9.189041,...,31.11,False,False,False,True,True,True,False,False,False
194,Guyana,GUY,Guyana,53.554689,48.457223,0.904818,3.913768,74.0,NaN,6.741370,...,25.80,True,False,False,True,True,True,False,True,False
206,Luxembourg,LUX,Luxemburg,246.444528,118.177955,0.479532,258.862053,97.0,NaN,4.476712,...,80.80,False,True,False,False,True,True,False,True,False

In [97]:
safe_countries_enough_data=safe_countries.dropna(thresh=28).copy()
safe_countries_enough_data

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Cost_BIP_Ratio,Bevoelkerungsdichte,Freedom_Score,PISA_Score,Sonnenstunde_pro_Tag,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,Burundi,0.275860,20.998052,76.118642,533.078271,15.0,NaN,6.502466,...,7.91,True,False,False,False,True,True,False,False,False
5,Mozambique,MOZ,Mosambik,1.160006,49.343009,42.536863,42.772146,41.0,NaN,7.775342,...,48.21,False,False,False,True,True,True,False,False,False
6,"Congo, Dem. Rep.",COD,"Kongo, Demokratische Republik",1.160274,49.064988,42.287398,46.664048,18.0,NaN,6.095890,...,32.09,False,False,False,True,True,True,False,False,False
7,Malawi,MWI,Malawi,0.911056,35.424203,38.882573,223.848982,65.0,NaN,7.659909,...,12.09,False,False,False,False,True,True,False,True,False
8,Madagascar,MDG,Madagaskar,0.976694,37.490671,38.385285,53.619684,55.0,NaN,7.847763,...,40.00,False,False,False,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Norway,NOR,Norwegen,155.572371,111.330540,0.715619,15.152480,99.0,474.0,3.762557,...,86.82,False,True,False,True,True,True,False,True,True
202,Qatar,QAT,Katar,136.694637,78.368331,0.573309,231.160313,25.0,422.0,7.898630,...,4.39,False,False,False,True,True,True,False,False,True
204,Ireland,IRL,Irland,192.322429,106.002847,0.551173,77.044564,97.0,504.0,3.980822,...,85.00,False,True,False,True,True,True,False,True,True
205,Singapore,SGP,Singapur,162.497688,77.965737,0.479796,8241.849582,48.0,560.0,5.540822,...,44.29,False,False,False,True,True,True,False,True,True
206,Luxembourg,LUX,Luxemburg,246.444528,118.177955,0.479532,258.862053,97.0,NaN,4.476712,...,80.80,False,True,False,False,True,True,False,True,False

In [102]:
safe_countries_enough_data_red=safe_countries_enough_data.drop(columns=["Cost_BIP_Ratio",'PISA_Score'])

In [103]:
safe_countries_enough_data_red[safe_countries_enough_data_red.columns[2:]] = safe_countries_enough_data_red[safe_countries_enough_data_red.columns[2:]].round(1)
safe_countries_enough_data_red

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Bevoelkerungsdichte,Freedom_Score,Sonnenstunde_pro_Tag,Zeitunterschied_D,HoechsterPunkt_m,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,Burundi,0.3,21.0,533.1,15.0,6.5,0.0,2684.0,...,7.9,True,False,False,False,True,True,False,False,False
5,Mozambique,MOZ,Mosambik,1.2,49.3,42.8,41.0,7.8,0.0,2440.0,...,48.2,False,False,False,True,True,True,False,False,False
6,"Congo, Dem. Rep.",COD,"Kongo, Demokratische Republik",1.2,49.1,46.7,18.0,6.1,1.0,5109.0,...,32.1,False,False,False,True,True,True,False,False,False
7,Malawi,MWI,Malawi,0.9,35.4,223.8,65.0,7.7,0.0,3002.0,...,12.1,False,False,False,False,True,True,False,True,False
8,Madagascar,MDG,Madagaskar,1.0,37.5,53.6,55.0,7.8,1.0,2876.0,...,40.0,False,False,False,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Norway,NOR,Norwegen,155.6,111.3,15.2,99.0,3.8,0.0,2469.0,...,86.8,False,True,False,True,True,True,False,True,True
202,Qatar,QAT,Katar,136.7,78.4,231.2,25.0,7.9,1.0,103.0,...,4.4,False,False,False,True,True,True,False,False,True
204,Ireland,IRL,Irland,192.3,106.0,77.0,97.0,4.0,1.0,1039.0,...,85.0,False,True,False,True,True,True,False,True,True
205,Singapore,SGP,Singapur,162.5,78.0,8241.8,48.0,5.5,6.0,164.0,...,44.3,False,False,False,True,True,True,False,True,True
206,Luxembourg,LUX,Luxemburg,246.4,118.2,258.9,97.0,4.5,0.0,560.0,...,80.8,False,True,False,False,True,True,False,True,False

In [106]:
safe_countries_enough_data_red.columns

Index(['Country Name', 'Country Code', 'Land', 'BIP_rel_D',
       'PurchasingPower_rel_D', 'Bevoelkerungsdichte', 'Freedom_Score',
       'Sonnenstunde_pro_Tag', 'Zeitunterschied_D', 'HoechsterPunkt_m',
       'NiedrigsterPunkt_m', 'BuerokratieScore', 'MaxTemperatur',
       'MinTemperatur', 'LivingConditions', 'Healthcare', 'CostofLiving',
       'LGBTQ', 'Mehrals5Morde_pro_100k_boolean',
       'Mehrals1000Deutsche_boolean', 'Alkoholverbot_boolean',
       'Kueste_boolean', 'Christian_boolean', 'Muslim_boolean',
       'Jewish_boolean', 'English_boolean', 'Cuisine_boolean'],
      dtype='object')

In [107]:
safe_countries_enough_data_red

,Country Name,Country Code,Land,BIP_rel_D,PurchasingPower_rel_D,Bevoelkerungsdichte,Freedom_Score,Sonnenstunde_pro_Tag,Zeitunterschied_D,HoechsterPunkt_m,...,LGBTQ,Mehrals5Morde_pro_100k_boolean,Mehrals1000Deutsche_boolean,Alkoholverbot_boolean,Kueste_boolean,Christian_boolean,Muslim_boolean,Jewish_boolean,English_boolean,Cuisine_boolean
0,Burundi,BDI,Burundi,0.3,21.0,533.1,15.0,6.5,0.0,2684.0,...,7.9,True,False,False,False,True,True,False,False,False
5,Mozambique,MOZ,Mosambik,1.2,49.3,42.8,41.0,7.8,0.0,2440.0,...,48.2,False,False,False,True,True,True,False,False,False
6,"Congo, Dem. Rep.",COD,"Kongo, Demokratische Republik",1.2,49.1,46.7,18.0,6.1,1.0,5109.0,...,32.1,False,False,False,True,True,True,False,False,False
7,Malawi,MWI,Malawi,0.9,35.4,223.8,65.0,7.7,0.0,3002.0,...,12.1,False,False,False,False,True,True,False,True,False
8,Madagascar,MDG,Madagaskar,1.0,37.5,53.6,55.0,7.8,1.0,2876.0,...,40.0,False,False,False,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Norway,NOR,Norwegen,155.6,111.3,15.2,99.0,3.8,0.0,2469.0,...,86.8,False,True,False,True,True,True,False,True,True
202,Qatar,QAT,Katar,136.7,78.4,231.2,25.0,7.9,1.0,103.0,...,4.4,False,False,False,True,True,True,False,False,True
204,Ireland,IRL,Irland,192.3,106.0,77.0,97.0,4.0,1.0,1039.0,...,85.0,False,True,False,True,True,True,False,True,True
205,Singapore,SGP,Singapur,162.5,78.0,8241.8,48.0,5.5,6.0,164.0,...,44.3,False,False,False,True,True,True,False,True,True
206,Luxembourg,LUX,Luxemburg,246.4,118.2,258.9,97.0,4.5,0.0,560.0,...,80.8,False,True,False,False,True,True,False,True,False

In [108]:
safe_countries_enough_data_red.to_csv("../newdata/named_cleaned_data.csv", index=False)

In [33]:
"""datatype_dict={'Country Name':str, 'Country Code':str, 'Land':str, 'BIP_rel_D':float,
       'PurchasingPower_rel_D':float, 'Cost_BIP_Ratio':float, 'Bevoelkerungsdichte':float,
       'Freedom_Score':'Int64', 'PISA_Score':'Int64', 'Sonnenstunde_pro_Tag':float,
       'Zeitunterschied_D':'Int64', 'Rang_Kueche':'Int64', 'HoechsterPunkt_m':'Int64',
       'NiedrigsterPunkt_m':'Int64', 'EnglishSkill':'Int64', 'BuerokratieScore':float,
       'MaxTemperatur':float, 'MinTemperatur':float, 'LivingConditions':'Int64', 'Healthcare':'Int64',
       'CostofLiving':'Int64', 'LGBTQ':float, 'Mehrals5Morde_pro_100k_boolean':bool,
       'Mehrals1000Deutsche_boolean':bool, 'Alkoholverbot_boolean':bool,
       'Kueste_boolean':bool, 'Christian_boolean':bool, 'Muslim_boolean':bool,
       'Jewish_boolean':bool}

# Make sure we're working with a copy
safe_countries_enough_data = safe_countries_enough_data.copy()
safe_countries_enough_data = safe_countries_enough_data.astype(datatype_dict, errors = 'ignore')
safe_countries_enough_data.dtypes"""

"datatype_dict={'Country Name':str, 'Country Code':str, 'Land':str, 'BIP_rel_D':float,\n       'PurchasingPower_rel_D':float, 'Cost_BIP_Ratio':float, 'Bevoelkerungsdichte':float,\n       'Freedom_Score':'Int64', 'PISA_Score':'Int64', 'Sonnenstunde_pro_Tag':float,\n       'Zeitunterschied_D':'Int64', 'Rang_Kueche':'Int64', 'HoechsterPunkt_m':'Int64',\n       'NiedrigsterPunkt_m':'Int64', 'EnglishSkill':'Int64', 'BuerokratieScore':float,\n       'MaxTemperatur':float, 'MinTemperatur':float, 'LivingConditions':'Int64', 'Healthcare':'Int64',\n       'CostofLiving':'Int64', 'LGBTQ':float, 'Mehrals5Morde_pro_100k_boolean':bool,\n       'Mehrals1000Deutsche_boolean':bool, 'Alkoholverbot_boolean':bool,\n       'Kueste_boolean':bool, 'Christian_boolean':bool, 'Muslim_boolean':bool,\n       'Jewish_boolean':bool}\n\n# Make sure we're working with a copy\nsafe_countries_enough_data = safe_countries_enough_data.copy()\nsafe_countries_enough_data = safe_countries_enough_data.astype(datatype_dict, errors = 'ignore')\nsafe_countries_enough_data.dtypes"