In [1]:
import pandas as pd
import requests
import numpy as np
from bs4 import BeautifulSoup
import yfinance
import os
from decimal import Decimal, ROUND_HALF_UP
import locale
from datetime import datetime, timedelta
import json
import time
import io
#https://github.com/patrickloeber/python-github-action-template?tab=readme-ov-file
# Set the locale to English (United States)
locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
#authorization

'en_US.UTF-8'

In [4]:

# Get today's date
end_of_year = "2025-12-31"
end_of_year = datetime.strptime(end_of_year, "%Y-%m-%d")
# Get date 365 days ago
date_365_days_ago = end_of_year - timedelta(days=365)

# Format as string if needed
date_365_days_ago_str = date_365_days_ago.strftime("%Y-%m-%d")

print(date_365_days_ago_str)

2024-12-31

In [24]:
msci_world = yfinance.download (tickers = "^990100-USD-STRD", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
                              interval = "1d")
msci_world

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/3152003485.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  msci_world = yfinance.download (tickers = "^990100-USD-STRD", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,^990100-USD-STRD,^990100-USD-STRD,^990100-USD-STRD,^990100-USD-STRD,^990100-USD-STRD
Date,,,,,
2024-12-31,3707.800049,3732.100098,3701.600098,3720.899902,0
2025-01-02,3702.699951,3733.800049,3682.800049,3707.500000,0
2025-01-03,3737.500000,3741.899902,3700.699951,3702.100098,0
2025-01-06,3763.199951,3785.000000,3736.100098,3738.600098,0
2025-01-07,3733.600098,3780.300049,3723.399902,3763.500000,0
...,...,...,...,...,...
2025-12-23,4464.000000,4465.799805,4442.799805,4442.799805,0
2025-12-24,4474.200195,4476.799805,4462.000000,4466.000000,0
2025-12-26,4473.200195,4480.600098,4468.600098,4474.600098,0
2025-12-29,4461.200195,4474.200195,4452.299805,4472.600098,0
2025-12-30,4458.299805,4468.100098,4456.299805,4461.299805,0

In [25]:
emerging_markets = yfinance.download (tickers = "EEM", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
                              interval = "1d")
emerging_markets

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/3791202752.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  emerging_markets = yfinance.download (tickers = "EEM", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker            EEM        EEM        EEM        EEM       EEM
Date
2024-12-31  40.834389  41.049205  40.805097  40.951560  40524000
2025-01-02  40.775803  41.000385  40.697690  40.883211  25287200
2025-01-03  41.156612  41.195667  40.971088  41.098025  17706000
2025-01-06  41.303078  41.722944  41.283549  41.596007  26200900
2025-01-07  41.010147  41.469071  40.971089  41.459305  30912500
...               ...        ...        ...        ...       ...
2025-12-23  54.310001  54.330002  53.900002  53.990002  25319700
2025-12-24  54.419998  54.459999  54.340000  54.410000   9565300
2025-12-26  54.799999  54.820000  54.529999  54.570000  11352000
2025-12-29  54.660000  54.680000  54.430000  54.520000  18816700
2025-12-30  54.880001  54.990002  54.810001  54.869999  24643000

[250 rows x 5 columns]

In [26]:
europe_markets = yfinance.download (tickers = "EMUU.L", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
                              interval = "1d")
europe_markets

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/3964065752.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  europe_markets = yfinance.download (tickers = "EMUU.L", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
[*********************100%***********************]  1 of 1 completed

Price        Close    High      Low    Open  Volume
Ticker      EMUU.L  EMUU.L   EMUU.L  EMUU.L  EMUU.L
Date
2024-12-31  10.417  10.338  10.2840  10.284    8930
2025-01-02  10.460  10.456  10.3860  10.440   36374
2025-01-03  10.380  10.450  10.3700  10.446  115722
2025-01-06  10.594  10.594  10.4620  10.546    6015
2025-01-07  10.639  10.654  10.5900  10.606   13469
...            ...     ...      ...     ...     ...
2025-12-22  13.032  13.034  12.9980  13.030    8863
2025-12-23  13.029  13.050  12.9920  13.010    5507
2025-12-24  13.066  13.066  13.0640  13.066    2599
2025-12-29  13.056  13.086  13.0035  13.086   20286
2025-12-30  13.179  13.166  13.1180  13.118    7154

[253 rows x 5 columns]

In [27]:

eafe_markets = yfinance.download (tickers = "EFA", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
                              interval = "1d")
eafe_markets

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/2300636686.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  eafe_markets = yfinance.download (tickers = "EFA", start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker            EFA        EFA        EFA        EFA       EFA
Date
2024-12-31  73.000061  73.357292  72.835931  73.241431  21393500
2025-01-02  72.749039  73.251093  72.546288  73.086956  12756600
2025-01-03  73.067650  73.125576  72.642836  72.922826  12548800
2025-01-06  73.762794  74.235878  73.617971  73.695211  16201800
2025-01-07  73.704857  74.400005  73.598661  74.400005   9393200
...               ...        ...        ...        ...       ...
2025-12-23  96.290001  96.440002  96.169998  96.279999  16485700
2025-12-24  96.410004  96.459999  96.190002  96.330002   5609700
2025-12-26  96.570000  96.599998  96.339996  96.529999   9304200
2025-12-29  96.279999  96.470001  96.059998  96.260002  16705400
2025-12-30  96.440002  96.800003  96.419998  96.629997  15877000

[250 rows x 5 columns]

In [28]:
def reduce_index(df,indexname):
    index_red=pd.DataFrame()
    df["Date"]=df.index
    index_red["Date"]=df["Date"]

    index_red[indexname]=df[df.columns[0]]

    index_red=index_red.reset_index(drop=True)
    return index_red

In [29]:
europe_markets_red=reduce_index(europe_markets,"EUROPE_MARKETS")
msci_world_red=reduce_index(msci_world,"MSCI_WORLD")
emerging_markets_red=reduce_index(emerging_markets,"EMERGING_MARKETS")
eafe_markets_red=reduce_index(eafe_markets,"EAFE_MARKETS")

europe_markets_red

          Date  EUROPE_MARKETS
0   2024-12-31          10.417
1   2025-01-02          10.460
2   2025-01-03          10.380
3   2025-01-06          10.594
4   2025-01-07          10.639
..         ...             ...
248 2025-12-22          13.032
249 2025-12-23          13.029
250 2025-12-24          13.066
251 2025-12-29          13.056
252 2025-12-30          13.179

[253 rows x 2 columns]

In [30]:
world_emerging=pd.merge(msci_world_red, emerging_markets_red, on="Date", how="outer")
world_emerging=world_emerging.fillna(method="ffill")
world_emerging

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/34355924.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  world_emerging=world_emerging.fillna(method="ffill")

          Date   MSCI_WORLD  EMERGING_MARKETS
0   2024-12-31  3707.800049         40.834389
1   2025-01-02  3702.699951         40.775803
2   2025-01-03  3737.500000         41.156612
3   2025-01-06  3763.199951         41.303078
4   2025-01-07  3733.600098         41.010147
..         ...          ...               ...
249 2025-12-23  4464.000000         54.310001
250 2025-12-24  4474.200195         54.419998
251 2025-12-26  4473.200195         54.799999
252 2025-12-29  4461.200195         54.660000
253 2025-12-30  4458.299805         54.880001

[254 rows x 3 columns]

In [31]:
world_emerging_europe=pd.merge(world_emerging, europe_markets_red, on="Date", how="outer")
world_emerging_europe=world_emerging_europe.fillna(method="ffill")

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/2752512718.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  world_emerging_europe=world_emerging_europe.fillna(method="ffill")

In [32]:
world_emerging_europe_eafe=pd.merge(world_emerging_europe, eafe_markets_red, on="Date", how="outer")
world_emerging_europe_eafe=world_emerging_europe_eafe.fillna(method="ffill")
today_str=end_of_year.strftime("%Y-%m-%d")

world_emerging_europe_eafe_without_today=world_emerging_europe_eafe[world_emerging_europe_eafe["Date"]!=today_str]
world_emerging_europe_eafe_without_today=world_emerging_europe_eafe_without_today.dropna()
world_emerging_europe_eafe_without_today

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/3520075149.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  world_emerging_europe_eafe=world_emerging_europe_eafe.fillna(method="ffill")

          Date   MSCI_WORLD  EMERGING_MARKETS  EUROPE_MARKETS  EAFE_MARKETS
0   2024-12-31  3707.800049         40.834389          10.417     73.000061
1   2025-01-02  3702.699951         40.775803          10.460     72.749039
2   2025-01-03  3737.500000         41.156612          10.380     73.067650
3   2025-01-06  3763.199951         41.303078          10.594     73.762794
4   2025-01-07  3733.600098         41.010147          10.639     73.704857
..         ...          ...               ...             ...           ...
253 2025-12-23  4464.000000         54.310001          13.029     96.290001
254 2025-12-24  4474.200195         54.419998          13.066     96.410004
255 2025-12-26  4473.200195         54.799999          13.066     96.570000
256 2025-12-29  4461.200195         54.660000          13.056     96.279999
257 2025-12-30  4458.299805         54.880001          13.179     96.440002

[258 rows x 5 columns]

In [33]:
for col in world_emerging_europe_eafe_without_today.columns[1:]:
    world_emerging_europe_eafe_without_today[col]= world_emerging_europe_eafe_without_today[col].apply(lambda x: Decimal(str(x)))

    # Example: Perform precise rounding on the Decimal column
    world_emerging_europe_eafe_without_today[col]= world_emerging_europe_eafe_without_today[col].apply(lambda x: x.quantize(Decimal('1'), rounding=ROUND_HALF_UP))
world_emerging_europe_eafe_without_today

          Date MSCI_WORLD EMERGING_MARKETS EUROPE_MARKETS EAFE_MARKETS
0   2024-12-31       3708               41             10           73
1   2025-01-02       3703               41             10           73
2   2025-01-03       3738               41             10           73
3   2025-01-06       3763               41             11           74
4   2025-01-07       3734               41             11           74
..         ...        ...              ...            ...          ...
253 2025-12-23       4464               54             13           96
254 2025-12-24       4474               54             13           96
255 2025-12-26       4473               55             13           97
256 2025-12-29       4461               55             13           96
257 2025-12-30       4458               55             13           96

[258 rows x 5 columns]

In [34]:
def converter_perc(index_name):
    df_perc=pd.DataFrame()
    df_perc["Date"]=world_emerging_europe_eafe_without_today["Date"]
    col_important=world_emerging_europe_eafe_without_today[index_name]
    base_value=col_important.iloc[0]
    df_perc[index_name+"_perc"]=(col_important-base_value)*100/base_value
    df_perc[index_name+"_perc"] = df_perc[index_name+"_perc"].apply(lambda x: float(Decimal(str(x)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)))

    return(df_perc)

In [35]:
world_emerging_europe_eafe_without_today

          Date MSCI_WORLD EMERGING_MARKETS EUROPE_MARKETS EAFE_MARKETS
0   2024-12-31       3708               41             10           73
1   2025-01-02       3703               41             10           73
2   2025-01-03       3738               41             10           73
3   2025-01-06       3763               41             11           74
4   2025-01-07       3734               41             11           74
..         ...        ...              ...            ...          ...
253 2025-12-23       4464               54             13           96
254 2025-12-24       4474               54             13           96
255 2025-12-26       4473               55             13           97
256 2025-12-29       4461               55             13           96
257 2025-12-30       4458               55             13           96

[258 rows x 5 columns]

In [36]:
for col in world_emerging_europe_eafe_without_today.columns[1:]:
    print(col)
    df_perc=converter_perc(col)
    print(df_perc)
    world_emerging_europe_eafe_without_today=pd.merge(world_emerging_europe_eafe_without_today,df_perc,on="Date",how="outer")
world_emerging_europe_eafe_without_today

MSCI_WORLD
          Date  MSCI_WORLD_perc
0   2024-12-31             0.00
1   2025-01-02            -0.13
2   2025-01-03             0.81
3   2025-01-06             1.48
4   2025-01-07             0.70
..         ...              ...
253 2025-12-23            20.39
254 2025-12-24            20.66
255 2025-12-26            20.63
256 2025-12-29            20.31
257 2025-12-30            20.23

[258 rows x 2 columns]
EMERGING_MARKETS
          Date  EMERGING_MARKETS_perc
0   2024-12-31                   0.00
1   2025-01-02                   0.00
2   2025-01-03                   0.00
3   2025-01-06                   0.00
4   2025-01-07                   0.00
..         ...                    ...
253 2025-12-23                  31.71
254 2025-12-24                  31.71
255 2025-12-26                  34.15
256 2025-12-29                  34.15
257 2025-12-30                  34.15

[258 rows x 2 columns]
EUROPE_MARKETS
          Date  EUROPE_MARKETS_perc
0   2024-12-31                  0.0
1   2025-01-02                  0.0
2   2025-01-03                  0.0
3   2025-01-06                 10.0
4   2025-01-07                 10.0
..         ...                  ...
253 2025-12-23                 30.0
254 2025-12-24                 30.0
255 2025-12-26                 30.0
256 2025-12-29                 30.0
257 2025-12-30                 30.0

[258 rows x 2 columns]
EAFE_MARKETS
          Date  EAFE_MARKETS_perc
0   2024-12-31               0.00
1   2025-01-02               0.00
2   2025-01-03               0.00
3   2025-01-06               1.37
4   2025-01-07               1.37
..         ...                ...
253 2025-12-23              31.51
254 2025-12-24              31.51
255 2025-12-26              32.88
256 2025-12-29              31.51
257 2025-12-30              31.51

[258 rows x 2 columns]

,Date,MSCI_WORLD,EMERGING_MARKETS,EUROPE_MARKETS,EAFE_MARKETS,MSCI_WORLD_perc,EMERGING_MARKETS_perc,EUROPE_MARKETS_perc,EAFE_MARKETS_perc
0,2024-12-31,3708,41,10,73,0.00,0.00,0.0,0.00
1,2025-01-02,3703,41,10,73,-0.13,0.00,0.0,0.00
2,2025-01-03,3738,41,10,73,0.81,0.00,0.0,0.00
3,2025-01-06,3763,41,11,74,1.48,0.00,10.0,1.37
4,2025-01-07,3734,41,11,74,0.70,0.00,10.0,1.37
...,...,...,...,...,...,...,...,...,...
253,2025-12-23,4464,54,13,96,20.39,31.71,30.0,31.51
254,2025-12-24,4474,54,13,96,20.66,31.71,30.0,31.51
255,2025-12-26,4473,55,13,97,20.63,34.15,30.0,32.88
256,2025-12-29,4461,55,13,96,20.31,34.15,30.0,31.51
257,2025-12-30,4458,55,13,96,20.23,34.15,30.0,31.51

In [37]:
world_emerging_europe_eafe_without_today[["Date","MSCI_WORLD_perc","EMERGING_MARKETS_perc","EUROPE_MARKETS_perc","EAFE_MARKETS_perc"]].iloc[-1].to_csv("currently.csv")

In [45]:
world_emerging_europe_eafe_without_today[["Date","MSCI_WORLD_perc","EMERGING_MARKETS_perc","EUROPE_MARKETS_perc","EAFE_MARKETS_perc"]].iloc[-1]

Date                     2025-12-30 00:00:00
MSCI_WORLD_perc                        20.23
EMERGING_MARKETS_perc                  34.15
EUROPE_MARKETS_perc                     30.0
EAFE_MARKETS_perc                      31.51
Name: 257, dtype: object

In [38]:
EURUS="USDEUR=X"

In [40]:
EUROKurs = yfinance.download (tickers = EURUS, start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
                              interval = "1d")
EUROKurs

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_38781/1879854592.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  EUROKurs = yfinance.download (tickers = EURUS, start = date_365_days_ago_str, end= end_of_year.strftime("%Y-%m-%d"),
[*********************100%***********************]  1 of 1 completed

Price         Close     High      Low     Open   Volume
Ticker     USDEUR=X USDEUR=X USDEUR=X USDEUR=X USDEUR=X
Date
2024-12-31  0.96097  0.96632  0.95930  0.96097        0
2025-01-02  0.96601  0.97734  0.96380  0.96601        0
2025-01-03  0.97388  0.97414  0.97037  0.97388        0
2025-01-06  0.97037  0.97122  0.95831  0.97037        0
2025-01-07  0.96280  0.96530  0.95820  0.96280        0
...             ...      ...      ...      ...      ...
2025-12-23  0.84991  0.85003  0.84720  0.85002        0
2025-12-24  0.84778  0.84931  0.84680  0.84777        0
2025-12-26  0.84851  0.85012  0.84750  0.84862        0
2025-12-29  0.84942  0.85077  0.84828  0.84926        0
2025-12-30  0.84941  0.85134  0.84880  0.84940        0

[257 rows x 5 columns]

In [41]:
EUROKurs=reduce_index(EUROKurs,"EURO")
EUROKurs

          Date     EURO
0   2024-12-31  0.96097
1   2025-01-02  0.96601
2   2025-01-03  0.97388
3   2025-01-06  0.97037
4   2025-01-07  0.96280
..         ...      ...
252 2025-12-23  0.84991
253 2025-12-24  0.84778
254 2025-12-26  0.84851
255 2025-12-29  0.84942
256 2025-12-30  0.84941

[257 rows x 2 columns]

In [42]:
def converter_perc_euro(index_name):
    df_perc=pd.DataFrame()
    df_perc["Date"]=EUROKurs["Date"]
    col_important=EUROKurs[index_name]
    base_value=col_important.iloc[0]
    df_perc[index_name+"_perc"]=(col_important-base_value)*100/base_value
    df_perc[index_name+"_perc"] = df_perc[index_name+"_perc"].apply(lambda x: float(Decimal(str(x)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)))

    return(df_perc)

In [43]:
df_perc=pd.DataFrame()
df_perc["Date"]=EUROKurs["Date"]
col_important=EUROKurs["EURO"]
base_value=col_important.iloc[0]
print(base_value)
df_perc["EURO_perc"]=(col_important-base_value)*100/base_value
df_perc

0.9609699845314026

          Date  EURO_perc
0   2024-12-31   0.000000
1   2025-01-02   0.524469
2   2025-01-03   1.343435
3   2025-01-06   0.978179
4   2025-01-07   0.190437
..         ...        ...
252 2025-12-23 -11.557069
253 2025-12-24 -11.778723
254 2025-12-26 -11.702754
255 2025-12-29 -11.608060
256 2025-12-30 -11.609102

[257 rows x 2 columns]

In [44]:
df_perc.to_csv("euro_perc.csv")