In [1]:
import pandas as pd
import requests
import numpy as np
from bs4 import BeautifulSoup
import yfinance
import os
import pygsheets
from decimal import Decimal, ROUND_HALF_UP
import locale
from datetime import datetime, timedelta
import json
import datawrapper
import time
import io
#https://github.com/patrickloeber/python-github-action-template?tab=readme-ov-file
# Set the locale to English (United States)
locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
#authorization
if "PYGSHEET" in os.environ:

    AUTH_DATA = os.environ["PYGSHEET"]
    whatever_json=json.loads(AUTH_DATA, strict=False)
    credentials = whatever_json

    gc = pygsheets.authorize(service_account_json=(json.dumps(whatever_json))
    )
else:

    gc = pygsheets.authorize(service_file='/Users/halukamaier-borst/Documents/trumptracker-459020-5b428916efa8.json')

In [2]:

# Get today's date
today = datetime.now()

# Get date 365 days ago
date_365_days_ago = today - timedelta(days=365)

# Format as string if needed
date_365_days_ago_str = date_365_days_ago.strftime("%Y-%m-%d")

print(date_365_days_ago_str)
today

2025-01-06

datetime.datetime(2026, 1, 6, 9, 17, 46, 103810)

In [3]:

shanghaicomposite = yfinance.download (tickers = "000001.SS", start = date_365_days_ago_str, 
                              interval = "1d")
shanghaicomposite

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open      Volume
Ticker        000001.SS    000001.SS    000001.SS    000001.SS   000001.SS
Date
2025-01-06  3206.923096  3219.488037  3185.462891  3209.782959      431000
2025-01-07  3229.644043  3230.853027  3190.460938  3203.306885      409700
2025-01-08  3230.167969  3246.291016  3175.725098  3218.857910      472900
2025-01-09  3211.393066  3228.972900  3205.909912  3220.720947      382900
2025-01-10  3168.523926  3220.106934  3168.523926  3211.707031      403700
...                 ...          ...          ...          ...         ...
2025-12-29  3965.280029  3983.979004  3956.946045  3964.650879      563700
2025-12-30  3965.115967  3979.989990  3947.418945  3947.871094      525900
2025-12-31  3968.840088  3977.535889  3955.487061  3968.726074      490800
2026-01-05  4023.416992  4025.262939  3983.575928  3986.971924      597000
2026-01-06  4083.667236  4083.667236  4025.087891  4026.015869  1527750264

[243 rows x 5 columns]

In [4]:

dax40 = yfinance.download (tickers = "^GDAXI", start = date_365_days_ago_str,
                              interval = "1d")
dax40

[*********************100%***********************]  1 of 1 completed

Price              Close          High           Low          Open    Volume
Ticker            ^GDAXI        ^GDAXI        ^GDAXI        ^GDAXI    ^GDAXI
Date
2025-01-06  20216.189453  20216.189453  19921.119141  19982.660156  70784900
2025-01-07  20340.570312  20391.169922  20152.699219  20206.039062  62020000
2025-01-08  20329.939453  20480.490234  20242.560547  20322.169922  62954900
2025-01-09  20317.099609  20360.380859  20245.960938  20284.199219  50177100
2025-01-10  20214.789062  20400.519531  20187.970703  20316.550781  76245500
...                  ...           ...           ...           ...       ...
2025-12-29  24351.119141  24389.150391  24253.730469  24370.939453  35372300
2025-12-30  24490.410156  24527.939453  24328.419922  24343.189453  23179300
2026-01-02  24539.339844  24676.789062  24448.980469  24499.509766  48788700
2026-01-05  24868.689453  24872.919922  24639.679688  24681.349609  53518200
2026-01-06  24902.570312  24904.679688  24902.570312  24904.679688         0

[254 rows x 5 columns]

In [5]:
sandp500 = yfinance.download (tickers = "^GSPC", start = date_365_days_ago_str, 
                              interval = "1d")
sandp500

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2025-01-06  5975.379883  6021.040039  5960.009766  5982.810059  4940120000
2025-01-07  5909.029785  6000.680176  5890.680176  5993.259766  4517330000
2025-01-08  5918.250000  5927.890137  5874.779785  5910.660156  4441740000
2025-01-10  5827.040039  5890.350098  5807.779785  5890.350098  4751930000
2025-01-13  5836.220215  5838.609863  5773.310059  5782.020020  4421200000
...                 ...          ...          ...          ...         ...
2025-12-29  6905.740234  6920.209961  6888.759766  6903.600098  3541750000
2025-12-30  6896.240234  6913.250000  6893.470215  6900.439941  3309930000
2025-12-31  6845.500000  6901.419922  6844.549805  6898.819824  3261830000
2026-01-02  6858.470215  6894.870117  6824.310059  6878.109863  4184120000
2026-01-05  6902.049805  6920.379883  6891.560059  6892.189941  5771930000

[250 rows x 5 columns]

In [6]:
def reduce_index(df,indexname):
    index_red=pd.DataFrame()
    df["Date"]=df.index
    index_red["Date"]=df["Date"]

    index_red[indexname]=df[df.columns[0]]

    index_red=index_red.reset_index(drop=True)
    return index_red

In [7]:
sandp500_red=reduce_index(sandp500,"S&P500")
dax40_red=reduce_index(dax40,"DAX40")
shanghaicomposite_red=reduce_index(shanghaicomposite,"SHANGHAI")
shanghaicomposite_red

          Date     SHANGHAI
0   2025-01-06  3206.923096
1   2025-01-07  3229.644043
2   2025-01-08  3230.167969
3   2025-01-09  3211.393066
4   2025-01-10  3168.523926
..         ...          ...
238 2025-12-29  3965.280029
239 2025-12-30  3965.115967
240 2025-12-31  3968.840088
241 2026-01-05  4023.416992
242 2026-01-06  4083.667236

[243 rows x 2 columns]

In [8]:
sandp500_dax40=pd.merge(sandp500_red, dax40_red, on="Date", how="outer")
sandp500_dax40=sandp500_dax40.fillna(method="ffill")
sandp500_dax40

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_35927/2964685221.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sandp500_dax40=sandp500_dax40.fillna(method="ffill")

          Date       S&P500         DAX40
0   2025-01-06  5975.379883  20216.189453
1   2025-01-07  5909.029785  20340.570312
2   2025-01-08  5918.250000  20329.939453
3   2025-01-09  5918.250000  20317.099609
4   2025-01-10  5827.040039  20214.789062
..         ...          ...           ...
254 2025-12-30  6896.240234  24490.410156
255 2025-12-31  6845.500000  24490.410156
256 2026-01-02  6858.470215  24539.339844
257 2026-01-05  6902.049805  24868.689453
258 2026-01-06  6902.049805  24902.570312

[259 rows x 3 columns]

In [9]:
sandp500_dax40_shanghai=pd.merge(sandp500_dax40, shanghaicomposite_red, on="Date", how="outer")
sandp500_dax40_shanghai=sandp500_dax40_shanghai.fillna(method="ffill")
sandp500_dax40_shanghai

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_35927/2476299639.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sandp500_dax40_shanghai=sandp500_dax40_shanghai.fillna(method="ffill")

          Date       S&P500         DAX40     SHANGHAI
0   2025-01-06  5975.379883  20216.189453  3206.923096
1   2025-01-07  5909.029785  20340.570312  3229.644043
2   2025-01-08  5918.250000  20329.939453  3230.167969
3   2025-01-09  5918.250000  20317.099609  3211.393066
4   2025-01-10  5827.040039  20214.789062  3168.523926
..         ...          ...           ...          ...
256 2025-12-30  6896.240234  24490.410156  3965.115967
257 2025-12-31  6845.500000  24490.410156  3968.840088
258 2026-01-02  6858.470215  24539.339844  3968.840088
259 2026-01-05  6902.049805  24868.689453  4023.416992
260 2026-01-06  6902.049805  24902.570312  4083.667236

[261 rows x 4 columns]

In [10]:
now = datetime.now()
today=now.strftime("%Y-%m-%d")
since_election=sandp500_dax40_shanghai[sandp500_dax40_shanghai["Date"]>=date_365_days_ago_str]
since_election_without_today=since_election[since_election["Date"]!=today]
since_election_without_today

          Date       S&P500         DAX40     SHANGHAI
0   2025-01-06  5975.379883  20216.189453  3206.923096
1   2025-01-07  5909.029785  20340.570312  3229.644043
2   2025-01-08  5918.250000  20329.939453  3230.167969
3   2025-01-09  5918.250000  20317.099609  3211.393066
4   2025-01-10  5827.040039  20214.789062  3168.523926
..         ...          ...           ...          ...
255 2025-12-29  6905.740234  24351.119141  3965.280029
256 2025-12-30  6896.240234  24490.410156  3965.115967
257 2025-12-31  6845.500000  24490.410156  3968.840088
258 2026-01-02  6858.470215  24539.339844  3968.840088
259 2026-01-05  6902.049805  24868.689453  4023.416992

[260 rows x 4 columns]

In [11]:
for col in since_election_without_today.columns[1:]:
    since_election_without_today[col]= since_election_without_today[col].apply(lambda x: Decimal(str(x)))

    # Example: Perform precise rounding on the Decimal column
    since_election_without_today[col]= since_election_without_today[col].apply(lambda x: x.quantize(Decimal('1'), rounding=ROUND_HALF_UP))
since_election_without_today

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_35927/3670032238.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  since_election_without_today[col]= since_election_without_today[col].apply(lambda x: Decimal(str(x)))
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_35927/3670032238.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  since_election_without_today[col]= since_election_without_today[col].apply(lambda x: x.quantize(Decimal('1'), rounding=ROUND_HALF_UP))

          Date S&P500  DAX40 SHANGHAI
0   2025-01-06   5975  20216     3207
1   2025-01-07   5909  20341     3230
2   2025-01-08   5918  20330     3230
3   2025-01-09   5918  20317     3211
4   2025-01-10   5827  20215     3169
..         ...    ...    ...      ...
255 2025-12-29   6906  24351     3965
256 2025-12-30   6896  24490     3965
257 2025-12-31   6846  24490     3969
258 2026-01-02   6858  24539     3969
259 2026-01-05   6902  24869     4023

[260 rows x 4 columns]

In [12]:
since_election_without_today[since_election_without_today["Date"]=="2025-05-01"]

         Date S&P500  DAX40 SHANGHAI
83 2025-05-01   5604  22497     3279

In [ ]:
def retrieve_from_investing(index):
    index_to_shortform_dict={"S&P500":"us-spx-500","DAX40":"germany-30",	"SHANGHAI":"shanghai-composite"}
    now = datetime.now()
    yesterday = now - timedelta(days=1)
    formatted_date = yesterday.strftime("%m/%d/%Y")
    index_shortform=index_to_shortform_dict[index]

    time.sleep(10)

    url=f"https://www.investing.com/indices/{index_shortform}-historical-data#:~:text=Daily-,Download,-{formatted_date}"
    print(url)
    response = requests.get(url)


    # Check if the request was successful
    if response.status_code == 200:
        # Parse the HTML content of the page
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find the first table on the page
        table = soup.find('table', class_="freeze-column-w-1 w-full overflow-x-auto text-xs leading-4")

        # Extract rows from the table
        rows = table.find_all('tr')

        # Extract data from each row
        table_data = []
        for row in rows:
            cells = row.find_all(['td', 'th'])  # Get all cells (both <td> and <th>)
            cell_data = [cell.get_text(strip=True) for cell in cells]  # Extract text
            table_data.append(cell_data)

        # Return the extracted table data
        return(table_data)
    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")

In [14]:
df_to_check=since_election_without_today
columns_to_round = ['S&P500','DAX40','SHANGHAI']

# Apply Decimal rounding to the specified columns
df_to_check[columns_to_round] = df_to_check[columns_to_round].applymap(lambda x: Decimal(str(x)).quantize(Decimal('1'), rounding=ROUND_HALF_UP))

for index_name in since_election_without_today.columns[1:]:
    print(index_name)
    array=retrieve_from_investing(index_name)
    crosscheck_data=pd.DataFrame(array)
    crosscheck_data.replace("",np.nan,inplace=True)

    crosscheck_data=crosscheck_data.dropna(how="all")
    crosscheck_data[0]=pd.to_datetime(crosscheck_data[0], format="%b %d, %Y", errors="coerce")
    crosscheck_data_red=crosscheck_data[[0,1]]
    crosscheck_data_red=crosscheck_data_red.dropna(subset=[0])
    crosscheck_data_red.columns=["Date",index_name+"check"]
    crosscheck_data_red=crosscheck_data_red.sort_values(by="Date", ascending=True)
    crosscheck_data_red[index_name+"check"]=crosscheck_data_red[index_name+"check"].str.replace(",","")
    crosscheck_data_red[index_name+"check"]=crosscheck_data_red[index_name+"check"].astype(float)

    crosscheck_data_red[index_name+"check"]= crosscheck_data_red[index_name+"check"].apply(lambda x: Decimal(str(x)))

# Example: Perform precise rounding on the Decimal column
    crosscheck_data_red[index_name+"check"] = crosscheck_data_red[index_name+"check"].apply(lambda x: x.quantize(Decimal('1'), rounding=ROUND_HALF_UP))
    print("crosscheckdata")
    print(crosscheck_data_red.tail(5))
    print("df_to_check")

    print(df_to_check.tail(5))

#    df_to_check=pd.merge(df_to_check,crosscheck_data_red, on="Date", how="outer", suffixes=["_raw","_crosscheck"])

    df_to_check=pd.merge(df_to_check,crosscheck_data_red, on="Date", how="outer", suffixes=["_raw","_crosscheck"])
df_to_check=df_to_check.fillna(method="ffill")
df_to_check

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_85003/1710883695.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_to_check[columns_to_round] = df_to_check[columns_to_round].applymap(lambda x: Decimal(str(x)).quantize(Decimal('1'), rounding=ROUND_HALF_UP))
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_85003/1710883695.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_to_check[columns_to_round] = df_to_check[columns_to_round].applymap(lambda x: Decimal(str(x)).quantize(Decimal('1'), rounding=ROUND_HALF_UP))

S&P500
https://www.investing.com/indices/us-spx-500-historical-data#:~:text=Daily-,Download,-12/10/2025

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_85003/1710883695.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  crosscheck_data.replace("",np.nan,inplace=True)

crosscheckdata
        Date S&P500check
5 2025-12-03        6850
4 2025-12-04        6857
3 2025-12-05        6870
2 2025-12-08        6847
1 2025-12-09        6841
df_to_check
          Date S&P500  DAX40 SHANGHAI
255 2025-12-03   6850  23694     3878
256 2025-12-04   6857  23882     3876
257 2025-12-05   6870  24028     3903
258 2025-12-08   6847  24046     3924
259 2025-12-09   6841  24163     3910
DAX40
https://www.investing.com/indices/germany-30-historical-data#:~:text=Daily-,Download,-12/10/2025
crosscheckdata
        Date DAX40check
5 2025-12-04      23882
4 2025-12-05      24028
3 2025-12-08      24046
2 2025-12-09      24163
1 2025-12-10      24061
df_to_check
          Date S&P500  DAX40 SHANGHAI S&P500check
255 2025-12-03   6850  23694     3878        6850
256 2025-12-04   6857  23882     3876        6857
257 2025-12-05   6870  24028     3903        6870
258 2025-12-08   6847  24046     3924        6847
259 2025-12-09   6841  24163     3910        6841
SHANGHAI
https://www.investing.com/indices/shanghai-composite-historical-data#:~:text=Daily-,Download,-12/10/2025
crosscheckdata
        Date SHANGHAIcheck
5 2025-12-04          3876
4 2025-12-05          3903
3 2025-12-08          3924
2 2025-12-09          3910
1 2025-12-10          3901
df_to_check
          Date S&P500  DAX40 SHANGHAI S&P500check DAX40check
256 2025-12-04   6857  23882     3876        6857      23882
257 2025-12-05   6870  24028     3903        6870      24028
258 2025-12-08   6847  24046     3924        6847      24046
259 2025-12-09   6841  24163     3910        6841      24163
260 2025-12-10    NaN    NaN      NaN         NaN      24061

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_85003/1710883695.py:35: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_to_check=df_to_check.fillna(method="ffill")

          Date S&P500  DAX40 SHANGHAI S&P500check DAX40check SHANGHAIcheck
0   2024-12-10   6035  20329     3423         NaN        NaN           NaN
1   2024-12-11   6084  20399     3432         NaN        NaN           NaN
2   2024-12-12   6051  20426     3462         NaN        NaN           NaN
3   2024-12-13   6051  20406     3392         NaN        NaN           NaN
4   2024-12-16   6074  20314     3386         NaN        NaN           NaN
..         ...    ...    ...      ...         ...        ...           ...
256 2025-12-04   6857  23882     3876        6857      23882          3876
257 2025-12-05   6870  24028     3903        6870      24028          3903
258 2025-12-08   6847  24046     3924        6847      24046          3924
259 2025-12-09   6841  24163     3910        6841      24163          3910
260 2025-12-10   6841  24163     3910        6841      24061          3901

[261 rows x 7 columns]

In [15]:
for index_name in since_election_without_today.columns[1:]:

    df_to_check[index_name+"overlap"]=df_to_check[index_name]/df_to_check[index_name+"check"]
df_to_check

,Date,S&P500,DAX40,SHANGHAI,S&P500check,DAX40check,SHANGHAIcheck,S&P500overlap,DAX40overlap,SHANGHAIoverlap
0,2024-12-10,6035,20329,3423,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-12-11,6084,20399,3432,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-12-12,6051,20426,3462,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-12-13,6051,20406,3392,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-12-16,6074,20314,3386,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
256,2025-12-04,6857,23882,3876,6857,23882,3876,1,1,1
257,2025-12-05,6870,24028,3903,6870,24028,3903,1,1,1
258,2025-12-08,6847,24046,3924,6847,24046,3924,1,1,1
259,2025-12-09,6841,24163,3910,6841,24163,3910,1,1,1
260,2025-12-10,6841,24163,3910,6841,24061,3901,1,1.004239225302356510535721707,1.002307100743399128428608049

In [16]:
overlap_cols=df_to_check.columns[df_to_check.columns.str.contains("overlap")]
overlap_cols

Index(['S&P500overlap', 'DAX40overlap', 'SHANGHAIoverlap'], dtype='object')

In [17]:
(df_to_check[overlap_cols]==1).all(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
256     True
257     True
258     True
259     True
260    False
Length: 261, dtype: bool

In [18]:
df_to_check["all_equal"]=(df_to_check[overlap_cols]==1).all(axis=1)
df_to_check

,Date,S&P500,DAX40,SHANGHAI,S&P500check,DAX40check,SHANGHAIcheck,S&P500overlap,DAX40overlap,SHANGHAIoverlap,all_equal
0,2024-12-10,6035,20329,3423,NaN,NaN,NaN,NaN,NaN,NaN,False
1,2024-12-11,6084,20399,3432,NaN,NaN,NaN,NaN,NaN,NaN,False
2,2024-12-12,6051,20426,3462,NaN,NaN,NaN,NaN,NaN,NaN,False
3,2024-12-13,6051,20406,3392,NaN,NaN,NaN,NaN,NaN,NaN,False
4,2024-12-16,6074,20314,3386,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
256,2025-12-04,6857,23882,3876,6857,23882,3876,1,1,1,True
257,2025-12-05,6870,24028,3903,6870,24028,3903,1,1,1,True
258,2025-12-08,6847,24046,3924,6847,24046,3924,1,1,1,True
259,2025-12-09,6841,24163,3910,6841,24163,3910,1,1,1,True
260,2025-12-10,6841,24163,3910,6841,24061,3901,1,1.004239225302356510535721707,1.002307100743399128428608049,False

In [19]:

checked_df=df_to_check[df_to_check["all_equal"]==True]
checked_df

,Date,S&P500,DAX40,SHANGHAI,S&P500check,DAX40check,SHANGHAIcheck,S&P500overlap,DAX40overlap,SHANGHAIoverlap,all_equal
238,2025-11-10,6832,23960,4019,6832,23960,4019,1,1,1,True
239,2025-11-11,6847,24088,4003,6847,24088,4003,1,1,1,True
240,2025-11-12,6851,24381,4000,6851,24381,4000,1,1,1,True
241,2025-11-13,6737,24042,4030,6737,24042,4030,1,1,1,True
242,2025-11-14,6734,23877,3990,6734,23877,3990,1,1,1,True
243,2025-11-17,6672,23591,3972,6672,23591,3972,1,1,1,True
244,2025-11-18,6617,23181,3940,6617,23181,3940,1,1,1,True
245,2025-11-19,6642,23163,3947,6642,23163,3947,1,1,1,True
246,2025-11-20,6539,23279,3931,6539,23279,3931,1,1,1,True
247,2025-11-21,6603,23092,3835,6603,23092,3835,1,1,1,True
248,2025-11-24,6705,23239,3837,6705,23239,3837,1,1,1,True
249,2025-11-25,6766,23465,3870,6766,23465,3870,1,1,1,True
250,2025-11-26,6813,23726,3864,6813,23726,3864,1,1,1,True
251,2025-11-27,6813,23768,3875,6813,23768,3875,1,1,1,True
252,2025-11-28,6849,23837,3889,6849,23837,3889,1,1,1,True
253,2025-12-01,6813,23589,3914,6813,23589,3914,1,1,1,True
254,2025-12-02,6829,23711,3898,6829,23711,3898,1,1,1,True
255,2025-12-03,6850,23694,3878,6850,23694,3878,1,1,1,True
256,2025-12-04,6857,23882,3876,6857,23882,3876,1,1,1,True
257,2025-12-05,6870,24028,3903,6870,24028,3903,1,1,1,True
258,2025-12-08,6847,24046,3924,6847,24046,3924,1,1,1,True
259,2025-12-09,6841,24163,3910,6841,24163,3910,1,1,1,True

In [20]:
checked_df_red=checked_df[checked_df.columns[:4]]
checked_df_red["Date"]=checked_df_red["Date"].dt.strftime("%Y-%m-%d")
checked_df_red

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_85003/3470133631.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  checked_df_red["Date"]=checked_df_red["Date"].dt.strftime("%Y-%m-%d")

           Date S&P500  DAX40 SHANGHAI
238  2025-11-10   6832  23960     4019
239  2025-11-11   6847  24088     4003
240  2025-11-12   6851  24381     4000
241  2025-11-13   6737  24042     4030
242  2025-11-14   6734  23877     3990
243  2025-11-17   6672  23591     3972
244  2025-11-18   6617  23181     3940
245  2025-11-19   6642  23163     3947
246  2025-11-20   6539  23279     3931
247  2025-11-21   6603  23092     3835
248  2025-11-24   6705  23239     3837
249  2025-11-25   6766  23465     3870
250  2025-11-26   6813  23726     3864
251  2025-11-27   6813  23768     3875
252  2025-11-28   6849  23837     3889
253  2025-12-01   6813  23589     3914
254  2025-12-02   6829  23711     3898
255  2025-12-03   6850  23694     3878
256  2025-12-04   6857  23882     3876
257  2025-12-05   6870  24028     3903
258  2025-12-08   6847  24046     3924
259  2025-12-09   6841  24163     3910

In [21]:
#Open the google spreadsheet
sh = gc.open('TrumptrackerRaw')
sheet_name = "RawIndices"  # Replace with the name of the sheet you want to select
wks = sh.worksheet_by_title(sheet_name)


#Get the data from the Sheet into python as DF
read_indices = wks.get_as_df()
read_indices_red=read_indices[read_indices.columns[:4]]
read_indices_red

           Date  S&P500  DAX40  SHANGHAI
0    2024-12-10    6035  20329      3423
1    2024-12-11    6084  20399      3432
2    2024-12-12    6051  20426      3462
3    2024-12-13    6051  20406      3392
4    2024-12-16    6074  20314      3386
..          ...     ...    ...       ...
255  2025-12-03    6850  23694      3878
256  2025-12-04    6857  23882      3876
257  2025-12-05    6870  24028      3903
258  2025-12-08    6847  24046      3924
259  2025-12-09    6841  24163      3910

[260 rows x 4 columns]

In [22]:
read_plus_new_checked=pd.concat([read_indices_red,checked_df_red], axis=0, ignore_index=True)

read_plus_new_checked.drop_duplicates(subset=["Date"], keep="first", inplace=True)
read_plus_new_checked.reset_index(drop=True, inplace=True)
read_plus_new_checked

           Date S&P500  DAX40 SHANGHAI
0    2024-12-10   6035  20329     3423
1    2024-12-11   6084  20399     3432
2    2024-12-12   6051  20426     3462
3    2024-12-13   6051  20406     3392
4    2024-12-16   6074  20314     3386
..          ...    ...    ...      ...
255  2025-12-03   6850  23694     3878
256  2025-12-04   6857  23882     3876
257  2025-12-05   6870  24028     3903
258  2025-12-08   6847  24046     3924
259  2025-12-09   6841  24163     3910

[260 rows x 4 columns]

In [23]:
read_plus_new_checked["Date"]=pd.to_datetime(read_plus_new_checked["Date"])
read_plus_new_checked=read_plus_new_checked[read_plus_new_checked["Date"]>date_365_days_ago]
read_plus_new_checked

          Date S&P500  DAX40 SHANGHAI
1   2024-12-11   6084  20399     3432
2   2024-12-12   6051  20426     3462
3   2024-12-13   6051  20406     3392
4   2024-12-16   6074  20314     3386
5   2024-12-17   6051  20246     3361
..         ...    ...    ...      ...
255 2025-12-03   6850  23694     3878
256 2025-12-04   6857  23882     3876
257 2025-12-05   6870  24028     3903
258 2025-12-08   6847  24046     3924
259 2025-12-09   6841  24163     3910

[259 rows x 4 columns]

In [24]:
def converter_perc(index_name):
    df_perc=pd.DataFrame()
    df_perc["Date"]=read_plus_new_checked["Date"]
    col_important=read_plus_new_checked[index_name]
    base_value=col_important.iloc[0]
    df_perc[index_name+"_perc"]=(col_important-base_value)*100/base_value
    df_perc[index_name+"_perc"] = df_perc[index_name+"_perc"].apply(lambda x: float(Decimal(str(x)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)))

    return(df_perc)

In [25]:
for col in read_plus_new_checked.columns[1:]:
    df_perc=converter_perc(col)
    read_plus_new_checked=pd.merge(read_plus_new_checked,df_perc,on="Date",how="outer",suffixes=["_abs","_perc"])
read_plus_new_checked

          Date S&P500  DAX40 SHANGHAI  S&P500_perc  DAX40_perc  SHANGHAI_perc
0   2024-12-11   6084  20399     3432         0.00        0.00           0.00
1   2024-12-12   6051  20426     3462        -0.54        0.13           0.87
2   2024-12-13   6051  20406     3392        -0.54        0.03          -1.17
3   2024-12-16   6074  20314     3386        -0.16       -0.42          -1.34
4   2024-12-17   6051  20246     3361        -0.54       -0.75          -2.07
..         ...    ...    ...      ...          ...         ...            ...
254 2025-12-03   6850  23694     3878        12.59       16.15          13.00
255 2025-12-04   6857  23882     3876        12.71       17.07          12.94
256 2025-12-05   6870  24028     3903        12.92       17.79          13.72
257 2025-12-08   6847  24046     3924        12.54       17.88          14.34
258 2025-12-09   6841  24163     3910        12.44       18.45          13.93

[259 rows x 7 columns]

In [26]:



#open the google spreadsheet (where 'PY to Gsheet Test' is the name of my sheet)
sh = gc.open('TrumptrackerRaw')

#select the first sheet 
wks = sh[0]

wks.set_dataframe(read_plus_new_checked,(0,0))

/Users/halukamaier-borst/Documents/CodeRelated/HBDataviz/2025/08_Trumptracker/.venv/lib/python3.12/site-packages/pygsheets/worksheet.py:1431: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(nan)

In [27]:
# Get the current year
current_year = datetime.now().year
print(current_year)

2025

In [28]:
df=pd.DataFrame()
for year in range(2024,current_year+1):
    print(year)
    url=f"https://home.treasury.gov/resource-center/data-chart-center/interest-rates/daily-treasury-rates.csv/{year}/all?type=daily_treasury_yield_curve&field_tdr_date_value={year}&page&_format=csv"
    response = requests.get(url)

    file_object = io.StringIO(response.content.decode('utf-8'))
    data=pd.read_csv(file_object)
    df=pd.concat([df,data],axis=0)
df

2024
2025

,Date,1 Mo,2 Mo,3 Mo,4 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr,1.5 Month
0,12/31/2024,4.40,4.39,4.37,4.32,4.24,4.16,4.25,4.27,4.38,4.48,4.58,4.86,4.78,NaN
1,12/30/2024,4.43,4.42,4.37,4.33,4.25,4.17,4.24,4.29,4.37,4.46,4.55,4.84,4.77,NaN
2,12/27/2024,4.44,4.43,4.31,4.35,4.29,4.20,4.31,4.36,4.45,4.53,4.62,4.89,4.82,NaN
3,12/26/2024,4.45,4.45,4.35,4.37,4.31,4.23,4.30,4.35,4.42,4.49,4.58,4.83,4.76,NaN
4,12/24/2024,4.44,4.44,4.40,4.38,4.30,4.24,4.29,4.36,4.43,4.52,4.59,4.84,4.76,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,01/08/2025,4.41,4.34,4.35,4.31,4.25,4.19,4.28,4.31,4.45,4.56,4.67,4.97,4.91,NaN
230,01/07/2025,4.42,4.35,4.35,4.31,4.24,4.19,4.30,4.33,4.46,4.57,4.67,4.97,4.91,NaN
231,01/06/2025,4.43,4.36,4.35,4.31,4.24,4.17,4.28,4.30,4.42,4.52,4.62,4.91,4.85,NaN
232,01/03/2025,4.44,4.35,4.34,4.31,4.25,4.18,4.28,4.32,4.41,4.51,4.60,4.88,4.82,NaN
233,01/02/2025,4.45,4.36,4.36,4.31,4.25,4.17,4.25,4.29,4.38,4.47,4.57,4.86,4.79,NaN

In [29]:
df["Date"]=pd.to_datetime(df["Date"])
since_election_yield=df[df["Date"]>=date_365_days_ago]
since_election_yield=since_election_yield[["Date","10 Yr"]]
since_election_yield=since_election_yield.sort_values(by="Date", ascending=True)
since_election_yield

         Date  10 Yr
13 2024-12-11   4.26
12 2024-12-12   4.32
11 2024-12-13   4.40
10 2024-12-16   4.39
9  2024-12-17   4.40
..        ...    ...
4  2025-12-03   4.06
3  2025-12-04   4.11
2  2025-12-05   4.14
1  2025-12-08   4.17
0  2025-12-09   4.18

[248 rows x 2 columns]

In [30]:



#open the google spreadsheet (where 'PY to Gsheet Test' is the name of my sheet)
sh = gc.open('TrumptrackerRaw')

#select the first sheet 
sheet_name = "Yield"  # Replace with the name of the sheet you want to select
wks = sh.worksheet_by_title(sheet_name)


wks.set_dataframe(since_election_yield,(0,0))

In [31]:
if "DWKEY" in os.environ:

    DWKEY = os.environ["DWKEY"]
    print(len(DWKEY))


else:
    data=pd.read_csv("/Users/halukamaier-borst/Documents/Keys.csv")
    DWKEY=data.APIKey.iloc[1]

In [32]:
dw_connection = datawrapper.Datawrapper(access_token = DWKEY)

allcharts=dw_connection.get_charts(limit=500)

dw_connection.publish_chart(chart_id="50HqS")

{'data': {'publicId': '50HqS',
  'language': 'de-DE',
  'theme': 'handelsblatt',
  'id': '50HqS',
  'type': 'd3-lines',
  'title': 'So haben sich die Märkte in den letzten 365 Tagen verändert',
  'lastEditStep': 5,
  'publishedAt': '2025-12-10T08:48:11.992Z',
  'publicUrl': 'https://datawrapper.dwcdn.net/50HqS/827/',
  'publicVersion': 827,
  'deleted': False,
  'forkable': False,
  'isFork': False,
  'metadata': {'data': {'changes': [],
    'transpose': False,
    'vertical-header': True,
    'horizontal-header': True,
    'column-format': {'DAX40': {'type': 'auto', 'ignore': True},
     'S&P500': {'type': 'auto', 'ignore': True},
     'SHANGHAI': {'type': 'auto', 'ignore': True},
     'DAX40_abs': {'type': 'auto', 'ignore': True},
     'DAX40_perc': {'type': 'auto',
      'number-append': ' %',
      'number-prepend': ''},
     'S&P500_abs': {'type': 'auto', 'ignore': True},
     'S&P500_perc': {'type': 'auto',
      'number-append': ' %',
      'number-prepend': ''},
     'SHANGHAI_abs': {'type': 'auto', 'ignore': True},
     'SHANGHAI_perc': {'type': 'auto',
      'number-append': ' %',
      'number-prepend': ''}},
    'external-data': 'https://docs.google.com/spreadsheets/d/1_yZ4LeEpkOAEgcSfUVGrL0rgHsrfFL5rQzZHpM4EzMA/export?format=csv&id=1_yZ4LeEpkOAEgcSfUVGrL0rgHsrfFL5rQzZHpM4EzMA&gid=0',
    'upload-method': 'external-data',
    'use-datawrapper-cdn': True},
   'describe': {'source-name': 'YahooFinance/eigene Berechnung',
    'source-url': '',
    'intro': '<b>Veränderung der Schlusskurse innerhalb eines Jahres</b> in Prozent',
    'byline': '',
    'aria-description': '',
    'number-format': '-',
    'number-divisor': 0,
    'number-append': '',
    'number-prepend': ''},
   'visualize': {'dark-mode-invert': True,
    'highlighted-series': [],
    'highlighted-values': [],
    'sharing': {'enabled': False,
     'url': 'https://www.datawrapper.de/_/50HqS',
     'auto': False},
    'lines': {'DAX40_perc': {'title': 'Dax',
      'directLabel': False,
      'valueLabels': {'first': False, 'enabled': True}},
     'S&P500_perc': {'title': 'S&P500',
      'directLabel': False,
      'valueLabels': {'first': False, 'enabled': True}},
     'SHANGHAI_perc': {'title': 'Shanghai Composite',
      'directLabel': False,
      'valueLabels': {'first': False, 'enabled': True}}},
    'x-grid': 'off',
    'y-grid': 'on',
    'scale-y': 'linear',
    'striped': True,
    'overlays': [],
    'background': False,
    'base-color': 0,
    'compactMode': True,
    'label-colors': False,
    'label-margin': 0,
    'stack-to-100': False,
    'interpolation': 'linear',
    'show-tooltips': True,
    'x-grid-format': 'YYYY|MMM',
    'y-grid-format': '+',
    'y-grid-labels': 'auto',
    'chart-type-set': True,
    'color-category': {'map': {'DAX40_perc': '#3f7997',
      'S&P500_perc': '#ef7c00',
      'SHANGHAI_perc': '#e3b1a5'}},
    'custom-range-x': ['', ''],
    'custom-range-y': ['', ''],
    'custom-ticks-x': '',
    'custom-ticks-y': '',
    'plotHeightMode': 'fixed',
    'variate-colors': False,
    'connector-lines': True,
    'label-alignment': 'right',
    'plotHeightFixed': 300,
    'plotHeightRatio': 0.5,
    'text-annotations': [{'bg': True,
      'dx': 3,
      'dy': 64,
      'id': 'TP8Wv1VJLd',
      'bold': False,
      'size': 14,
      'text': '„Liberation Day" unter Trump',
      'align': 'tl',
      'color': False,
      'width': 19.97215420807528,
      'italic': False,
      'position': {'x': '2025/04/01 18:50', 'y': '-1.5'},
      'underline': False,
      'showMobile': True,
      'showDesktop': False,
      'connectorLine': {'type': 'curveRight',
       'circle': False,
       'stroke': 1,
       'enabled': False,
       'arrowHead': 'lines',
       'circleStyle': 'solid',
       'circleRadius': 15,
       'inheritColor': False,
       'targetPadding': 4},
      'mobileFallback': True},
     {'bg': True,
      'dx': -147,
      'dy': 35,
      'id': 'ADuTxH5oRv',
      'bold': False,
      'size': 14,
      'text': '„Liberation Day" unter Trump',
      'align': 'tl',
      'color': False,
      'width': 19.97215420807528,
      'italic': False,
      'position': {'x': '2025/04/01 10:08', 'y': '-2.4624'},
      'underline': False,
      'showMobile': False,
      'showDesktop': True,
      'connectorLine': {'type': 'curveLeft',
       'circle': False,
       'stroke': 1,
       'enabled': True,
       'arrowHead': 'lines',
       'circleStyle': 'solid',
       'circleRadius': 15,
       'inheritColor': False,
       'targetPadding': 4},
      'mobileFallback': True},
     {'bg': False,
      'dx': -97,
      'dy': 8,
      'id': 'GYgUy8On4R',
      'bold': False,
      'size': 14,
      'text': 'Rückgang durch Sorge um KI-Blase ',
      'align': 'tl',
      'color': False,
      'width': 15.931475460969082,
      'italic': False,
      'position': {'x': '2025/12/30 21:08', 'y': '7.3072'},
      'underline': False,
      'showMobile': True,
      'showDesktop': False,
      'connectorLine': {'type': 'curveLeft',
       'circle': False,
       'stroke': 1,
       'enabled': False,
       'arrowHead': 'lines',
       'circleStyle': 'solid',
       'circleRadius': 15,
       'inheritColor': False,
       'targetPadding': 4},
      'mobileFallback': True},
     {'bg': False,
      'dx': -121,
      'dy': 60,
      'id': 'J3g53m0dea',
      'bold': False,
      'size': 14,
      'text': 'Rückgang durch Sorge um KI-Blase',
      'align': 'tl',
      'color': False,
      'width': 15.931475460969082,
      'italic': False,
      'position': {'x': '2025/11/19 21:08', 'y': '7.3072'},
      'underline': False,
      'showMobile': False,
      'showDesktop': True,
      'connectorLine': {'type': 'curveLeft',
       'circle': False,
       'stroke': 1,
       'enabled': True,
       'arrowHead': 'lines',
       'circleStyle': 'solid',
       'circleRadius': 15,
       'inheritColor': False,
       'targetPadding': 4},
      'mobileFallback': True}],
    'tooltip-x-format': 'D.M.YYYY',
    'y-grid-subdivide': True,
    'custom-area-fills': [],
    'range-annotations': [{'id': 'ZJpAx8UmuG',
      'type': 'x',
      'color': '#aca094',
      'display': 'line',
      'opacity': 75,
      'position': {'x0': '2025/11/19 02:47',
       'x1': '2025/04/07 22:28',
       'y0': '24.7481',
       'y1': '0.0652'},
      'strokeType': 'dashed',
      'strokeWidth': 3},
     {'id': 'KP-HO-hBeJ',
      'type': 'x',
      'color': '#aca094',
      'display': 'line',
      'opacity': 75,
      'position': {'x0': '2025/04/02 02:47',
       'x1': '2025/04/07 22:28',
       'y0': '24.7481',
       'y1': '0.0652'},
      'strokeType': 'dashed',
      'strokeWidth': 3}],
    'value-label-colors': True,
    'y-grid-label-align': 'left'},
   'axes': {},
   'publish': {'embed-width': 320,
    'embed-height': 619,
    'blocks': {'logo': {'id': 'main', 'enabled': True},
     'embed': False,
     'download-pdf': False,
     'download-svg': False,
     'get-the-data': False,
     'download-image': False},
    'export-pdf': {},
    'embed-codes': {'embed-method-responsive': '<iframe title="So haben sich die Märkte in den letzten 365 Tagen verändert" aria-label="Liniendiagramm" id="datawrapper-chart-50HqS" src="https://datawrapper.dwcdn.net/50HqS/827/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="619" data-external="1"></iframe><script type="text/javascript">window.addEventListener("message",function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}});</script>',
     'embed-method-iframe': '<iframe title="So haben sich die Märkte in den letzten 365 Tagen verändert" aria-label="Liniendiagramm" id="datawrapper-chart-50HqS" src="https://datawrapper.dwcdn.net/50HqS/827/" scrolling="no" frameborder="0" style="border: none;" width="320" height="619" data-external="1"></iframe>',
     'embed-method-web-component': '<div style="min-height:619px" id="datawrapper-vis-50HqS"><script type="text/javascript" defer src="https://datawrapper.dwcdn.net/50HqS/embed.js" charset="utf-8" data-target="#datawrapper-vis-50HqS"></script><noscript><img src="https://datawrapper.dwcdn.net/50HqS/full.png" alt="So haben sich die Märkte in den letzten 365 Tagen verändert (Liniendiagramm)" /></noscript></div>'},
    'autoDarkMode': False,
    'chart-height': 443},
   'annotate': {'notes': ''},
   'custom': {'subhed': '', 'caption': ''}},
  'externalData': 'https://static.dwcdn.net/data/50HqS.csv',
  'utf8': False,
  'createdAt': '2025-05-05T14:18:34.000Z',
  'lastModifiedAt': '2025-12-10T08:48:11.992Z',
  'forkedFrom': None,
  'organizationId': 'handelsblatt-2',
  'authorId': 690161,
  'folderId': 370750,
  'workspace': 'handelsblatt',
  'deletedAt': None},
 'version': 827,
 'url': 'https://datawrapper.dwcdn.net/50HqS/827/'}